#!/usr/bin/env python3
# GENERATED by PrototypeFramework 0.4.2 from Documentation~/agent/hooks/pf-subagent-context.py — do not edit here. Change it in the framework repo, then run Framework/Agent Docs/Sync (editor) or Tools/Build/pf-build.sh agentdocs.
"""SubagentStart hook: give every subagent the project contract it cannot inherit.

A subagent launches with an empty context — no CLAUDE.md, no AGENTS.md, none of the parent's
conversation. Claude Code fires SubagentStart with {agent_id, agent_type} on stdin and injects
whatever this script prints as `additionalContext`.

Two sources, read in order and merged section by section:
  docs/framework/SUBAGENTS.md   the framework's half (written by the agent-doc sync)
  SUBAGENTS.md                  the SKU's own additions (optional, never written by the sync)

Each is split by `<!-- profile: NAME -->` markers into a preamble (before the first marker), `all`,
and one of `readonly` / `mutating`. Read-only agent types get the readonly half, so a Bash-capable
Explore agent is told, in words, not to write — its tool restrictions alone do not close that door.

Registered in .claude/settings.json by the same sync. Fails open: any problem here must never block
a subagent, so every path exits 0.
"""

import json
import os
import re
import sys

READ_ONLY_TYPES = {"Explore", "Plan", "claude-code-guide"}
MARKER = re.compile(r"^<!--\s*profile:\s*([a-z-]+)\s*-->\s*$", re.MULTILINE)
GENERATED = re.compile(r"^<!-- GENERATED by PrototypeFramework .*-->\s*$", re.MULTILINE)
SOURCES = (os.path.join("docs", "framework", "SUBAGENTS.md"), "SUBAGENTS.md")


def sections(text):
    """{'': preamble, 'all': ..., 'readonly': ..., 'mutating': ...}"""
    text = GENERATED.sub("", text)
    parts, last, name = {}, 0, ""
    for m in MARKER.finditer(text):
        parts[name] = text[last:m.start()].strip()
        name, last = m.group(1), m.end()
    parts[name] = text[last:].strip()
    return parts


def read(path):
    try:
        with open(path, encoding="utf-8") as fh:
            return fh.read()
    except OSError:
        return None


def main():
    try:
        payload = json.load(sys.stdin)
    except Exception:
        payload = {}
    agent_type = payload.get("agent_type") or ""
    profile = "readonly" if agent_type in READ_ONLY_TYPES else "mutating"

    root = os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd()
    docs = [sections(t) for t in (read(os.path.join(root, s)) for s in SOURCES) if t]
    if not docs:
        return 0

    chunks = []
    for key in ("", "all", profile):
        chunks.extend(d.get(key, "") for d in docs)
    context = "\n\n".join(c for c in chunks if c)
    if not context.strip():
        return 0

    json.dump(
        {
            "hookSpecificOutput": {
                "hookEventName": "SubagentStart",
                "additionalContext": context,
            }
        },
        sys.stdout,
    )
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception:
        sys.exit(0)
