'use strict';
const C=CardSlotCore, $=id=>document.getElementById(id), colors=['#F2475B','#3D8BFF','#FFC93C','#3CC26B','#9B5CF6','#FF8A3D','#FF6FB5','#2FCFE0'], names=['Đỏ','Xanh dương','Vàng','Xanh lá','Tím','Cam','Hồng','Cyan'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let level=C.normalize(CARDSLOT_PRESETS[0]),selected=null,undo=[],redo=[],game=null,hiddenLayers=new Set(),view={x:-120,y:-100,w:1200,h:1000},drag=null;
const colorIndex=c=>typeof c==='string'&&/^color_[0-7]$/.test(c)?Number(c.slice(6)):0, options=value=>names.map((n,i)=>`<option value="color_${i}" ${value==='color_'+i?'selected':''}>${n}</option>`).join('');
function toast(s){$('toast').textContent=s;$('toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('toast').style.display='none',3000);}
function persist(){try{localStorage.setItem('cardslot-working-v1',JSON.stringify(level));}catch{}}
function checkpoint(){undo.push(C.clone(level));if(undo.length>100)undo.shift();redo=[];}
function change(fn){if(game)return;checkpoint();fn();delete level.solution;persist();render();}
function load(l){checkpoint();level=C.normalize(l);selected=null;game=null;hiddenLayers.clear();persist();render();fit();}
function field(label,key,value,type='number',extra=''){return `<label class="field">${label}<input data-key="${key}" type="${type}" value="${esc(value)}" ${extra}></label>`;}
function nextId(){let n=0;while(level.stacks.some(s=>s.id==='s'+n))n++;return 's'+n;}
function addStack(c,child=false){change(()=>{const parent=level.stacks.find(s=>s.id===selected);const s={id:nextId(),x:Math.round(view.x+view.w/2-75),y:Math.round(view.y+view.h/2-103),w:150,h:206,layer:0,color:'color_'+c,count:6,fan:false,spread:true,spread_direction:1,spread_angle:0};if(child&&parent){if(parent.layer>=4){toast('Đã ở tầng cao nhất');return;}Object.assign(s,{x:parent.x+10,y:parent.y,w:parent.w,h:parent.h,layer:parent.layer+1,spread_angle:parent.spread_angle,on_stack:parent.id});}level.stacks.push(s);selected=s.id;});}
function render(){
  $('levelTitle').textContent=level.id; $('undo').disabled=!undo.length||!!game;$('redo').disabled=!redo.length||!!game;
  $('play').textContent=game?'■ Dừng bấm thử':'▷ Bấm thử';
  $('presets').innerHTML=CARDSLOT_PRESETS.map((l,i)=>`<button class="preset ${level.id===l.id?'active':''}" data-preset="${i}"><span class="num">0${i+1}</span><span><strong>Màn ${i+1}</strong><small>${l.stacks.length} cọc · ${l.stacks.reduce((n,s)=>n+s.count,0)} lá</small></span><span class="dots">${[...new Set(l.stacks.map(s=>s.color))].map(c=>`<i class="dot" style="background:${colors[colorIndex(c)]}"></i>`).join('')}</span></button>`).join('');
  $('layers').innerHTML=[4,3,2,1,0].map(n=>`<label class="layer"><input data-layer="${n}" type="checkbox" ${hiddenLayers.has(n)?'':'checked'}> Tầng ${n}<small>${level.stacks.filter(s=>s.layer===n).length} cọc</small></label><div class="layernodes">${level.stacks.filter(s=>s.layer===n).map(s=>`<button data-select="${esc(s.id)}" class="${selected===s.id?'chosen':''}"><i class="dot" style="background:${colors[colorIndex(s.color)]}"></i> ${esc(s.id)}</button>`).join('')}</div>`).join('');
  $('global').innerHTML=field('ID màn','id',level.id,'text')+`<div class="fields">${field('Revision','revision',level.revision)}${field('Seed','seed',level.seed)}${field('Số cọc đích','n_slots',level.n_slots,'number','min="2" max="4"')}${field('Sức chứa buffer','buffer_capacity',level.buffer_capacity,'number','min="1" max="60"')}</div>`+field('FTUE (tùy chọn)','ftue',level.ftue??'','text');
  $('global').querySelectorAll('[data-key]').forEach(el=>el.onchange=()=>change(()=>{level[el.dataset.key]=el.type==='number'?Number(el.value):el.value;}));
  $('targets').innerHTML=level.targets.map((t,i)=>`<div class="target"><i class="dot" style="background:${colors[colorIndex(t.color)]}"></i><select aria-label="Màu đích ${i+1}" data-color="${i}">${options(t.color)}</select><input aria-label="Sức chứa đích ${i+1}" type="number" min="2" max="36" value="${t.capacity}" data-capacity="${i}"><button title="Đưa lên" data-up="${i}">↑</button><button title="Xóa đích" data-delete-target="${i}">×</button></div>`).join('');
  $('targets').querySelectorAll('[data-color]').forEach(el=>el.onchange=()=>change(()=>level.targets[+el.dataset.color].color=el.value));
  $('targets').querySelectorAll('[data-capacity]').forEach(el=>el.onchange=()=>change(()=>level.targets[+el.dataset.capacity].capacity=Number(el.value)));
  $('targets').querySelectorAll('[data-up]').forEach(el=>el.onclick=()=>change(()=>{const i=+el.dataset.up;if(i>0)[level.targets[i-1],level.targets[i]]=[level.targets[i],level.targets[i-1]];}));
  $('targets').querySelectorAll('[data-delete-target]').forEach(el=>el.onclick=()=>change(()=>level.targets.splice(+el.dataset.deleteTarget,1)));
  const totals=names.map((_,i)=>({a:level.stacks.filter(s=>s.color==='color_'+i).reduce((n,s)=>n+s.count,0),b:level.targets.filter(t=>t.color==='color_'+i).reduce((n,t)=>n+t.capacity,0)}));
  $('balanceView').innerHTML=totals.map((t,i)=>t.a||t.b?`<span class="${t.a===t.b?'good':'bad'}"><i class="dot" style="background:${colors[i]}"></i> ${t.a} / ${t.b}</span>`:'').join('');
  const errors=C.validate(level);$('validation').innerHTML=errors.length?errors.map(e=>`<div class="issue">${esc(e)}</div>`).join(''):'<div class="valid">✓ Config hợp lệ để xuất vào game</div>';
  $('status').textContent=`${level.stacks.length} cọc · ${level.stacks.reduce((n,s)=>n+s.count,0)} lá · ${errors.length?errors.length+' vấn đề cần sửa':'Config hợp lệ'}${game?' · Bấm cọc sáng để chơi thử':''}`;
  inspector();renderBoard();renderGame();renderDrafts();
  for(const id of ['global','targets','inspector'])$(id).querySelectorAll('input,select,button').forEach(el=>el.disabled=!!game);
  for(const id of ['addTarget','balance','new','import','applyJson'])$(id).disabled=!!game;
}
function inspector(){
  const i=level.stacks.findIndex(s=>s.id===selected),s=level.stacks[i];
  if(!s){$('inspector').innerHTML='<div class="eyebrow">THUỘC TÍNH CỌC</div><h2>Chọn một cọc trên bàn</h2><p class="muted">Chỉnh vị trí, tầng, màu và quy luật xòe ở đây.</p>';return;}
  const p=C.resolve(level)[i],r=level.stacks[p.root],supports=level.stacks.filter(t=>t.layer<s.layer&&C.overlap(s,t)&&t.spread_angle===s.spread_angle);
  $('inspector').innerHTML=`<div class="eyebrow">CỌC ĐANG CHỌN</div><h2>${esc(s.id)} <span style="color:${colors[colorIndex(s.color)]}">●</span></h2>${field('ID cọc','id',s.id,'text')}<label class="field">Màu<select data-key="color">${options(s.color)}</select></label><div class="fields">${['x','y','w','h','layer','count'].map(k=>field(({x:'Vị trí X',y:'Vị trí Y',w:'Vùng chặn W',h:'Vùng chặn H',layer:'Tầng',count:'Số bài'})[k],k,s[k])).join('')}</div><label class="field">Kiểu xòe<select data-key="fan"><option value="false" ${!s.fan?'selected':''}>Thẳng</option><option value="true" ${s.fan?'selected':''}>Vòng</option></select></label><label class="field">Chiều xòe<select data-key="spread_direction"><option value="0" ${s.spread_direction===0?'selected':''}>Tự chọn theo vị trí</option><option value="1" ${s.spread_direction===1?'selected':''}>Thuận (+1)</option><option value="-1" ${s.spread_direction===-1?'selected':''}>Ngược (−1)</option></select></label>${field('Hướng xòe thẳng (0° ngang / 90° dọc)','spread_angle',s.spread_angle,'number','min="-180" max="180"')}<label class="field">Đặt tiếp trên cọc<select data-key="on_stack"><option value="">Tự tìm cọc phù hợp</option>${supports.map(t=>`<option value="${esc(t.id)}" ${s.on_stack===t.id?'selected':''}>${esc(t.id)} · tầng ${t.layer}</option>`).join('')}</select></label><p class="muted">${p.support>=0?`Đang nối trên <b>${esc(level.stacks[p.support].id)}</b>, kế thừa xòe từ <b>${esc(r.id)}</b>. Bắt đầu tại lá ${p.offset+1}.`:'Cọc gốc: các cọc phía trên sẽ kế thừa quy luật xòe này.'}</p><div class="row"><button id="duplicate">Nhân đôi</button><button id="child">+ Cọc phía trên</button><button id="remove">Xóa</button></div>`;
  $('inspector').querySelectorAll('[data-key]').forEach(el=>el.onchange=()=>{const k=el.dataset.key,v=el.value;if(k==='id'&&(!v||level.stacks.some(t=>t!==s&&t.id===v))){toast('ID không được trống hoặc trùng');render();return;}change(()=>{const old=s.id;s[k]=k==='fan'?v==='true':['id','color','on_stack'].includes(k)?v:Number(v);if(k==='id'){level.stacks.forEach(t=>{if(t.on_stack===old)t.on_stack=v;});selected=v;}if(k==='on_stack'&&!v)delete s.on_stack;});});
  $('duplicate').onclick=duplicate;$('remove').onclick=remove;$('child').onclick=()=>addStack((colorIndex(s.color)+1)%8,true);
}
function duplicate(){const s=level.stacks.find(s=>s.id===selected);if(!s||game)return;change(()=>{const n={...C.clone(s),id:nextId(),x:s.x+s.w+30};delete n.on_stack;level.stacks.push(n);selected=n.id;});}
function remove(){if(!selected||game)return;change(()=>{level.stacks=level.stacks.filter(s=>s.id!==selected);level.stacks.forEach(s=>{if(s.on_stack===selected)delete s.on_stack;});selected=null;});}
function renderBoard(){
  const poses=C.geometry(level,$('packed').checked), centres=poses.map(p=>p.cards.at(-1)||{x:0,y:0}), ss=level.stacks;
  const relationships=[];
  if($('relations').checked)ss.forEach((s,i)=>{if(hiddenLayers.has(s.layer))return;const p=poses[i];if(p.support>=0&&!hiddenLayers.has(ss[p.support].layer)){const a=centres[i],b=centres[p.support];relationships.push(`<path class="relation" d="M${a.x},${a.y} L${b.x},${b.y}" fill="none" stroke="#8e75c9" stroke-width="3" stroke-dasharray="7 5" marker-end="url(#arrow)"/>`);}if($('regions').checked)ss.forEach((t,j)=>{if(t.layer<s.layer&&t.color!==s.color&&C.overlap(s,t)&&!hiddenLayers.has(t.layer))relationships.push(`<path class="relation" d="M${s.x+s.w/2},${s.y+s.h/2} L${t.x+t.w/2},${t.y+t.h/2}" stroke="#d18f79" stroke-width="2" stroke-dasharray="3 5"/>`);});});
  const html=ss.map((s,i)=>({s,i})).sort((a,b)=>a.s.layer-b.s.layer||a.i-b.i).map(({s,i})=>{
    if(hiddenLayers.has(s.layer)||game&&!game.remaining[i])return '';const p=poses[i],cs=p.cards.slice(0,game?game.remaining[i]:s.count),c=colors[colorIndex(s.color)]||'#aaa',blocked=game&&C.covered(level,game,i),last=cs.at(-1);
    const body=cs.map((v,b)=>`<g transform="translate(${v.x} ${v.y}) rotate(${v.angle})"><rect x="-75" y="-98" width="150" height="200" rx="22" fill="#714f3328" transform="translate(3 5)"/><rect x="-75" y="-100" width="150" height="200" rx="22" fill="${c}" stroke="${b===cs.length-1?'#fff3cf':'#ffffff80'}" stroke-width="${b===cs.length-1?6:2}"/><rect x="-62" y="-87" width="124" height="174" rx="15" fill="none" stroke="#ffffffc9" stroke-width="3"/>${b===cs.length-1?'<path d="M-9 11 V-14 Q0-21 9-14 V11 M-4 11 V-10 M4 11 V-10" fill="none" stroke="#64452355" stroke-width="3"/>':''}</g>`).join('');
    return `<g class="stack ${selected===s.id?'selected':''} ${game&&!blocked?'playable':''}" data-stack="${esc(s.id)}" opacity="${blocked?.55:1}"><title>${esc(s.id)} · ${names[colorIndex(s.color)]} · ${s.count} lá · tầng ${s.layer}</title>${$('regions').checked?`<rect x="${s.x}" y="${s.y}" width="${s.w}" height="${s.h}" fill="#8d76b912" stroke="#9c87ba" stroke-dasharray="6 4"/>`:''}${body}${last?`<rect class="selection" x="${last.x-90}" y="${last.y-114}" width="180" height="228" rx="26"/><g transform="translate(${last.x} ${last.y+118})"><rect x="-51" y="-8" width="102" height="25" rx="12" fill="#fff9ed"/><text text-anchor="middle" y="9" fill="#927257" font-size="12" font-family="Segoe UI,sans-serif">${esc(s.id)} · L${s.layer} · ${s.count}</text></g>`:''}</g>`;
  }).join('');
  $('scene').innerHTML=($('grid').checked?`<rect x="${view.x-5000}" y="${view.y-5000}" width="15000" height="15000" fill="url(#gridPattern)"/>`:'')+html+relationships.join('');updateView();
}
function updateView(){$('board').setAttribute('viewBox',`${view.x} ${view.y} ${view.w} ${view.h}`);$('zoomLabel').textContent=Math.round(100*1000/view.w)+'%';}
function fit(){const ps=C.geometry(level,$('packed').checked).flatMap(p=>p.cards);if(!ps.length)return;const minX=Math.min(...ps.map(p=>p.x))-190,maxX=Math.max(...ps.map(p=>p.x))+190,minY=Math.min(...ps.map(p=>p.y))-190,maxY=Math.max(...ps.map(p=>p.y))+210;const bounds=$('board').getBoundingClientRect(),ratio=bounds.width/Math.max(1,bounds.height);let w=maxX-minX,h=maxY-minY;if(w/h<ratio)w=h*ratio;else h=w/ratio;view={x:(minX+maxX-w)/2,y:(minY+maxY-h)/2,w,h};renderBoard();}
function point(e){const p=$('board').createSVGPoint();p.x=e.clientX;p.y=e.clientY;return p.matrixTransform($('board').getScreenCTM().inverse());}
$('board').addEventListener('pointerdown',e=>{if(e.button!==0)return;const node=e.target.closest('[data-stack]'),id=node?.dataset.stack;if(game){if(id){const i=level.stacks.findIndex(s=>s.id===id);if(C.tap(level,game,i))render();else toast('Cọc này đang bị chặn');}return;}const p=point(e);if(id){selected=id;const s=level.stacks.find(s=>s.id===id);drag={id,start:p,x:s.x,y:s.y,before:C.clone(level),moved:false};inspector();}else{selected=null;drag={start:p,view:{...view}};inspector();}renderBoard();$('board').setPointerCapture(e.pointerId);});
$('board').addEventListener('pointermove',e=>{if(!drag)return;const p=point(e);if(drag.id){const s=level.stacks.find(s=>s.id===drag.id),snap=$('snap').checked?10:1;const dx=p.x-drag.start.x,dy=p.y-drag.start.y;if(Math.abs(dx)+Math.abs(dy)>2){drag.moved=true;s.x=Math.round((drag.x+dx)/snap)*snap;s.y=Math.round((drag.y+dy)/snap)*snap;renderBoard();}}else{view.x-=p.x-drag.start.x;view.y-=p.y-drag.start.y;updateView();}});
function endDrag(){if(drag?.id&&drag.moved){undo.push(drag.before);redo=[];delete level.solution;persist();}drag=null;render();}
$('board').addEventListener('pointerup',endDrag);$('board').addEventListener('pointercancel',endDrag);
$('board').addEventListener('wheel',e=>{e.preventDefault();const p=point(e),f=e.deltaY>0?1.12:1/1.12,nw=Math.max(250,Math.min(8000,view.w*f)),scale=nw/view.w;view={x:p.x-(p.x-view.x)*scale,y:p.y-(p.y-view.y)*scale,w:nw,h:view.h*scale};updateView();},{passive:false});
function renderGame(){$('playHud').hidden=!game;if(!game)return;const label={playing:'Đang chơi',won:'✓ Hoàn thành',overflow:'Buffer tràn',stuck:'Không còn nước đi an toàn'}[game.result];$('playHud').innerHTML=`<b>${label}</b> · ${game.moves.length} lượt <button id="restart">Chơi lại</button> <button id="saveSolution" ${game.result==='won'?'':'disabled'}>Lưu lời giải</button><div>${game.slots.map((s,i)=>s?`<span class="slot" style="border-color:${colors[colorIndex(s.color)]}">${i+1}. ${names[colorIndex(s.color)]} ${s.filled}/${s.capacity}</span>`:`<span class="slot" style="border-color:#ddd">${i+1}. Trống</span>`).join('')} Buffer ${game.buffer.length}/${level.buffer_capacity} ${game.buffer.map(c=>`<i class="dot" style="background:${colors[colorIndex(c)]}"></i>`).join('')}</div>`;$('restart').onclick=()=>{game=C.newGame(level);render();};$('saveSolution').onclick=()=>{level.solution=[...game.moves];persist();toast('Đã lưu thứ tự bấm vào solution');};}
function renderDrafts(){let drafts=[];try{drafts=JSON.parse(localStorage.getItem('cardslot-drafts-v1')||'[]');}catch{}$('drafts').innerHTML=drafts.map((d,i)=>`<button data-draft="${i}">◷ ${esc(d.id)} · bản nháp</button>`).join('');$('drafts').querySelectorAll('[data-draft]').forEach(el=>el.onclick=()=>{if(!game)load(drafts[+el.dataset.draft]);});}
$('palette').innerHTML=colors.map((c,i)=>`<button style="background:${c}" title="Thêm cọc ${names[i]}" data-add="${i}">${i} · ${names[i]}</button>`).join('');$('palette').onclick=e=>{const b=e.target.closest('[data-add]');if(b)addStack(+b.dataset.add);};
$('presets').onclick=e=>{const b=e.target.closest('[data-preset]');if(b&&!game)load(CARDSLOT_PRESETS[+b.dataset.preset]);};
$('layers').onclick=e=>{const b=e.target.closest('[data-select]');if(b&&!game){selected=b.dataset.select;render();}};
$('layers').onchange=e=>{const n=+e.target.dataset.layer;if(e.target.checked)hiddenLayers.delete(n);else hiddenLayers.add(n);renderBoard();};$('allLayers').onclick=()=>{hiddenLayers.clear();render();};
['grid','regions','relations','packed'].forEach(id=>$(id).onchange=()=>renderBoard());$('fit').onclick=fit;
$('undo').onclick=()=>{if(undo.length&&!game){redo.push(C.clone(level));level=undo.pop();selected=null;persist();render();}};$('redo').onclick=()=>{if(redo.length&&!game){undo.push(C.clone(level));level=redo.pop();selected=null;persist();render();}};
$('new').onclick=()=>load({...C.clone(CARDSLOT_PRESETS[0]),id:'level_new',revision:1,solution:undefined});
$('balance').onclick=()=>change(()=>{const totals=Array(8).fill(0);level.stacks.forEach(s=>totals[colorIndex(s.color)]+=s.count);level.targets=[];totals.forEach((count,i)=>{while(count>0){let capacity=Math.min(36,count);if(count-capacity===1)capacity--;level.targets.push({color:'color_'+i,capacity});count-=capacity;}});});
$('addTarget').onclick=()=>change(()=>level.targets.push({color:'color_0',capacity:6}));
$('save').onclick=()=>{try{const drafts=JSON.parse(localStorage.getItem('cardslot-drafts-v1')||'[]'),i=drafts.findIndex(d=>d.id===level.id);if(i<0)drafts.push(C.clone(level));else drafts[i]=C.clone(level);localStorage.setItem('cardslot-drafts-v1',JSON.stringify(drafts));renderDrafts();toast('Đã lưu bản nháp trên trình duyệt');}catch{toast('Không lưu được: hãy xuất JSON để giữ bản này');}};
$('play').onclick=()=>{if(game){game=null;render();return;}const errors=C.validate(level);if(errors.length){toast('Sửa các lỗi config trước khi bấm thử');return;}hiddenLayers.clear();game=C.newGame(level);render();};
$('json').onclick=()=>{$('jsonText').value=JSON.stringify(level,null,2);$('jsonError').textContent='';$('jsonDialog').showModal();};$('closeJson').onclick=()=>$('jsonDialog').close();
function parse(text){const l=C.normalize(JSON.parse(text));if(l.stacks.length>100||l.stacks.some(s=>!Number.isInteger(s.count)||s.count<1||s.count>48||!['x','y','w','h','layer'].every(k=>Number.isFinite(s[k]))))throw Error('Dữ liệu cọc hoặc số bài không hợp lệ.');return l;}
$('applyJson').onclick=()=>{try{const l=parse($('jsonText').value);load(l);$('jsonDialog').close();toast('Đã nhập JSON; xem kết quả kiểm tra bên phải');}catch(e){$('jsonError').textContent=e.message;}};
$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{try{const f=e.target.files[0];if(f)load(parse(await f.text()));}catch(e){toast('Không nhập được: '+e.message);}finally{$('file').value='';}};
$('export').onclick=()=>{const errors=C.validate(level);if(errors.length){toast('Chưa xuất được: hãy sửa '+errors.length+' lỗi config');return;}const url=URL.createObjectURL(new Blob([JSON.stringify(level,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=level.id.replace(/[^a-zA-Z0-9_-]/g,'_')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Đã xuất JSON CardSlot');};
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT/.test(e.target.tagName)||$('jsonDialog').open)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();$(e.shiftKey?'redo':'undo').click();}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y'){e.preventDefault();$('redo').click();}else if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='d'){e.preventDefault();duplicate();}else if(e.key==='Delete')remove();else if(e.key.toLowerCase()==='f')fit();});
try{const saved=localStorage.getItem('cardslot-working-v1');if(saved)level=parse(saved);}catch{}
render();requestAnimationFrame(fit);new ResizeObserver(()=>{updateView();}).observe($('canvas'));


