# GENERATED by PrototypeFramework 0.4.2 from Documentation~/agent/tools/_typecheck_lib.py — do not edit here. Change it in the framework repo, then run Framework/Agent Docs/Sync (editor) or Tools/Build/pf-build.sh agentdocs.
"""
Shared helper for Tools/pf/typecheck.sh + typecheck-headless.sh.

Transforms Unity's auto-generated <Asm>.csproj into an SDK-style csproj that
`dotnet build` can compile without opening the Unity Editor. Fast type-check
gate for AI-driven edits: `Library/pf-typecheck/<Asm>.csproj`, ~1 s cold,
~0.5 s incremental, errors greppable as `error CS####`.

Assumptions:
- Repo root passed via env or arg; `<repo>/<Asm>.csproj` exists (Unity generated it via `unity.rider`).
- Unity install at `Library/EditorInstance.json:app_contents_path`, so HintPaths in the Unity csproj are absolute.
- Cross-asmdef references satisfied from `Library/ScriptAssemblies/<Asm>.dll`
  (present because Unity has compiled the project at least once).
"""

from __future__ import annotations
import json
import pathlib
import re
import sys
import xml.etree.ElementTree as ET

# BCL names supplied by SDK's implicit netstandard2.1 reference — do NOT copy
# these from Unity's csproj (Unity has them at relative HintPaths that fail).
_BCL = {
    "mscorlib", "System", "System.Core", "System.Data", "System.Xml",
    "System.Xml.Linq", "System.Data.DataSetExtensions", "System.Numerics",
    "System.Runtime", "System.Runtime.Serialization", "Microsoft.CSharp",
    "netstandard",
}


def _strip_xmlns(xml_text: str) -> str:
    return re.sub(r'\sxmlns="[^"]+"', "", xml_text, count=1)


def parse_unity_csproj(csproj_path: pathlib.Path) -> dict:
    """Extract compile items, references (absolute HintPath only), project refs, defines."""
    root = ET.fromstring(_strip_xmlns(csproj_path.read_text()))

    compiles = [e.get("Include") for e in root.iter("Compile") if e.get("Include")]

    refs, ref_skips = [], []
    for r in root.iter("Reference"):
        name = r.get("Include")
        if not name:
            continue
        hp = r.find("HintPath")
        hp_val = hp.text.strip() if hp is not None and hp.text else None
        if name in _BCL:
            ref_skips.append((name, "bcl"))
            continue
        if not hp_val:
            ref_skips.append((name, "no-hintpath"))
            continue
        p = pathlib.Path(hp_val)
        if not p.is_absolute() or not p.is_file():
            ref_skips.append((name, f"not-resolvable:{hp_val}"))
            continue
        refs.append((name, str(p)))

    project_refs = []
    for pr in root.iter("ProjectReference"):
        inc = pr.get("Include")
        if inc:
            # Strip .csproj → assembly name.
            project_refs.append(pathlib.Path(inc).stem)

    defines = ""
    for pg in root.iter("PropertyGroup"):
        dc = pg.find("DefineConstants")
        if dc is not None and dc.text and not defines:
            defines = dc.text.strip()

    return {
        "compiles": compiles,
        "refs": refs,
        "project_refs": project_refs,
        "defines": defines,
        "ref_skips": ref_skips,
    }


def render_sdk_csproj(
    parsed: dict,
    repo: pathlib.Path,
    script_assemblies: pathlib.Path,
    *,
    drop_unity_refs: bool = False,
) -> str:
    """Render an SDK-style csproj that dotnet build can compile.

    drop_unity_refs=True → truly engine-free build (no UnityEngine.* refs). Fails
    fast for asmdefs that touch Unity APIs — that's the point in headless mode.
    """
    refs = parsed["refs"]
    if drop_unity_refs:
        refs = [(n, hp) for n, hp in refs if not n.startswith("UnityEngine") and not n.startswith("UnityEditor")]

    lines = [
        '<Project Sdk="Microsoft.NET.Sdk">',
        '  <PropertyGroup>',
        '    <TargetFramework>netstandard2.1</TargetFramework>',
        '    <LangVersion>latest</LangVersion>',
        '    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>',
        '    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>',
        '    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>',
        '    <NoStdLib>false</NoStdLib>',
        '    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>',
        '    <NoWarn>0169;0649;CS8032;CS1701;CS1702;NU1701</NoWarn>',
        f'    <DefineConstants>{parsed["defines"]}</DefineConstants>',
        '  </PropertyGroup>',
        '  <ItemGroup>',
    ]
    for name, hp in refs:
        lines.append(f'    <Reference Include="{name}"><HintPath>{hp}</HintPath><Private>false</Private></Reference>')
    # Project deps → prebuilt DLLs from Library/ScriptAssemblies (must be present).
    missing_pr = []
    for pr in parsed["project_refs"]:
        dll = script_assemblies / f"{pr}.dll"
        if dll.is_file():
            lines.append(
                f'    <Reference Include="{pr}"><HintPath>{dll}</HintPath><Private>false</Private></Reference>'
            )
        else:
            missing_pr.append(pr)
    lines.append('  </ItemGroup>')
    lines.append('  <ItemGroup>')
    for c in parsed["compiles"]:
        p = c if pathlib.Path(c).is_absolute() else str(repo / c)
        lines.append(f'    <Compile Include="{p}" />')
    lines.append('  </ItemGroup>')
    lines.append('</Project>')

    if missing_pr:
        # Emit a comment so callers can see it without failing the build outright.
        lines.insert(0, f"<!-- WARN missing prebuilt project refs: {', '.join(missing_pr)} -->")
    return "\n".join(lines) + "\n"


def resolve_repo_root(start: pathlib.Path | None = None) -> pathlib.Path:
    p = (start or pathlib.Path.cwd()).resolve()
    while p != p.parent:
        if (p / "ProjectSettings" / "ProjectVersion.txt").is_file():
            return p
        p = p.parent
    print("ERROR: could not find Unity project root (ProjectSettings/ProjectVersion.txt)", file=sys.stderr)
    sys.exit(2)


def out_csproj_for(repo: pathlib.Path, asm: str) -> pathlib.Path:
    d = repo / "Library" / "pf-typecheck"
    d.mkdir(parents=True, exist_ok=True)
    return d / f"{asm}.csproj"


def prepare_csproj(repo: pathlib.Path, asm: str, *, headless: bool = False) -> pathlib.Path:
    src = repo / f"{asm}.csproj"
    if not src.is_file():
        print(f"ERROR: {src.name} not found in repo root. Open the project in Unity once to generate it.", file=sys.stderr)
        sys.exit(2)
    parsed = parse_unity_csproj(src)
    script_assemblies = repo / "Library" / "ScriptAssemblies"
    text = render_sdk_csproj(parsed, repo, script_assemblies, drop_unity_refs=headless)
    out = out_csproj_for(repo, asm)
    out.write_text(text)
    return out


def cli_main():
    import argparse
    ap = argparse.ArgumentParser(description="Transform Unity csproj → SDK csproj for `dotnet build`.")
    ap.add_argument("asm", help="Assembly name (e.g. Game.Domain), without .csproj suffix.")
    ap.add_argument("--headless", action="store_true", help="Drop UnityEngine/UnityEditor refs (engine-free gate).")
    ap.add_argument("--repo", default=None, help="Project root (autodetected if omitted).")
    args = ap.parse_args()
    repo = pathlib.Path(args.repo).resolve() if args.repo else resolve_repo_root()
    out = prepare_csproj(repo, args.asm, headless=args.headless)
    print(out)


if __name__ == "__main__":
    cli_main()
