#!/usr/bin/env python3
# GENERATED by PrototypeFramework 0.4.2 from Documentation~/agent/tools/asset-gen.py — do not edit here. Change it in the framework repo, then run Framework/Agent Docs/Sync (editor) or Tools/Build/pf-build.sh agentdocs.
"""asset-gen — generate or edit a raster SOURCE asset with Codex's built-in image_gen.

The implementer's door to illustrated art that no design package supplies, and to edits of a plate
that code can only fake (painting an object out, a clean background). It is the sibling of
`Tools/pf/visual-judge.sh`: the same `codex exec`, headless, read-only, with the model pinned. When
to reach for it, and when code is the right tool instead: the `pf-asset-gen` skill.

    python3 Tools/pf/asset-gen.py run    <request.json> [--variants N] [--dry-run]
    python3 Tools/pf/asset-gen.py select <request.json> <variant>

The tool is synced from the framework. The DATA is the SKU's own, under `Tools/AssetGen/`
(`ASSETGEN_ROOT`), exactly as `Tools/UiGate/` is to the judge: `requests/<id>.json` (reviewable),
the selected PNGs wherever a request's `out` points (conventionally `assets/`), and `candidates/`
(scratch, git-ignored by the tool itself).

`run` writes candidates to `<ASSETGEN_ROOT>/candidates/<id>/v<n>.png` plus one `.json` of facts each.
`select` promotes one candidate to the request's `out` path and writes `<out>.gen.json` (provenance).
Only the selected PNG and its provenance are committed.

What a generation is NOT:
  * deterministic. The same prompt gives different art every time, so a selected PNG is committed
    SOURCE and nothing ever regenerates it in CI. Downstream code (crop, 9-slice, PPU 1) stays
    deterministic and reads the committed file.
  * size-controlled. A generate call returns 1254x1254 whatever size the prompt asks for. An edit
    keeps the target's size. Normalise in the consuming Editor generator, never here.
  * a finished decision. A selected asset carries `status: pending-user-review` until a person
    approves it, like a pending-user-review mockup.

Why the wrapper copies the file itself: given write access, the model post-processed its own output
(a silent `sips` resize). The call runs `-s read-only`, and the image is taken from
`$CODEX_HOME/generated_images/<thread_id>/`. `--json` names the thread but emits no image event.

Exit codes (CliConventions): 0 ok · 1 drift (a variant broke a `preserve` region) · 2 error.

Request (`schema: asset-gen-request/v1`), repo-relative paths:
    id          one path segment, names the candidates folder
    mode        "generate" | "edit"
    target      edit only: the image being edited, attached as Image 1
    references  [{"path": ..., "role": "style" | "composition" | ...}], attached after the target
    prompt      what to make or change. Name the images by their attachment number
    out         where `select` writes the chosen PNG
    preserve    edit only, optional: [[x, y, w, h], ...] regions that must come back unchanged,
                checked as mean |diff| against the target (`preserve_tolerance`, default 8 of 255)
    consumer    the file that reads `out` (documentation; `select` records it)

Environment: ASSETGEN_ROOT (default `Tools/AssetGen`, resolved from this script's location, not the
cwd), CODEX_BIN (default ~/.local/bin/codex, bypassing shell shims, else `codex` on PATH),
ASSETGEN_MODEL (default gpt-6-astra), ASSETGEN_EFFORT (default low), ASSETGEN_TIMEOUT_S (default 600).
Needs network: run it unsandboxed.
"""

import argparse
import concurrent.futures
import datetime
import hashlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
DATA = Path(os.environ.get("ASSETGEN_ROOT", HERE.parent / "AssetGen")).resolve()
CANDIDATES = DATA / "candidates"
CODEX_HOME = Path(os.environ.get("CODEX_HOME", Path.home() / ".codex"))

EXIT_OK, EXIT_DRIFT, EXIT_ERROR = 0, 1, 2

HEADER = (
    "Call the built-in image_gen tool exactly ONCE for the request below, then reply with the single "
    "word DONE.\n"
    "Do not run any shell command, do not copy, resize, convert or post-process any file, and do not "
    "call image_gen a second time.\n"
)


def die(msg):
    print(f"[asset-gen] ERROR: {msg}", file=sys.stderr)
    sys.exit(EXIT_ERROR)


def sha256(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def codex_bin():
    explicit = os.environ.get("CODEX_BIN")
    if explicit:
        return explicit
    local = Path.home() / ".local" / "bin" / "codex"
    return str(local) if local.exists() else "codex"


def load_request(path):
    req_path = Path(path)
    if not req_path.is_file():
        die(f"request not found: {path}")
    req = json.loads(req_path.read_text())
    if req.get("schema") != "asset-gen-request/v1":
        die(f"{path}: schema must be asset-gen-request/v1")
    for key in ("id", "mode", "prompt", "out"):
        if not req.get(key):
            die(f"{path}: missing '{key}'")
    if "/" in req["id"]:
        die(f"{path}: id must be one path segment")
    if req["mode"] not in ("generate", "edit"):
        die(f"{path}: mode must be generate or edit")
    if req["mode"] == "edit" and not req.get("target"):
        die(f"{path}: an edit needs a target")
    for p in [req.get("target")] + [r["path"] for r in req.get("references", [])]:
        if p and not (ROOT / p).is_file():
            die(f"{path}: image not found: {p}")
    req["_path"] = str(req_path)
    return req


def images(req):
    """(repo-relative path, legend) in attachment order: target first, then references."""
    out = []
    if req["mode"] == "edit":
        out.append((req["target"], "EDIT TARGET"))
    for r in req.get("references", []):
        out.append((r["path"], f"REFERENCE ({r.get('role', 'style')} only)"))
    return out


def prompt_text(req):
    legend = "\n".join(
        f"- Image {i} — {label} — `{p}`" for i, (p, label) in enumerate(images(req), 1))
    mode = ("Edit mode: edit Image 1 and keep its size and framing."
            if req["mode"] == "edit" else "Generate mode: create a new image.")
    return f"{HEADER}\n## Attached images\n{legend or '- none'}\n\n{mode}\n\n{req['prompt'].strip()}\n"


def argv(req):
    args = [codex_bin(), "exec", "--json", "-s", "read-only", "--skip-git-repo-check",
            "--ignore-user-config", "--ephemeral",
            "-m", os.environ.get("ASSETGEN_MODEL", "gpt-6-astra"),
            "-c", f'model_reasoning_effort="{os.environ.get("ASSETGEN_EFFORT", "low")}"']
    attached = [str(ROOT / p) for p, _ in images(req)]
    if attached:
        args += ["-i", *attached]
    return args + ["-"]  # -i is variadic: the prompt goes on stdin


def image_facts(path):
    from PIL import Image
    with Image.open(path) as im:
        facts = {"size": list(im.size), "mode": im.mode}
        if "A" in im.getbands():
            alpha = im.getchannel("A")
            facts["alpha_minmax"] = list(alpha.getextrema())
            box = alpha.point(lambda v: 255 if v >= 32 else 0).getbbox()
            facts["visible_bounds_alpha32"] = list(box) if box else None
    return facts


def preserve_check(req, candidate):
    """Mean |diff| (0-255) per preserve region against the edit target; None when not applicable."""
    regions = req.get("preserve") or []
    if req["mode"] != "edit" or not regions:
        return None
    from PIL import Image, ImageChops, ImageStat
    tol = float(req.get("preserve_tolerance", 8))
    with Image.open(ROOT / req["target"]) as t, Image.open(candidate) as c:
        t, c = t.convert("RGB"), c.convert("RGB")
        if t.size != c.size:
            return {"ok": False, "reason": f"size {list(c.size)} != target {list(t.size)}", "regions": []}
        rows = []
        for x, y, w, h in regions:
            box = (x, y, x + w, y + h)
            diff = ImageStat.Stat(ImageChops.difference(t.crop(box), c.crop(box)).convert("L")).mean[0]
            rows.append({"region": [x, y, w, h], "mean_abs_diff": round(diff, 2), "ok": diff <= tol})
    return {"ok": all(r["ok"] for r in rows), "tolerance": tol, "regions": rows}


def run_variant(req, n, text, folder):
    t0 = time.time()
    log = folder / f"v{n}.jsonl"
    timeout = int(os.environ.get("ASSETGEN_TIMEOUT_S", "600"))
    try:
        # Run outside the repo: its AGENTS.md and .codex/ hooks are for coding agents, not for this call.
        with open(log, "w") as fh, tempfile.TemporaryDirectory(prefix="asset-gen-") as cwd:
            proc = subprocess.run(argv(req), input=text, text=True, stdout=fh, stderr=subprocess.STDOUT,
                                  cwd=cwd, timeout=timeout)
        rc = proc.returncode
    except subprocess.TimeoutExpired:
        rc = "timeout"
    thread, shell = None, []
    for line in log.read_text().splitlines():
        if not line.startswith("{"):
            continue
        event = json.loads(line)
        thread = thread or event.get("thread_id")
        item = event.get("item") or {}
        if item.get("type") == "command_execution":
            shell.append(item.get("command"))
    made = sorted((CODEX_HOME / "generated_images" / thread).glob("*.png")) if thread else []
    record = {"variant": n, "rc": rc, "wall_s": round(time.time() - t0, 1), "thread_id": thread,
              "generations": len(made), "shell_commands": shell}
    if made:
        dst = folder / f"v{n}.png"
        shutil.copyfile(made[-1], dst)  # the tool's own bytes: never a model-side copy
        record.update(source=str(made[-1]), sha256=sha256(dst), facts=image_facts(dst),
                      preserve=preserve_check(req, dst))
    (folder / f"v{n}.json").write_text(json.dumps(record, indent=1) + "\n")
    return record


def cmd_run(args):
    req = load_request(args.request)
    text = prompt_text(req)
    if args.dry_run:
        print(" ".join(argv(req)) + " < prompt")
        print(text)
        return EXIT_OK
    folder = CANDIDATES / req["id"]
    folder.mkdir(parents=True, exist_ok=True)
    ignore = CANDIDATES / ".gitignore"
    if not ignore.exists():
        ignore.write_text("# asset-gen scratch: only a selected PNG and its .gen.json are committed.\n*\n")
    (folder / "prompt.txt").write_text(text)
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.variants) as pool:
        records = list(pool.map(lambda n: run_variant(req, n, text, folder), range(1, args.variants + 1)))
    code = EXIT_OK
    for r in records:
        pres = r.get("preserve")
        verdict = ("NO IMAGE" if not r["generations"] else
                   "PRESERVE-DRIFT" if pres and not pres["ok"] else "ok")
        extra = f" size={r['facts']['size']}" if r.get("facts") else ""
        if pres:
            extra += " preserve=" + ",".join(str(x["mean_abs_diff"]) for x in pres["regions"])
        if r["generations"] > 1 or r["shell_commands"]:
            extra += f" WARNING generations={r['generations']} shell={len(r['shell_commands'])}"
        print(f"[asset-gen] {req['id']} v{r['variant']}: {verdict} rc={r['rc']} {r['wall_s']}s{extra}")
        if verdict == "PRESERVE-DRIFT":
            code = max(code, EXIT_DRIFT)
    if not any(r["generations"] for r in records):
        print("[asset-gen] no variant produced an image", file=sys.stderr)
        return EXIT_ERROR
    print(f"[asset-gen] candidates: {os.path.relpath(folder, ROOT)}/ — inspect, then: "
          f"python3 Tools/pf/asset-gen.py select {args.request} <n>")
    return code


def cmd_select(args):
    req = load_request(args.request)
    folder = CANDIDATES / req["id"]
    src, facts_path = folder / f"v{args.variant}.png", folder / f"v{args.variant}.json"
    if not src.is_file():
        die(f"no candidate {os.path.relpath(src, ROOT)}")
    record = json.loads(facts_path.read_text())
    out = ROOT / req["out"]
    out.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, out)
    provenance = {
        "schema": "asset-gen-provenance/v1",
        "id": req["id"],
        "status": "pending-user-review",
        "mode": req["mode"],
        "request": os.path.relpath(req["_path"], ROOT),
        "consumer": req.get("consumer"),
        "tool": "codex exec built-in image_gen",
        "model": os.environ.get("ASSETGEN_MODEL", "gpt-6-astra"),
        "prompt": (folder / "prompt.txt").read_text(),
        "inputs": [{"path": p, "role": label, "sha256": sha256(ROOT / p)} for p, label in images(req)],
        "output": {"path": req["out"], "sha256": sha256(out), **record.get("facts", {})},
        "preserve": record.get("preserve"),
        "variant": args.variant,
        "selected_at": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }
    Path(str(out) + ".gen.json").write_text(json.dumps(provenance, indent=1) + "\n")
    print(f"[asset-gen] selected v{args.variant} -> {req['out']} (+ .gen.json, status pending-user-review)")
    return EXIT_OK


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("run")
    r.add_argument("request")
    r.add_argument("--variants", type=int, default=2)
    r.add_argument("--dry-run", action="store_true")
    s = sub.add_parser("select")
    s.add_argument("request")
    s.add_argument("variant", type=int)
    args = ap.parse_args()
    if getattr(args, "variants", 1) < 1:
        die("--variants must be >= 1")
    return cmd_run(args) if args.cmd == "run" else cmd_select(args)


if __name__ == "__main__":
    sys.exit(main())
