#!/usr/bin/env sh
# GENERATED by PrototypeFramework 0.4.2 from Documentation~/agent/tools/gate.sh — do not edit here. Change it in the framework repo, then run Framework/Agent Docs/Sync (editor) or Tools/Build/pf-build.sh agentdocs.
# =============================================================================
# gate.sh — a SKU's rung-1 gate, in one invocation.
#
# Synced from the framework (Documentation~/agent/tools/). What is the SKU's own lives in ONE file,
# Tools/Gate/gate.conf.sh (PF_GATE_CONF overrides), sourced before any leg runs:
#
#   TEST_PROJECT        required — the engine-free test project, repo-relative
#   KEYED_TEST          optional — ONE Slow test the gate still owns, run by name only when the
#                       content hash of its inputs changed (see leg 4); the config then also sets
#                       KEYED_TEST_LABEL, KEYED_TEST_TITLE, KEYED_TEST_STAMP, KEYED_TEST_ENV and
#                       defines keyed_test_inputs(), which prints one input path per line
#                       (framework_root, below, is available to it)
#
# A SKU's own source greps go in Tools/Gate/greps.local.sh, which Tools/pf/greps.sh sources.
#
# Four legs, in order, each reporting pass/fail:
#
#   1. greps        Tools/pf/greps.sh          — the source greps rule #9 and
#                                                friends have no other enforcement for.
#   2. typecheck    Tools/pf/typecheck-headless.sh
#                                              — Game.Domain / Game.Application /
#                                                Game.Gen compile with NO Unity
#                                                reference. Engine-freedom, proved.
#   3. test         dotnet test $TEST_PROJECT --filter "$DEFAULT_TEST_FILTER"
#                                              — the engine-free suite, minus the
#                                                Slow set, with its ELAPSED SECONDS
#                                                and its SLOWEST classes and tests
#                                                printed.
#   4. keyed        the ONE Slow test the gate still owns (KEYED_TEST), by name and opted
#                                              in. It runs only when a content hash of its
#                                                inputs differs from its last green run, and says
#                                                REUSED (never PASS) when not. No KEYED_TEST: SKIP.
#
# The elapsed time is REPORTED, never asserted: the 5-second bar is CI's to
# enforce, and a wall-time assertion inside a unit test is a flake generator.
#
# No Unity. No batchmode. No EditMode/PlayMode test. Runs from a tree with no
# Library/, bin/ or obj/ — with the one caveat named at the typecheck leg below.
#
#   Exit codes: 0 all legs pass · 1 a leg failed · 2 usage/error.
#
# THE RUN IS KEPT. Every leg's raw output is written to Logs/gate/gate-last.log
# (gitignored) as well as to the console, and a red run prints the distilled
# failure blocks at the very end. Two reasons, both measured on this project:
#
#   * A reader who pipes this through `| tail -40` THROWS THE REST AWAY, and the
#     only way back to a cut line used to be a second 97-second run of the same
#     suite over the same tree. Story 7.1 paid that twice (~200s). Grep the log
#     instead — `grep -nE "Error Message" -A4 Logs/gate/gate-last.log` costs
#     0.05s and tells you exactly what the re-run would have.
#   * At a 250k-token context one extra agent turn costs ~$0.40, far more than
#     the seconds it saves, so the failure summary is printed by THIS run: the
#     first read should already be enough, and the log is the rare fallback.
#
# Usage:
#   sh Tools/pf/gate.sh              run all four legs
#   sh Tools/pf/gate.sh --help       this text
# =============================================================================

set -u

TAG="[gate]"

# The filter the test leg runs under — the framework's convention, not a SKU setting: a SKU tags
# its sweeps, soaks and fuzzes `Slow` (AGENTS.framework.md §8a). A SKU test may PARSE this line —
# it stays at column 0, in this exact `DEFAULT_TEST_FILTER="…"` form.
DEFAULT_TEST_FILTER="TestCategory!=Slow"

usage() {
    sed -n '/^# Usage:/,/this text/p' "$0" | sed 's/^# \{0,1\}//'
    exit 2
}

case "${1:-}" in
    "") ;;
    -h|--help|help) usage ;;
    *) echo "$TAG ERROR: unexpected argument '$1'." >&2; usage ;;
esac

ROOT=$(cd "$(dirname "$0")/../.." && pwd)
cd "$ROOT" || { echo "$TAG ERROR: cannot cd to '$ROOT'." >&2; exit 2; }

# framework_root — the resolved package root (dev-link, embedded, then PackageCache), for a
# KEYED_TEST whose inputs include framework source.
framework_root() {
    fw=$(sed -n 's/.*"com\.classicspins\.prototype-framework" *: *"file:\([^"]*\)".*/\1/p' \
        "$ROOT/Packages/manifest.json" 2>/dev/null | head -1)
    if [ -n "$fw" ]; then
        case "$fw" in /*) ;; *) fw="$ROOT/Packages/$fw" ;; esac
    elif [ -d "$ROOT/Packages/com.classicspins.prototype-framework" ]; then
        fw="$ROOT/Packages/com.classicspins.prototype-framework"
    else
        fw=$(ls -dt "$ROOT"/Library/PackageCache/com.classicspins.prototype-framework@* 2>/dev/null | head -1)
    fi
    printf '%s' "$fw"
}

# --- The SKU's settings. ------------------------------------------------------------------------
GATE_CONF="${PF_GATE_CONF:-$ROOT/Tools/Gate/gate.conf.sh}"
if [ ! -f "$GATE_CONF" ]; then
    echo "$TAG ERROR: no SKU gate settings at ${GATE_CONF#"$ROOT/"}." >&2
    echo "$TAG       Write it: TEST_PROJECT=\"<YourSku>Tests/<YourSku>.Tests.csproj\" is the one required line." >&2
    exit 2
fi
TEST_PROJECT=""
KEYED_TEST=""
# shellcheck source=/dev/null
. "$GATE_CONF"
[ -n "$TEST_PROJECT" ] || { echo "$TAG ERROR: ${GATE_CONF#"$ROOT/"} sets no TEST_PROJECT." >&2; exit 2; }

# --- The kept run. ------------------------------------------------------------------------------
# One file, truncated per run, holding every leg's output verbatim. Logs/ is gitignored.
GATE_LOG_DIR="$ROOT/Logs/gate"
GATE_LOG="$GATE_LOG_DIR/gate-last.log"
mkdir -p "$GATE_LOG_DIR" || { echo "$TAG ERROR: cannot create '$GATE_LOG_DIR'." >&2; exit 2; }
: > "$GATE_LOG" || { echo "$TAG ERROR: cannot write '$GATE_LOG'." >&2; exit 2; }

rc_tmp=$(mktemp -t gate-rc-XXXX)
trap 'rm -f "$rc_tmp"' EXIT HUP INT TERM

# say / say_err — a gate line, to the console AND to the kept log.
say()     { echo "$TAG $*";      echo "$TAG $*" >> "$GATE_LOG"; }
say_err() { echo "$TAG $*" >&2;  echo "$TAG $*" >> "$GATE_LOG"; }

# run_leg CMD… — stream the command's output live, append it to the kept log, return ITS exit
# code (not tee's: POSIX sh has no PIPESTATUS, so the status rides through $rc_tmp).
run_leg() {
    { "$@" 2>&1; echo $? > "$rc_tmp"; } | tee -a "$GATE_LOG"
    leg_rc=$(cat "$rc_tmp" 2>/dev/null)
    [ -n "$leg_rc" ] || leg_rc=1
    return "$leg_rc"
}

rc=0
gate_start=$(date +%s)

# --- Leg 1: source greps. -----------------------------------------------------------------------
say "=== leg 1/4: source greps ==="
if run_leg sh "$ROOT/Tools/pf/greps.sh"; then
    say "PASS  greps"
else
    greps_rc=$?
    say_err "FAIL  greps (exit $greps_rc)"
    [ "$greps_rc" -eq 2 ] && exit 2
    rc=1
fi

# --- Leg 2: headless type-check. ----------------------------------------------------------------
# typecheck-headless.sh needs the Unity-generated Game.*.csproj at the repo root and prints
# `SKIP  <asm>` when one is missing. A SKIP is NOT a pass — it is the gate silently not running —
# so this leg treats it as a failure and names the remedy. (Those csproj files are gitignored, so a
# clone on which Unity has never been opened hits this. That is the one thing about this gate that
# a clean clone cannot satisfy, and it fails loudly rather than green.)
#
# Invoked with `bash`, NOT `sh`: typecheck-headless.sh is `#!/usr/bin/env bash` and uses bash arrays
# and ${BASH_SOURCE[0]}. On a host where /bin/sh is dash, `sh` on it dies on the array syntax and
# this leg misreports a shell incompatibility as a typecheck failure.
#
# Buffered rather than streamed because the SKIP grep below must read the whole leg; the buffer is
# echoed to the console and appended to the kept log the moment the leg ends.
say "=== leg 2/4: headless type-check (Game.Domain, Game.Application, Game.Gen) ==="
tc_log=$(mktemp -t gate-typecheck-XXXX)
if bash "$ROOT/Tools/pf/typecheck-headless.sh" > "$tc_log" 2>&1; then
    cat "$tc_log"; cat "$tc_log" >> "$GATE_LOG"
    if grep -q '^SKIP' "$tc_log"; then
        say_err "FAIL  typecheck: an assembly was SKIPped — its Game.*.csproj is missing."
        say_err "      Open the project in Unity once to generate the csproj files, then re-run."
        rc=1
    else
        say "PASS  typecheck"
    fi
else
    cat "$tc_log"; cat "$tc_log" >> "$GATE_LOG"
    say_err "FAIL  typecheck"
    rc=1
fi
rm -f "$tc_log"

# --- Leg 3: the engine-free test suite. ---------------------------------------------------------
say "=== leg 3/4: dotnet test $TEST_PROJECT --filter \"$DEFAULT_TEST_FILTER\" ==="
if [ ! -f "$ROOT/$TEST_PROJECT" ]; then
    say_err "ERROR: test project not found at $ROOT/$TEST_PROJECT."
    exit 2
fi

# The slowest classes and tests of this leg, from its own trx — REPORTED, never asserted, like the
# elapsed time. A suite does not get slow all at once: it gets slow one fixture at a time, and the
# first 0.6 s test nobody sees is the one that ships in fifteen [TestCase] rows. Measured on a SKU:
# 70 of 1332 tests were 22 s of a 24 s leg — one class rebuilt the same generated level for each of
# its 15 cases (6.3 s), another spawned a shell per case (10.9 s). No python3 ⇒ no line, nothing else.
GATE_TRX="$GATE_LOG_DIR/gate-last.trx"
report_slowest() {
    command -v python3 >/dev/null 2>&1 || return 0
    [ -f "$GATE_TRX" ] || return 0
    python3 - "$GATE_TRX" <<'PY' 2>/dev/null | while IFS= read -r line; do say "$line"; done
import collections, sys, xml.etree.ElementTree as ET
ns = {"t": "http://microsoft.com/schemas/VisualStudio/TeamTest/2010"}
root = ET.parse(sys.argv[1]).getroot()
cls = {u.get("id"): u.find("t:TestMethod", ns).get("className").rsplit(".", 1)[-1]
       for u in root.findall(".//t:UnitTest", ns)}
def secs(d):
    h, m, s = (d or "0:0:0").split(":")
    return int(h) * 3600 + int(m) * 60 + float(s)
by, tests, total = collections.defaultdict(lambda: [0, 0.0]), [], 0.0
for r in root.findall(".//t:UnitTestResult", ns):
    d, c = secs(r.get("duration")), cls.get(r.get("testId"), "?")
    by[c][0] += 1; by[c][1] += d; total += d
    tests.append((d, c + "." + r.get("testName", "?")))
top = [f"{c} {s:.1f}s ({n})" for c, (n, s) in sorted(by.items(), key=lambda x: -x[1][1])[:3] if s >= 1.0]
slow = [f"{n[:90]} {d:.2f}s" for d, n in sorted(tests, reverse=True)[:3] if d >= 0.5]
if top:
    print(f"slowest classes (of {total:.0f}s in tests): " + " · ".join(top))
if slow:
    print("slowest tests: " + " · ".join(slow))
if top or slow:
    print("      a fixture built per case is the usual cause — build it once ([OneTimeSetUp] / a static Lazy<T>)")
PY
}

rm -f "$GATE_TRX"
test_start=$(date +%s)
if run_leg dotnet test "$ROOT/$TEST_PROJECT" --filter "$DEFAULT_TEST_FILTER" -nologo \
        --logger "trx;LogFileName=$GATE_TRX"; then
    test_elapsed=$(($(date +%s) - test_start))
    say "PASS  test  (${test_elapsed}s elapsed)"
else
    test_elapsed=$(($(date +%s) - test_start))
    say_err "FAIL  test  (${test_elapsed}s elapsed)"
    rc=1
fi
report_slowest

# --- Leg 4: the keyed Slow test. ---------------------------------------------------------------
# A Slow test whose answer can only change when one of its inputs does is run BY NAME (never the whole
# Slow set) whenever the content hash of those inputs differs from its last green run. Under-scoping
# the input list is the one way this goes quietly wrong, so a config should err wide. No hasher, or a
# hash error, means the test RUNS.
keyed_key() {
    command -v shasum >/dev/null 2>&1 || return 1
    keyed_test_inputs | LC_ALL=C sort | while IFS= read -r f; do
        if [ -f "$f" ]; then shasum -a 256 "$f"; else echo "missing $f"; fi
    done | shasum -a 256 | cut -d' ' -f1
}

det_state="skipped"
if [ -z "$KEYED_TEST" ]; then
    say "=== leg 4/4: keyed Slow test ==="
    say "SKIP  keyed: ${GATE_CONF#"$ROOT/"} names no KEYED_TEST"
else
    KEYED_TEST_LABEL="${KEYED_TEST_LABEL:-keyed}"
    KEYED_TEST_TITLE="${KEYED_TEST_TITLE:-$KEYED_TEST_LABEL}"
    KEYED_TEST_ENV="${KEYED_TEST_ENV:-PF_RUN_SLOW=1}"
    DETERMINISM_STAMP="$GATE_LOG_DIR/${KEYED_TEST_STAMP:-keyed}.stamp"

    say "=== leg 4/4: $KEYED_TEST_TITLE (by name, $KEYED_TEST_ENV, only when its inputs changed) ==="
    det_key=$(keyed_key 2>/dev/null || true)
    det_state="ran"
    if [ -n "$det_key" ] && [ -f "$DETERMINISM_STAMP" ] && [ "$(cat "$DETERMINISM_STAMP")" = "$det_key" ]; then
        det_state="reused"
        say "REUSED  $KEYED_TEST_LABEL — NOT re-run: its inputs are byte-identical to its last green run"
        say "        ($(date -r "$DETERMINISM_STAMP" '+%Y-%m-%d %H:%M:%S'), key ${det_key%"${det_key#????????????}"}). Delete ${DETERMINISM_STAMP#"$ROOT/"} to force it."
    else
        [ -n "$det_key" ] || say "        (no input hash available — running it unconditionally)"
        det_from=$(($(wc -l < "$GATE_LOG") + 1))
        det_start=$(date +%s)
        # shellcheck disable=SC2086 — KEYED_TEST_ENV is NAME=value words, split on purpose
        if run_leg env $KEYED_TEST_ENV dotnet test "$ROOT/$TEST_PROJECT" \
                --filter "FullyQualifiedName~$KEYED_TEST" -nologo; then
            det_elapsed=$(($(date +%s) - det_start))
            # A green line is not enough: without the opt-in the test reports Skipped, and a filter
            # that matched nothing reports nothing. Require exactly one executed pass.
            if tail -n +"$det_from" "$GATE_LOG" | grep -Eq 'Passed:[[:space:]]+1,.*Skipped:[[:space:]]+0'; then
                say "PASS  $KEYED_TEST_LABEL  (${det_elapsed}s elapsed)"
                [ -n "$det_key" ] && printf '%s' "$det_key" > "$DETERMINISM_STAMP"
            else
                say_err "FAIL  $KEYED_TEST_LABEL: the run did not execute exactly one test (skipped or unmatched)."
                rm -f "$DETERMINISM_STAMP"
                rc=1
            fi
        else
            say_err "FAIL  $KEYED_TEST_LABEL  ($(($(date +%s) - det_start))s elapsed)"
            rm -f "$DETERMINISM_STAMP"
            rc=1
        fi
    fi
fi

# --- Verdict. -----------------------------------------------------------------------------------
gate_elapsed=$(($(date +%s) - gate_start))
if [ "$rc" -eq 0 ]; then
    say "ALL LEGS PASS  (gate ${gate_elapsed}s, test leg ${test_elapsed}s, ${KEYED_TEST_LABEL:-keyed} ${det_state})"
else
    say_err "GATE FAILED — see the failing leg above (gate ${gate_elapsed}s)"

    # The distilled failure blocks, printed LAST so a `| tail -N` reader lands on them rather than
    # on the passing tail of a suite. Each `Failed <test>` carries its Error Message and Stack
    # Trace; compiler errors are printed on their own line. Capped, because the whole run is in the
    # log anyway — read that when the cap bites, do NOT re-run the gate.
    echo "$TAG --- failure detail ---"
    awk '
        /^[[:space:]]*Failed /        { n = 12; print; next }
        n > 0                         { print; n--; next }
        /error CS[0-9]/               { print; next }
        /^\[gate\] FAIL/              { print; next }
    ' "$GATE_LOG" | head -60
fi

echo "$TAG full log: ${GATE_LOG#"$ROOT/"}  — grep it for anything cut above; never re-run to see more."
exit $rc
