#!/usr/bin/env sh
# GENERATED by PrototypeFramework 0.4.2 from Documentation~/agent/tools/greps.sh — do not edit here. Change it in the framework repo, then run Framework/Agent Docs/Sync (editor) or Tools/Build/pf-build.sh agentdocs.
# =============================================================================
# greps.sh — a SKU's source-grep enforcement surface.
#
# Synced from the framework (Documentation~/agent/tools/), and run by leg 1 of
# Tools/pf/gate.sh. The framework's own Tools/CI/greps.sh polices the framework
# tree; this one polices a SKU's code with the same technique. It carries the
# framework rules every SKU shares; a SKU's OWN greps live in
# Tools/Gate/greps.local.sh, which this script sources (PF_GREPS_LOCAL
# overrides) — the local file defines grep_* functions with the helpers below
# and lists them in SKU_GREPS, run after the shared three.
#
# A handful of architecture rules have no editor-free enforcement but a grep over
# the source tree. This script is that surface, versioned and locally runnable,
# and it NAMES every offending file:line so a red run is directly actionable.
#
# Three shared source greps, all scoped to Assets/<sku> — `sku` from the repo's
# framework.config.json, or PF_SKU_DIR (the SKU's own code; the framework is
# dev-linked and is not this repo's to police):
#
#   1. input-poll   — no Input.GetTouch / OnMouse* / Touchscreen.current in a
#                     Views asmdef (rule #9). Sole exception: a line that routes
#                     through IBackButtonRouter.
#   2. lifecycle    — no OnApplicationPause/Focus/Quit anywhere in the SKU; the
#                     kernel owns the engine lifecycle and forwards it.
#   3. messagepipe  — no RegisterMessageBroker<T> / RegisterMessagePipe() outside
#                     an Installers/ directory.
#
# SELF-TRIP GUARD — the reason this is not a naive `grep -rn`. The banned strings
# appear verbatim in rule text, in the tests that assert the ban, and in ordinary
# source comments. Every grep therefore:
#   (a) strips line comments before matching — for BOTH the ban and the allowance,
#       so a trailing `// IBackButtonRouter` cannot whitelist a real violation,
#   (b) excludes test assemblies (**/Tests/** and *Tests.cs) by the path RELATIVE
#       to the scanned root, never the absolute one — a checkout living under a
#       `/Tests/` path would otherwise exclude every file and report three clean
#       greps,
#   (c) scopes to the exact source root the rule governs.
# AGENTS.md, docs/ and SkuHeadlessTests/ sit outside Assets/ and are never scanned.
#
#   Exit codes: 0 clean · 1 violations found · 2 usage/error.
#
# Usage:
#   Tools/pf/greps.sh                 run the source greps over the SKU
#   Tools/pf/greps.sh --root <path>   run them over a throwaway fixture tree
# =============================================================================

set -eu

TAG="[sku-grep]"

# The repo this script lives in — NOT --root: a fixture tree borrows its SKU's name and its local
# greps, so a self-test over a throwaway tree exercises exactly the greps the real one runs.
SCRIPT_REPO=$(cd "$(dirname "$0")/../.." && pwd)
if [ -n "${PF_SKU_DIR:-}" ]; then
    SKU_DIR="$PF_SKU_DIR"
else
    _sku=$(sed -n 's/.*"sku"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' "$SCRIPT_REPO/framework.config.json" 2>/dev/null | head -1)
    if [ -z "$_sku" ]; then
        echo "$TAG ERROR: no \"sku\" in $SCRIPT_REPO/framework.config.json and no PF_SKU_DIR." >&2
        exit 2
    fi
    SKU_DIR="Assets/$_sku"
fi
GREPS_LOCAL="${PF_GREPS_LOCAL:-$SCRIPT_REPO/Tools/Gate/greps.local.sh}"
SKU_GREPS=""
if [ -f "$GREPS_LOCAL" ]; then
    # shellcheck source=/dev/null
    . "$GREPS_LOCAL"
fi

usage() {
    sed -n '/^# Usage:/,/fixture tree/p' "$0" | sed 's/^# \{0,1\}//'
    exit 2
}

# --- Repo-root discovery: the same two sentinels the framework's CI scripts use. ---------------
find_repo_root() {
    _explicit=""
    _prev=""
    for _a in "$@"; do
        if [ "$_prev" = "--root" ]; then _explicit="$_a"; break; fi
        _prev="$_a"
    done
    # `--root` as the LAST argument leaves _explicit empty. Falling through to discovery would scan
    # the REAL repo while the caller believes it named a fixture tree — the one failure mode this
    # flag exists to prevent. Name it and exit 2, as the usage contract above promises.
    if [ -z "$_explicit" ] && [ "$_prev" = "--root" ]; then
        echo "$TAG ERROR: --root requires a path (usage: Tools/pf/greps.sh --root <path>)." >&2
        exit 2
    fi
    if [ -n "$_explicit" ]; then
        if [ -f "$_explicit/AGENTS.md" ] && [ -f "$_explicit/Packages/manifest.json" ]; then
            ( cd "$_explicit" && pwd )
            return 0
        fi
        echo "$TAG ERROR: --root '$_explicit' is not a repo root (needs AGENTS.md + Packages/manifest.json)." >&2
        exit 2
    fi
    _dir=$(cd "$(dirname "$0")/../.." && pwd)
    while [ -n "$_dir" ]; do
        if [ -f "$_dir/AGENTS.md" ] && [ -f "$_dir/Packages/manifest.json" ]; then
            echo "$_dir"
            return 0
        fi
        [ "$_dir" = "/" ] && break
        _dir=$(dirname "$_dir")
    done
    echo "$TAG ERROR: could not locate repo root (a dir with AGENTS.md + Packages/manifest.json). Pass --root <path>." >&2
    exit 2
}

# --- The file list. -----------------------------------------------------------------------------
# ONE rooted find, selecting by -path rather than collecting directories into a variable and
# re-expanding it. That earlier shape word-split on the space in this checkout's own directory name
# and walked a SIBLING repo's Library/PackageCache — a grep that reports violations from outside the
# project is worse than no grep.
#
# Paths come back RELATIVE to $ROOT, which is what makes the test exclusion below correct: the
# checkout's own directory names are not part of what is matched.
list_sources() {
    ( cd "$ROOT" && find "$SKU_DIR" -type f -name '*.cs' "$@" 2>/dev/null )
}

# Matches a ROOT-RELATIVE path. See guard (b) in the header.
exclude_tests() {
    grep -v -e '/Tests/' -e 'Tests\.cs$' || true
}

# --- The core scanner. --------------------------------------------------------------------------
# Emits `file:line:content` for every line matching PATTERN after line-comment stripping, skipping
# any line that also matches ALLOW (empty ALLOW = no exception). Root-relative file list on stdin.
# Returns 0 when clean, 1 when it found something.
scan_files() {
    _pattern="$1"; _allow="$2"
    _hits=0
    while IFS= read -r _f; do
        [ -f "$ROOT/$_f" ] || continue
        _out=$(awk -v pat="$_pattern" -v allow="$_allow" '
            {
                stripped = $0
                sub(/\/\/.*/, "", stripped)     # drop line comments (/// and inline //)
                if (stripped ~ pat) {
                    # The allowance is matched against the STRIPPED line, exactly like the ban.
                    # Matching the raw line let a trailing `// IBackButtonRouter` whitelist any
                    # real rule-9 violation.
                    if (allow != "" && stripped ~ allow) next
                    printf "%d:%s\n", FNR, $0
                }
            }
        ' "$ROOT/$_f")
        if [ -n "$_out" ]; then
            echo "$_out" | while IFS= read -r _line; do
                echo "$TAG   VIOLATION $_f:$_line"
            done
            _hits=1
        fi
    done
    [ "$_hits" -eq 0 ]
}

# --- Grep 1: input polling in a Views asmdef (rule #9). -----------------------------------------
# Scope: every `Views` directory under the SKU — the Game.Views anchor folder and any feature's
# Views/ subfolder. Bans Input.GetTouch, the six exact Unity mouse messages (word-boundaried, NOT a
# bare `OnMouse` substring) and Touchscreen.current. Allowed: a line that goes through
# IBackButtonRouter, the sole codebase-wide poll exception.
grep_input_poll() {
    _p='Input[.]GetTouch|(^|[^[:alnum:]_])OnMouse(Down|Up|Enter|Exit|Over|Drag)([^[:alnum:]_]|$)|Touchscreen[.]current'
    _list=$(list_sources -path '*/Views/*' | exclude_tests)
    if [ -z "$_list" ]; then
        echo "$TAG input-poll: no Views sources (nothing to scan)"
        return 0
    fi
    if printf '%s\n' "$_list" | scan_files "$_p" 'IBackButtonRouter'; then
        echo "$TAG PASS  input-poll (no Input.GetTouch / OnMouse* / Touchscreen.current in a Views asmdef)"
        return 0
    fi
    echo "$TAG FAIL  input-poll: banned input polling in a Views asmdef (rule #9; sole exception IBackButtonRouter)"
    return 1
}

# --- Grep 2: engine lifecycle hooks in SKU code. ------------------------------------------------
# The kernel owns OnApplicationPause/Focus/Quit and forwards them; a SKU MonoBehaviour that
# implements one competes with it. There is no legal home for these in this repo, so there is no
# allowed file — only the test exclusion and comment-stripping.
grep_lifecycle() {
    _p='(^|[^[:alnum:]_])OnApplication(Pause|Focus|Quit)([^[:alnum:]_]|$)'
    _list=$(list_sources | exclude_tests)
    if [ -z "$_list" ]; then
        echo "$TAG lifecycle: no candidate sources"
        return 0
    fi
    if printf '%s\n' "$_list" | scan_files "$_p" ''; then
        echo "$TAG PASS  lifecycle (no OnApplicationPause/Focus/Quit in SKU code)"
        return 0
    fi
    echo "$TAG FAIL  lifecycle: engine lifecycle hook in SKU code — the kernel owns it and forwards it"
    return 1
}

# --- Grep 3: MessagePipe registration outside Installers/. --------------------------------------
grep_messagepipe() {
    _p='RegisterMessageBroker|RegisterMessagePipe'
    _list=$(list_sources | { grep -v -e '/Installers/' || true; } | exclude_tests)
    if [ -z "$_list" ]; then
        echo "$TAG messagepipe: no candidate sources"
        return 0
    fi
    if printf '%s\n' "$_list" | scan_files "$_p" ''; then
        echo "$TAG PASS  messagepipe (no MessagePipe registration outside Installers/)"
        return 0
    fi
    echo "$TAG FAIL  messagepipe: MessagePipe registration outside an Installers/ directory"
    return 1
}

# --- Dispatch. ----------------------------------------------------------------------------------
case "${1:-source}" in
    -h|--help|help)
        usage
        ;;
    source|--root)
        ROOT=$(find_repo_root "$@")
        if [ ! -d "$ROOT/$SKU_DIR" ]; then
            echo "$TAG ERROR: '$ROOT/$SKU_DIR' does not exist — wrong root?" >&2
            exit 2
        fi
        echo "$TAG root: $ROOT"
        _rc=0
        grep_input_poll         || _rc=1
        grep_lifecycle          || _rc=1
        grep_messagepipe        || _rc=1
        for _g in $SKU_GREPS; do
            "$_g" || _rc=1
        done
        if [ "$_rc" -eq 0 ]; then
            echo "$TAG ALL SOURCE GREPS CLEAN"
        else
            echo "$TAG SOURCE GREP VIOLATIONS FOUND — see file:line above" >&2
        fi
        exit $_rc
        ;;
    *)
        echo "$TAG ERROR: unknown subcommand '$1' (expected: source | --root <path>)." >&2
        usage
        ;;
esac
