#!/usr/bin/env python3
# GENERATED by PrototypeFramework 0.4.2 from Documentation~/agent/tools/judge-calibrate.py — do not edit here. Change it in the framework repo, then run Framework/Agent Docs/Sync (editor) or Tools/Build/pf-build.sh agentdocs.
"""Measure the vision judge before it is trusted to block a story.

    python3 Tools/pf/judge-calibrate.py                       # gameplay suite, 2 samples
    python3 Tools/pf/judge-calibrate.py --samples 3 --jobs 3
    python3 Tools/pf/judge-calibrate.py --dry-run             # build the cases, call nothing

pf-uigate: "The judge's catch rate is a number, not a belief ... Until that number exists, a VIOLATED
row is a finding for triage, not a unilateral block." This produces that number, with the model
identity that produced it, and writes it to `Tools/UiGate/judge-calibration.md` (the file the
framework docs point at) plus one line per calibration in `tuning/calibration-history.jsonl`.

A suite (`tuning/calibration/<surface>.json`) is a contract plus cases. Each case feeds the
contract's captures from known images — the approved mockup itself, a re-rendered copy, the real
pre-finish render, programmatic defects (flat background, greybox, blur) — and says what a correct
judge must answer:

  * positive — no scored row may come back VIOLATED        → false-positive rate
  * negative — every expected row must come back VIOLATED  → catch rate

Every case is judged `--samples` times with `--measure` (no cache, no HALT), so the report also
carries consistency: how often the judge gives the majority answer for the same input.

Re-run whenever judge.conf, visual-judge.sh's prompt, or the contract changes. Costs
cases × samples model calls (default 6 × 2 = 12, ~50 s each, run --jobs at a time).
"""

import argparse
import glob
import hashlib
import json
import os
import sys
import time
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import uigate_lib as L  # noqa: E402

TUNING = L.TUNING  # the SKU's data: tuning/calibration/<surface>.json and calibration-history.jsonl


def transform(src, dst, how):
    from PIL import Image, ImageFilter, ImageOps
    im = Image.open(src).convert("RGB")
    w, h = im.size
    if how == "jitter":
        import io
        from PIL import ImageEnhance
        im = ImageEnhance.Contrast(ImageEnhance.Brightness(im).enhance(1.04)).enhance(0.97)
        buf = io.BytesIO()
        im.save(buf, "JPEG", quality=75)
        im = Image.open(io.BytesIO(buf.getvalue())).convert("RGB")
    elif how == "greybox":
        im = ImageOps.posterize(ImageOps.grayscale(im), 3).convert("RGB")
    elif how == "blur":
        im = im.filter(ImageFilter.GaussianBlur(radius=max(w, h) / 190))
    elif how == "flat-bg":
        # Everything outside the shelf plate becomes the flat ground colour. The shelf plate and the
        # HUD band are kept, in the design's 1080×1920 frame scaled to this image.
        sx, sy = w / 1080, h / 1920
        ground = (227, 196, 156)
        flat = Image.new("RGB", (w, h), ground)
        keep = [(0, 0, 1080, 200), (18, 540, 1062, 1400)]
        for x0, y0, x1, y1 in keep:
            box = (int(x0 * sx), int(y0 * sy), int(x1 * sx), int(y1 * sy))
            flat.paste(im.crop(box), box[:2])
        im = flat
    elif how != "none":
        raise SystemExit(f"unknown transform '{how}'")
    im.save(dst, "PNG")


def build_case(suite, case, section, block, workdir):
    """Write the case's captures and a contract whose capture lines point at them."""
    os.makedirs(workdir, exist_ok=True)
    caps = []
    for i, (src, (_, label)) in enumerate(zip(case["captures"], block["captures"])):
        path = src[5:] if src.startswith("@ref:") else src
        path = L.resolve(block, path, src.startswith("@ref:"))
        dst = os.path.join(workdir, f"capture-{i + 1}.png")
        transform(path, dst, case.get("transform", "none"))
        caps.append((os.path.relpath(dst, L.ROOT), label))
    lines, ci = [], 0
    for line in section.splitlines():
        if line.strip().startswith("capture:"):
            if ci < len(caps):
                lines.append(f"capture: {caps[ci][0]} | {caps[ci][1]}")
            ci += 1
            continue
        lines.append(line)
    spec = os.path.join(workdir, "contract.md")
    with open(spec, "w", encoding="utf-8") as f:
        f.write(f"# calibration case {case['id']}\n\n" + "\n".join(lines) + "\n")
    return spec


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--suite", default=None,
                    help="tuning/calibration/<surface>.json (default: the only suite there is)")
    ap.add_argument("--samples", type=int, default=2)
    ap.add_argument("--jobs", type=int, default=3)
    ap.add_argument("--cases", help="comma-separated case ids (default: all)")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--no-write", action="store_true", help="print the report, do not write judge-calibration.md")
    a = ap.parse_args()
    if not a.suite:
        suites = sorted(glob.glob(os.path.join(TUNING, "calibration", "*.json")))
        if len(suites) != 1:
            sys.exit(f"[calibrate] ERROR: {len(suites)} suites under {os.path.relpath(os.path.join(TUNING, 'calibration'), L.ROOT)}/ — name one with --suite")
        a.suite = suites[0]

    suite = json.load(open(a.suite))
    contract = os.path.join(L.ROOT, suite["contract"])
    section = L.contract_section(contract)
    block = L.contract_block(section)
    rows = L.contract_rows(section)
    cases = [c for c in suite["cases"] if not a.cases or c["id"] in a.cases.split(",")]
    started = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    work = os.path.join(L.ARCHIVE, "_calibration", suite["suite"])
    jobs = []
    for c in cases:
        spec = build_case(suite, c, section, block, os.path.join(work, c["id"]))
        surface = f"calib-{suite['suite']}-{c['id']}"
        for s in range(a.samples):
            jobs.append((c, spec, f"{surface}-s{s + 1}", s))
    print(f"[calibrate] {len(cases)} cases × {a.samples} samples = {len(jobs)} judge calls "
          f"(contract {suite['contract']}, {len(rows)} rows)")

    if a.dry_run:
        for c in cases:
            rc, _, out = 0, None, ""
            p = L.subprocess.run(["sh", L.JUDGE, "--spec", os.path.join(work, c["id"], "contract.md"),
                                  "--dry-run"], cwd=L.ROOT, capture_output=True, text=True)
            first = [l for l in p.stdout.splitlines() if "model=" in l or "surface=" in l]
            print(f"  {c['id']:28s} exit {p.returncode}  {' | '.join(first)[:150]}")
        return 0

    def one(job):
        c, spec, surface, s = job
        t0 = time.time()
        rc, rec, tail = L.run_judge(spec, surface, "calibrate", measure=True)
        return c["id"], s, rc, rec, tail, time.time() - t0

    results = {}
    with ThreadPoolExecutor(max_workers=max(1, a.jobs)) as ex:
        for cid, s, rc, rec, tail, dt in ex.map(one, jobs):
            print(f"  {cid:28s} sample {s + 1}  exit {rc}  {dt:5.0f}s")
            if rc not in (0, 1) or rec is None:
                print("    judge did not run:\n    " + tail.replace("\n", "\n    ")[-800:])
            results.setdefault(cid, []).append(rec)

    # --- score -----------------------------------------------------------------------------------
    model = next((r.get("model") for rs in results.values() for r in rs if r), "unknown")
    effort = next((r.get("effort") for rs in results.values() for r in rs if r), "unknown")
    fp_num = fp_den = catch_num = catch_den = 0
    agree_all, secs, toks, ct_pos = [], [], [], 0
    lines = []
    for c in cases:
        recs = [r for r in results.get(c["id"], []) if r]
        samples = [r["verdicts"] for r in recs]
        secs += [r["duration-s"] for r in recs]
        toks += [r["tokens"] for r in recs]
        maj, agree = L.majority(samples, sorted(rows))
        agree_all += list(agree.values())
        if not recs:
            lines.append(f"| {c['id']} | {c['kind']} | — | judge did not run |")
            continue
        if c["kind"] == "positive":
            scored = c.get("scored_rows") or L.scored_rows(rows)
            bad = [n for s in samples for n in scored if s.get(n, ("",))[0] == "VIOLATED"]
            fp_num += len(bad)
            fp_den += len(scored) * len(samples)
            ct_pos += sum(1 for s in samples for n in scored if s.get(n, ("",))[0] == "CANNOT-TELL")
            worst = sorted({n for n in bad})
            res = "clean" if not bad else "VIOLATED " + ", ".join(f"V{n}" for n in worst)
            lines.append(f"| {c['id']} | positive | {len(bad)}/{len(scored) * len(samples)} false VIOLATED | {res} |")
        else:
            exp = c["expect_violated"]
            hit = [n for s in samples for n in exp if s.get(n, ("",))[0] == "VIOLATED"]
            catch_num += len(hit)
            catch_den += len(exp) * len(samples)
            missed = sorted({n for n in exp if maj.get(n) != "VIOLATED"})
            extra = sorted(n for n, v in maj.items() if v == "VIOLATED" and n not in exp)
            res = "all caught" if not missed else "missed " + ", ".join(f"V{n}" for n in missed)
            if extra:
                res += "; also VIOLATED " + ", ".join(f"V{n}" for n in extra)
            lines.append(f"| {c['id']} | negative | {len(hit)}/{len(exp) * len(samples)} caught | {res} |")

    fp = fp_num / fp_den if fp_den else None
    catch = catch_num / catch_den if catch_den else None
    cons = sum(agree_all) / len(agree_all) if agree_all else None
    judge_sha = hashlib.sha256(open(L.JUDGE, "rb").read()).hexdigest()[:12]
    contract_sha = hashlib.sha256(section.encode()).hexdigest()[:12]
    pct = lambda v: "n/a" if v is None else f"{100 * v:.0f}%"
    gate = ("may block" if (catch is not None and fp is not None and catch >= 0.8 and fp <= 0.05
                            and (cons or 0) >= 0.85) else "findings for triage only")

    report = f"""# Judge calibration — {suite['suite']}

Generated by `Tools/pf/judge-calibrate.py` on {started}. Do not hand-edit; re-run it.

| | |
|---|---|
| model | `{model}` (effort `{effort}`) |
| judge script | `Tools/pf/visual-judge.sh` sha256 {judge_sha}… |
| contract | `{suite['contract']}` sha256 {contract_sha}… |
| samples per case | {a.samples} |
| **catch rate** (negatives: expected rows VIOLATED) | **{pct(catch)}** ({catch_num}/{catch_den}) |
| **false-positive rate** (positives: scored rows VIOLATED) | **{pct(fp)}** ({fp_num}/{fp_den}) |
| CANNOT-TELL on positives | {ct_pos}/{fp_den} |
| **consistency** (same input, majority answer) | **{pct(cons)}** |
| median call | {sorted(secs)[len(secs) // 2] if secs else 0} s, {sorted(toks)[len(toks) // 2] if toks else 0} tokens |
| verdict status | **{gate}** — the bar is catch ≥ 80 %, false positives ≤ 5 %, consistency ≥ 85 % |

| case | kind | score | result |
|---|---|---|---|
""" + "\n".join(lines) + f"""

## Known limits

- The positives are the approved mockup, not a Unity render: they bound false positives on the design
  itself, not on every legitimate production difference (DIVERGENCES.md covers those in the prompt).
- The programmatic defects are coarse. A defect this suite does not model — a missing contact shadow,
  a badge detached from its row — has no measured catch rate; add a case when a real one is found.
- Records: `Tools/UiGate/captures/calib-{suite['suite']}-<case>-s<N>/` (git-ignored).

## Earlier finding kept from the framework docs

The Game View's render texture once read back a uniform `RGBA(0.098, 0.098, 0.122, 1)` across the
whole frame; judged, every row came back VIOLATED for the wrong reason. The judge's broken-capture
check (exit 2) exists because of it.
"""
    print("\n" + report)
    entry = dict(when=started, suite=suite["suite"], model=model, effort=effort, samples=a.samples,
                 judge_sha=judge_sha, contract_sha=contract_sha, catch=catch, false_positive=fp,
                 consistency=cons, gate=gate,
                 cases={c["id"]: [r["file"] if r else None for r in results.get(c["id"], [])] for c in cases})
    if not a.no_write:
        with open(os.path.join(L.UIGATE, "judge-calibration.md"), "w", encoding="utf-8") as f:
            f.write(report)
        with open(os.path.join(TUNING, "calibration-history.jsonl"), "a", encoding="utf-8") as f:
            f.write(json.dumps(entry) + "\n")
        print("[calibrate] wrote Tools/UiGate/judge-calibration.md and tuning/calibration-history.jsonl")
    return 0


if __name__ == "__main__":
    sys.exit(main())
