#!/usr/bin/env python3
# GENERATED by PrototypeFramework 0.4.2 from Documentation~/agent/tools/model-gen-blender.py — do not edit here. Change it in the framework repo, then run Framework/Agent Docs/Sync (editor) or Tools/Build/pf-build.sh agentdocs.
"""model-gen-blender — the Blender half of `Tools/pf/model-gen.py`. Never run it by hand.

model-gen.py starts Blender headless with this file as the startup script:

    Blender -b --factory-startup --python-exit-code 3 -P Tools/pf/model-gen-blender.py -- \
        --script <build.py> --spec <spec.json> --out <dir>

It empties the scene, runs the model script with an `mg` helper object in scope, measures what the
script built against the spec, exports `<dir>/model.fbx` for Unity, renders the blueprint's four
orthographic views plus a 3/4 hero view, and writes `<dir>/facts.json`. The tool does all of that,
never the model: the model only writes the script, and the script only builds geometry.

The FBX contract (what a Unity import can rely on): metres at import scale 1 (`FBX_SCALE_ALL` with
the unit scale applied), the model's front on Unity +Z and Y up, the axis change baked into the
meshes so no node arrives with a -90 degree X rotation, triangles exactly as Blender cut them, and
one material per palette key named `M_<key>`.

Exit codes: 0 facts.json was written (`facts.ok` says whether the model passed) · 2 the harness
itself failed. A script that raises is a fact (`script_error`), not a harness failure.
"""

import argparse
import json
import math
import sys
import traceback
from pathlib import Path

import bmesh
import bpy
from mathutils import Euler, Matrix, Vector

HARNESS_VERSION = 1
VIEWS = ("front", "right", "back", "top")

# The helper reference model-gen.py pastes into the author prompt. Keep it in step with class MG.
MG_API = r"""
`mg` is already in scope. Every builder returns the new bpy object. Common arguments:
  name     object name; give every object a meaningful one (Body, Cabin, Wheel_FL, Pivot_Brush)
  loc      (x, y, z) metres: the object's origin. Relative to `parent` when one is given
  rot      (x, y, z) Euler degrees, XYZ order
  color    a palette key, the face material. Omit it only on a part `mg.join` merges into a coloured one
  parent   an object (often an `mg.empty`) the new object hangs under
  bevel    edge bevel width in metres, baked into the mesh (0 = sharp); `segments` = its rounding steps

mg.color(key) -> bpy.types.Material
    The palette material `M_<key>`. An unknown key raises KeyError listing the palette.
mg.box(name, size, loc=(0,0,0), rot=(0,0,0), bevel=0.0, segments=2, color=None, parent=None)
    A box with full extents size=(sx, sy, sz), centred on its origin.
mg.cylinder(name, radius, depth, loc=(0,0,0), rot=(0,0,0), verts=16, radius2=None, bevel=0.0,
            segments=1, color=None, parent=None)
    Axis along local Z, centred on its origin. radius2 sets the +Z end's radius (0 = a cone).
    A wheel rolling along Y: rot=(0, 90, 0).
mg.sphere(name, radius, loc=(0,0,0), scale=(1,1,1), segments=12, rings=8, color=None, parent=None)
    A UV sphere; `scale` squashes it into an ellipsoid (heads, foam clumps, tree crowns).
mg.profile(name, points, depth, axis="X", loc=(0,0,0), rot=(0,0,0), bevel=0.0, segments=2,
           color=None, parent=None)
    A closed 2D outline extruded by `depth`, centred on its origin along `axis`:
      axis "X": points are (y, z) as the RIGHT view shows them (front = -y): car bodies, cabins
      axis "Y": points are (x, z) as the FRONT view shows them: arches, gantries, sign boards
      axis "Z": points are (x, y) as the TOP view shows them: floor plates, roofs
    The outline may be concave but must not cross itself. Its caps are triangulated for you.
mg.mesh(name, verts, faces, loc=(0,0,0), rot=(0,0,0), color=None, parent=None)
    Any polygon mesh: verts [(x, y, z)...], faces [(i, j, k, ...)...]. Normals are recalculated.
mg.empty(name, loc=(0,0,0), rot=(0,0,0), parent=None)
    A transform with no geometry: the pivot of a part that moves, or a group.
mg.mirror_x(obj, name) -> bpy.types.Object
    A copy of a mesh object mirrored across x = 0 in its parent's space: the left/right twin of a
    wheel, mirror or lamp. Its children are not copied.
mg.join(name, objs) -> bpy.types.Object
    Merge leaf mesh objects into one (materials kept) at the first one's origin and parent, so
    static detail is one draw. Never join a part that moves.
mg.smooth(obj, angle=30)
    Smooth shading, keeping edges sharper than `angle` degrees hard. The default is flat shading.

Coordinates: Blender axes, metres. The model's FRONT faces -Y, +Z is up, the ground is z = 0 (the
lowest point touches it), and the bounding box is centred on x = 0, y = 0.

Example (structure only, not a design):

    body = mg.profile("Body", [(-1.1, 0.25), (1.1, 0.25), (1.1, 0.75), (0.4, 0.8), (-0.9, 0.8),
                               (-1.1, 0.65)], depth=1.4, axis="X", bevel=0.06, color="body")
    glass = mg.box("Windshield", (1.2, 0.05, 0.4), loc=(0, -0.55, 1.0), rot=(-35, 0, 0), color="glass")
    wheel = mg.cylinder("Wheel_FL", 0.32, 0.22, loc=(0.6, -0.7, 0.32), rot=(0, 90, 0), verts=14,
                        bevel=0.03, color="tyre")
    mg.mirror_x(wheel, "Wheel_FR")
"""


def _linear(hex_rgb):
    """'E84E49' -> linear RGBA, the space Blender colour inputs take."""
    h = hex_rgb.lstrip("#")
    srgb = [int(h[i:i + 2], 16) / 255.0 for i in (0, 2, 4)]
    return tuple(c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4 for c in srgb) + (1.0,)


class MG:
    """The model script's builders. Geometry only: no file, render, export or scene-reset access."""

    def __init__(self, palette):
        self.palette = {k: v.lstrip("#").upper() for k, v in palette.items()}
        self.materials = {}
        self._collection = bpy.context.scene.collection

    def color(self, key):
        if key not in self.palette:
            raise KeyError(f"mg.color({key!r}): not a palette key; the palette is {sorted(self.palette)}")
        mat = self.materials.get(key)
        if mat is None:
            rgba = _linear(self.palette[key])
            mat = bpy.data.materials.new("M_" + key)
            mat.diffuse_color = rgba
            mat.roughness = 0.8
            bsdf = mat.node_tree.nodes.get("Principled BSDF") if mat.node_tree else None
            if bsdf is not None:
                bsdf.inputs["Base Color"].default_value = rgba
                bsdf.inputs["Roughness"].default_value = 0.8
            self.materials[key] = mat
        return mat

    def box(self, name, size, loc=(0, 0, 0), rot=(0, 0, 0), bevel=0.0, segments=2, color=None,
            parent=None):
        bm = bmesh.new()
        bmesh.ops.create_cube(bm, size=1.0)
        bmesh.ops.scale(bm, vec=Vector(size), verts=bm.verts)
        _bevel(bm, bevel, segments, min(size))
        return self._object(name, bm, loc, rot, color, parent)

    def cylinder(self, name, radius, depth, loc=(0, 0, 0), rot=(0, 0, 0), verts=16, radius2=None,
                 bevel=0.0, segments=1, color=None, parent=None):
        bm = bmesh.new()
        bmesh.ops.create_cone(bm, cap_ends=True, cap_tris=False, segments=max(3, int(verts)),
                              radius1=radius, radius2=radius if radius2 is None else radius2,
                              depth=depth)
        bmesh.ops.remove_doubles(bm, verts=bm.verts, dist=1e-6)  # a cone's tip collapses to one vertex
        _bevel(bm, bevel, segments, min(radius, depth / 2), hard_only=True)
        return self._object(name, bm, loc, rot, color, parent)

    def sphere(self, name, radius, loc=(0, 0, 0), scale=(1, 1, 1), segments=12, rings=8, color=None,
               parent=None):
        bm = bmesh.new()
        bmesh.ops.create_uvsphere(bm, u_segments=max(3, int(segments)), v_segments=max(2, int(rings)),
                                  radius=radius)
        bmesh.ops.scale(bm, vec=Vector(scale), verts=bm.verts)
        return self._object(name, bm, loc, (0, 0, 0), color, parent)

    def profile(self, name, points, depth, axis="X", loc=(0, 0, 0), rot=(0, 0, 0), bevel=0.0,
                segments=2, color=None, parent=None):
        if axis not in ("X", "Y", "Z"):
            raise ValueError(f"mg.profile({name!r}): axis must be 'X', 'Y' or 'Z', not {axis!r}")
        if len(points) < 3:
            raise ValueError(f"mg.profile({name!r}): an outline needs at least 3 points")

        def place(a, b, t):
            return (t, a, b) if axis == "X" else (a, t, b) if axis == "Y" else (a, b, t)

        bm = bmesh.new()
        near = [bm.verts.new(place(a, b, -depth / 2)) for a, b in points]
        far = [bm.verts.new(place(a, b, depth / 2)) for a, b in points]
        n = len(points)
        bm.faces.new(near)
        bm.faces.new(list(reversed(far)))
        for i in range(n):
            j = (i + 1) % n
            bm.faces.new((near[i], near[j], far[j], far[i]))
        bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
        span_a = max(p[0] for p in points) - min(p[0] for p in points)
        span_b = max(p[1] for p in points) - min(p[1] for p in points)
        _bevel(bm, bevel, segments, min(depth, span_a, span_b), hard_only=True)
        caps = [f for f in bm.faces if len(f.verts) > 4]
        if caps:
            bmesh.ops.triangulate(bm, faces=caps, quad_method="BEAUTY", ngon_method="EAR_CLIP")
        return self._object(name, bm, loc, rot, color, parent)

    def mesh(self, name, verts, faces, loc=(0, 0, 0), rot=(0, 0, 0), color=None, parent=None):
        bm = bmesh.new()
        vs = [bm.verts.new(v) for v in verts]
        for f in faces:
            bm.faces.new([vs[i] for i in f])
        bmesh.ops.recalc_face_normals(bm, faces=bm.faces)
        ngons = [f for f in bm.faces if len(f.verts) > 4]
        if ngons:
            bmesh.ops.triangulate(bm, faces=ngons, quad_method="BEAUTY", ngon_method="EAR_CLIP")
        return self._object(name, bm, loc, rot, color, parent)

    def empty(self, name, loc=(0, 0, 0), rot=(0, 0, 0), parent=None):
        obj = bpy.data.objects.new(name, None)
        obj.empty_display_size = 0.2
        self._collection.objects.link(obj)
        _place(obj, loc, rot, parent)
        return obj

    def mirror_x(self, obj, name):
        if obj.type != "MESH":
            raise TypeError(f"mg.mirror_x({obj.name!r}): only a mesh object can be mirrored")
        me = obj.data.copy()
        me.name = name
        bm = bmesh.new()
        bm.from_mesh(me)
        bmesh.ops.scale(bm, vec=Vector((-1, 1, 1)), verts=bm.verts)
        bmesh.ops.reverse_faces(bm, faces=bm.faces)
        bm.to_mesh(me)
        bm.free()
        twin = bpy.data.objects.new(name, me)
        self._collection.objects.link(twin)
        twin.parent = obj.parent
        twin.location = (-obj.location.x, obj.location.y, obj.location.z)
        e = obj.rotation_euler
        twin.rotation_euler = Euler((e.x, -e.y, -e.z), "XYZ")
        twin.scale = obj.scale
        return twin

    def join(self, name, objs):
        objs = [o for o in objs if o is not None]
        if not objs:
            raise ValueError(f"mg.join({name!r}): nothing to join")
        for o in objs:
            if o.type != "MESH":
                raise TypeError(f"mg.join({name!r}): {o.name!r} is not a mesh")
            if o.children:
                raise ValueError(f"mg.join({name!r}): {o.name!r} has children; join leaf objects only")
        bpy.context.view_layer.update()
        anchor = objs[0].matrix_world.copy()
        to_anchor = anchor.inverted()
        mats, bm = [], bmesh.new()
        for o in objs:
            tmp = o.data.copy()
            tmp.transform(to_anchor @ o.matrix_world)
            remap = []
            for slot_mat in tmp.materials:
                if slot_mat not in mats:
                    mats.append(slot_mat)
                remap.append(mats.index(slot_mat))
            start = len(bm.faces)
            bm.from_mesh(tmp)
            bm.faces.ensure_lookup_table()
            for f in bm.faces[start:]:
                f.material_index = remap[f.material_index] if remap else 0
            bpy.data.meshes.remove(tmp)
        me = bpy.data.meshes.new(name)
        bm.to_mesh(me)
        bm.free()
        for m in mats:
            me.materials.append(m)
        parent = objs[0].parent
        for o in objs:
            data = o.data
            bpy.data.objects.remove(o)
            if data.users == 0:
                bpy.data.meshes.remove(data)
        joined = bpy.data.objects.new(name, me)  # named after the removal, so it keeps `name` exactly
        self._collection.objects.link(joined)
        joined.parent = parent
        joined.matrix_world = anchor
        return joined

    def smooth(self, obj, angle=30):
        obj.data.shade_smooth()
        obj.data.set_sharp_from_angle(angle=math.radians(angle))
        return obj

    def _object(self, name, bm, loc, rot, color, parent):
        me = bpy.data.meshes.new(name)
        bm.to_mesh(me)
        bm.free()
        obj = bpy.data.objects.new(name, me)
        self._collection.objects.link(obj)
        if color is not None:
            me.materials.append(self.color(color))
        _place(obj, loc, rot, parent)
        return obj


def _bevel(bm, width, segments, extent, hard_only=False):
    if not width or width <= 0:
        return
    width = min(width, max(extent, 1e-4) * 0.45)
    edges = [e for e in bm.edges
             if not hard_only or (e.is_manifold and e.calc_face_angle(0.0) > math.radians(30))]
    if edges:
        bmesh.ops.bevel(bm, geom=list({v for e in edges for v in e.verts}) + edges, offset=width,
                        segments=max(1, int(segments)), affect="EDGES", profile=0.5, clamp_overlap=True)


def _place(obj, loc, rot, parent):
    if parent is not None:
        obj.parent = parent
    obj.location = Vector(loc)
    obj.rotation_euler = Euler([math.radians(a) for a in rot], "XYZ")


# ── measuring ──────────────────────────────────────────────────────────────────────────────────


def _check(facts, cid, ok, detail):
    facts["checks"].append({"id": cid, "ok": bool(ok), "detail": detail})


def measure(spec, mg, facts):
    """Every check the request makes of the model, as facts. Bounds are exact (vertex-level)."""
    scene = bpy.context.scene
    depsgraph = bpy.context.evaluated_depsgraph_get()
    meshes = [o for o in scene.objects if o.type == "MESH"]
    others = sorted(o.name for o in scene.objects if o.type not in ("MESH", "EMPTY"))
    facts["objects"], tris, unassigned, foreign, mirrored = [], 0, [], set(), []
    lo, hi = Vector((math.inf,) * 3), Vector((-math.inf,) * 3)
    palette_mats = set(mg.materials.values())
    for o in meshes:
        ev = o.evaluated_get(depsgraph)
        me = ev.to_mesh()
        me.calc_loop_triangles()
        n = len(me.loop_triangles)
        tris += n
        mw = ev.matrix_world
        for v in me.vertices:
            w = mw @ v.co
            lo = Vector(map(min, lo, w))
            hi = Vector(map(max, hi, w))
        used = {p.material_index for p in me.polygons}
        slots = [s.material for s in o.material_slots]
        if not slots or any(i >= len(slots) or slots[i] is None for i in used):
            unassigned.append(o.name)
        foreign.update(m.name for m in slots if m is not None and m not in palette_mats)
        if o.matrix_world.determinant() < 0:
            mirrored.append(o.name)
        ev.to_mesh_clear()
        facts["objects"].append({"name": o.name, "tris": n, "parent": o.parent.name if o.parent else None,
                                 "materials": [m.name for m in slots if m is not None]})
    facts["empties"] = sorted(o.name for o in scene.objects if o.type == "EMPTY")
    facts["tris"] = tris
    facts["materials"] = sorted(m.name for m in mg.materials.values())

    _check(facts, "meshes", meshes, f"{len(meshes)} mesh object(s)")
    if not meshes:
        return None
    size = {"width": hi.x - lo.x, "height": hi.z - lo.z, "length": hi.y - lo.y}
    centre = (lo + hi) / 2
    facts["size"] = {k: round(v, 4) for k, v in size.items()}
    facts["bounds"] = {"min": [round(c, 4) for c in lo], "max": [round(c, 4) for c in hi]}

    tol = float(spec.get("size_tolerance", 0.03))
    for axis, want in spec["size"].items():
        got = size[axis]
        allowed = max(tol * want, 0.005)
        _check(facts, f"size.{axis}", abs(got - want) <= allowed,
               f"{got:.3f} m, want {want:.3f} ± {allowed:.3f}")
    w, h, length = spec["size"]["width"], spec["size"]["height"], spec["size"]["length"]
    ground = max(0.01 * h, 0.005)
    _check(facts, "pivot.ground", abs(lo.z) <= ground,
           f"lowest point z = {lo.z:.3f}, want 0 ± {ground:.3f}")
    _check(facts, "pivot.centre", abs(centre.x) <= max(0.02 * w, 0.01) and abs(centre.y) <= max(0.02 * length, 0.01),
           f"bounding-box centre x = {centre.x:.3f}, y = {centre.y:.3f}, want 0, 0")
    _check(facts, "tris", tris <= int(spec["max_tris"]), f"{tris} triangles, budget {spec['max_tris']}")
    names = {o.name for o in scene.objects}
    missing = [p for p in spec.get("parts", []) if p not in names]
    _check(facts, "parts", not missing, "missing: " + ", ".join(missing) if missing else "all present")
    _check(facts, "materials", not unassigned and not foreign,
           "; ".join(filter(None, [
               "faces with no palette material on: " + ", ".join(unassigned) if unassigned else "",
               "materials not made by mg.color: " + ", ".join(sorted(foreign)) if foreign else ""]))
           or "every face carries an M_<key> palette material")
    _check(facts, "object_types", not others,
           "not exported (only meshes and empties are): " + ", ".join(others) if others else "meshes and empties only")
    _check(facts, "transforms", not mirrored,
           "negative scale (flipped normals in Unity): " + ", ".join(mirrored) if mirrored else "no negative scale")
    return lo, hi


# ── exporting and rendering ────────────────────────────────────────────────────────────────────


def export_fbx(path):
    bpy.ops.export_scene.fbx(
        filepath=str(path), use_selection=False, object_types={"EMPTY", "MESH"},
        apply_unit_scale=True, apply_scale_options="FBX_SCALE_ALL", axis_forward="-Z", axis_up="Y",
        bake_space_transform=True, use_mesh_modifiers=True, mesh_smooth_type="FACE",
        use_triangles=True, use_tspace=False, use_custom_props=False, add_leaf_bones=False,
        bake_anim=False, path_mode="AUTO", embed_textures=False)


def render(spec, facts, out, lo, hi):
    scene = bpy.context.scene
    scene.render.engine = "BLENDER_WORKBENCH"
    shading = scene.display.shading
    shading.light = "STUDIO"
    shading.studio_light = "paint.sl"  # keeps a palette hex within a few levels of itself; "Default" darkens it ~30%
    shading.color_type = "MATERIAL"
    shading.show_object_outline = True
    scene.display.render_aa = "8"
    scene.view_settings.view_transform = "Standard"
    scene.render.film_transparent = True
    scene.render.image_settings.file_format = "PNG"
    scene.render.image_settings.color_mode = "RGBA"

    centre = (lo + hi) / 2
    extent = hi - lo
    span = max(extent) * 1.25
    dist = 10 * span + 10
    cam_data = bpy.data.cameras.new("ModelGenCam")
    cam_data.type = "ORTHO"
    cam_data.clip_start = 0.01
    cam_data.clip_end = 3 * dist
    cam = bpy.data.objects.new("ModelGenCam", cam_data)
    scene.collection.objects.link(cam)
    scene.camera = cam

    def shoot(path, offset, px, scale, top=False):
        cam.location = centre + offset
        cam.rotation_euler = Euler((0, 0, 0)) if top else (-offset).to_track_quat("-Z", "Y").to_euler()
        cam_data.ortho_scale = scale
        scene.render.resolution_x = scene.render.resolution_y = px
        scene.render.filepath = str(path)
        bpy.ops.render.render(write_still=True)

    px = int(spec.get("view_px", 512))
    offsets = {"front": Vector((0, -dist, 0)), "right": Vector((dist, 0, 0)),
               "back": Vector((0, dist, 0)), "top": Vector((0, 0, dist))}
    facts["views"] = {}
    for view in VIEWS:
        shoot(out / f"view_{view}.png", offsets[view], px, span, top=(view == "top"))
        facts["views"][view] = f"view_{view}.png"

    hero = spec.get("hero", {})
    pitch, yaw = math.radians(hero.get("pitch", 30)), math.radians(hero.get("yaw", 35))
    look_from = Vector((math.sin(yaw) * math.cos(pitch), -math.cos(yaw) * math.cos(pitch), math.sin(pitch)))
    shoot(out / "hero.png", look_from * dist, int(spec.get("hero_px", 768)), extent.length * 1.1)
    facts["hero"] = "hero.png"
    bpy.data.objects.remove(cam)


# ── entry point ────────────────────────────────────────────────────────────────────────────────


def main():
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    ap = argparse.ArgumentParser(prog="model-gen-blender")
    ap.add_argument("--script", required=True)
    ap.add_argument("--spec", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--no-render", action="store_true")
    args = ap.parse_args(argv)
    out = Path(args.out)
    out.mkdir(parents=True, exist_ok=True)
    facts = {"harness": HARNESS_VERSION, "blender": bpy.app.version_string, "ok": False, "checks": []}
    try:
        spec = json.loads(Path(args.spec).read_text())
        bpy.ops.wm.read_factory_settings(use_empty=True)
        mg = MG(spec["palette"])
        source = Path(args.script).read_text()
        namespace = {"__name__": "__model__", "bpy": bpy, "bmesh": bmesh, "math": math, "mg": mg,
                     "Vector": Vector, "Matrix": Matrix, "Euler": Euler}
        try:
            exec(compile(source, "build.py", "exec"), namespace)
        except Exception as exc:  # the script's failure is a fact for the next round, not ours
            frames = [f for f in traceback.extract_tb(exc.__traceback__) if f.filename == "build.py"]
            where = f" (build.py line {frames[-1].lineno}: {frames[-1].line})" if frames else ""
            facts["script_error"] = f"{type(exc).__name__}: {exc}{where}"
        bpy.context.view_layer.update()
        bounds = measure(spec, mg, facts)
        if bounds and not facts.get("script_error"):
            export_fbx(out / "model.fbx")
            facts["fbx"] = "model.fbx"
        if bounds and not args.no_render:
            render(spec, facts, out, *bounds)
        facts["ok"] = not facts.get("script_error") and all(c["ok"] for c in facts["checks"])
    except Exception:
        facts["harness_error"] = traceback.format_exc()
        (out / "facts.json").write_text(json.dumps(facts, indent=1) + "\n")
        sys.exit(2)
    (out / "facts.json").write_text(json.dumps(facts, indent=1) + "\n")


if __name__ == "__main__":
    main()
