#!/usr/bin/env python3
# GENERATED by PrototypeFramework 0.4.2 from Documentation~/agent/tools/model-gen.py — do not edit here. Change it in the framework repo, then run Framework/Agent Docs/Sync (editor) or Tools/Build/pf-build.sh agentdocs.
# /// script
# requires-python = ">=3.9"
# dependencies = ["pillow"]
# ///
"""model-gen — a 3D model no design package supplies: an orthographic blueprint first, then a
Blender-built model authored against it.

The 3D sibling of `Tools/pf/asset-gen.py`, whose `codex exec` door it reuses. When to reach for it,
and what to do with the result: the `pf-model-gen` skill.

    python3 Tools/pf/model-gen.py blueprint        <request.json> [--variants N] [--dry-run]
    python3 Tools/pf/model-gen.py select-blueprint <request.json> <variant>
    python3 Tools/pf/model-gen.py build            <request.json> [--variants N] [--rounds N] [--dry-run]
    python3 Tools/pf/model-gen.py select           <request.json> <variant> [--round K] [--force]
    python3 Tools/pf/model-gen.py rebuild          <request.json>
    python3 Tools/pf/model-gen.py status           [<request.json>...] [--under DIR] [--md OUT]

  blueprint         Codex's built-in image_gen draws a 2x2 orthographic sheet (FRONT, RIGHT / BACK,
                    TOP) of the request's subject at its size and in its palette, once per variant.
                    Every variant is measured: four views, none crossing its cell, each view's
                    proportions against the requested size, one scale across the views.
  select-blueprint  Promote one variant to `<out>/blueprint.png` (+ `.gen.json`, status
                    pending-user-review). A person approving it is the model's design sign-off.
  build             Codex (read-only, no workspace) writes a Blender Python script against the selected
                    blueprint. The TOOL runs it in Blender headless (`model-gen-blender.py`), checks the
                    result (bounding box, pivot, triangle budget, palette materials, named parts),
                    exports FBX, renders the blueprint's four views and scores each silhouette against
                    the blueprint; the comparison goes back to Codex for the next round. One chain of
                    rounds per variant, chains in parallel.
  select            Promote a variant's best passing round to `<out>/`: build.py (the source),
                    `<id>.fbx`, views.png, hero.png, compare.png, model.gen.json (status
                    pending-user-review). --force takes a round that failed a check.
  rebuild           Re-run Blender on the committed `<out>/build.py`, after a hand edit or a harness
                    change. The script is deterministic, so the geometry is too; FBX bytes still differ
                    by the exporter's timestamp.
  status            One row per request: blueprint and model state, and whether the committed files
                    still match their provenance. --under keeps requests whose `out` is inside DIR;
                    --md writes the table (a design package's MODELS.md).

The DATA is the SKU's own, under `Tools/ModelGen/` (`MODELGEN_ROOT`), as `Tools/AssetGen/` is to
asset-gen: `requests/<id>.json` (reviewable), the selected files wherever a request's `out` points,
and `candidates/` (scratch, git-ignored by the tool itself).

What a generation is NOT:
  * deterministic. Neither the blueprint nor the script comes back the same twice, so the selected
    files are committed SOURCE and nothing regenerates them in CI. `rebuild` re-runs the committed
    script; it never asks a model again.
  * a finished decision. Both selections carry `status: pending-user-review` until a person
    approves them.
  * an import. Nothing is written under `Assets/`: importing the FBX (scale 1, materials remapped
    by their `M_<key>` names) is the consuming story's job.

Why the model only writes text: given write access, a model post-processes its own output without
saying so (asset-gen saw a silent `sips` resize). So Codex runs `-s read-only` from a temporary
directory outside the repo, its script comes back in its reply, and the tool screens it (imports,
builtins and bpy entry points outside geometry are refused) before Blender ever runs it.

Exit codes (CliConventions): 0 ok · 1 drift (no variant passed its checks; a committed file no longer
matches its provenance) · 2 error.

Request (`schema: model-gen-request/v1`), repo-relative paths:
    id           one path segment
    subject      what the model is, in a sentence or two: the blueprint prompt and the author brief
    size         {"width", "height", "length"} metres, the OVERALL bounding box (mirrors, bumpers and
                 wheels included). Unity axes: width = X, height = Y, length = Z (the front faces +Z)
    palette      {"key": "RRGGBB", ...}: the only colours; materials come out as M_<key>
    max_tris     the triangle budget, counted after bevels
    parts        optional [{"name", "note"}]: objects that must stay separate (they move) under exactly
                 these names, origin at their pivot
    references   optional [{"path", "role"}]: approved art the look follows (style only)
    notes        optional modelling guidance for both stages
    hero         optional {"pitch", "yaw"} degrees for the 3/4 render (default 30, 35)
    out          the directory `select-blueprint` and `select` write into
    consumer     optional: the story or file that imports the FBX (recorded)

Environment: MODELGEN_ROOT (default `Tools/ModelGen`, resolved from this script's location), BLENDER_BIN
(default: Blender.app on macOS, else `blender` on PATH), MODELGEN_MODEL (default: Codex's own),
MODELGEN_EFFORT (default medium), MODELGEN_TIMEOUT_S (default 900, per Codex call),
MODELGEN_BLENDER_TIMEOUT_S (default 300), MODELGEN_IOU_TARGET (default 0.88: a chain stops early once
every check passes at this mean silhouette match). The blueprint call is an asset-gen call: ASSETGEN_*
apply. Needs network: run it unsandboxed. A build takes minutes per round: run it in the background.
"""

import argparse
import ast
import concurrent.futures
import datetime
import importlib.util
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
import time
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
DATA = Path(os.environ.get("MODELGEN_ROOT", HERE.parent / "ModelGen")).resolve()
REQUESTS = DATA / "requests"
CANDIDATES = DATA / "candidates"
HARNESS = HERE / "model-gen-blender.py"

EXIT_OK, EXIT_DRIFT, EXIT_ERROR = 0, 1, 2
VIEWS = ("front", "right", "back", "top")  # the blueprint's cells, row by row
EXPECT = {"front": ("width", "height"), "right": ("length", "height"),
          "back": ("width", "height"), "top": ("width", "length")}
MASK_PX = 256
ASPECT_TOL = 0.15   # a blueprint view's proportions against the requested size
SCALE_TOL = 0.15    # the same extent measured in two views (a warning only)
ALLOWED_IMPORTS = {"bpy", "bmesh", "math", "mathutils"}
REFUSED_NAMES = {"open", "exec", "eval", "compile", "__import__", "globals", "locals", "vars",
                 "getattr", "setattr", "delattr", "input", "breakpoint", "exit", "quit", "help"}
REFUSED_CHAINS = ("bpy.ops", "bpy.app", "bpy.utils", "bpy.data.libraries", "bpy.data.texts", "bpy.data.images",
                  "bpy.data.materials", "bpy.context.preferences")


def _load_asset_gen():
    spec = importlib.util.spec_from_file_location("asset_gen", HERE / "asset-gen.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


ASSET_GEN = _load_asset_gen()


def die(msg):
    print(f"[model-gen] ERROR: {msg}", file=sys.stderr)
    sys.exit(EXIT_ERROR)


def say(msg):
    print(f"[model-gen] {msg}", flush=True)


def sha256(path):
    return ASSET_GEN.sha256(path)


def now():
    return datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def rel(path):
    """Repo-relative when inside the repo, else absolute."""
    try:
        r = os.path.relpath(path, ROOT)
    except ValueError:
        return str(path)
    return str(path) if r.startswith("..") else r


# ── the request ─────────────────────────────────────────────────────────────────────────────────


def load_request(path):
    req_path = Path(path)
    if not req_path.is_file():
        die(f"request not found: {path}")
    req = json.loads(req_path.read_text())
    if req.get("schema") != "model-gen-request/v1":
        die(f"{path}: schema must be model-gen-request/v1")
    for key in ("id", "subject", "size", "palette", "max_tris", "out"):
        if not req.get(key):
            die(f"{path}: missing '{key}'")
    if "/" in req["id"]:
        die(f"{path}: id must be one path segment")
    size = req["size"]
    if sorted(size) != ["height", "length", "width"] or not all(
            isinstance(v, (int, float)) and v > 0 for v in size.values()):
        die(f"{path}: size must be {{width, height, length}} in metres, all > 0")
    for key, value in req["palette"].items():
        if not re.fullmatch(r"#?[0-9A-Fa-f]{6}", str(value)) or not re.fullmatch(r"[A-Za-z][A-Za-z0-9_]*", key):
            die(f"{path}: palette entry {key!r}: {value!r} must be an identifier mapped to RRGGBB")
    if not isinstance(req["max_tris"], int) or req["max_tris"] <= 0:
        die(f"{path}: max_tris must be a positive integer")
    for part in req.get("parts", []):
        if not part.get("name"):
            die(f"{path}: every part needs a name")
    for r in req.get("references", []):
        if not (ROOT / r["path"]).is_file():
            die(f"{path}: image not found: {r['path']}")
    req["_path"] = str(req_path)
    return req


def out_dir(req):
    return ROOT / req["out"]


def palette_lines(req):
    return "\n".join(f"- `{k}` = #{v.lstrip('#').upper()}" for k, v in req["palette"].items())


def size_line(req):
    s = req["size"]
    return f"{s['width']:g} m wide × {s['height']:g} m tall × {s['length']:g} m long"


def parts_lines(req):
    return "\n".join(f"- `{p['name']}`: {p.get('note', 'separate object, origin at its pivot')}"
                     for p in req.get("parts", [])) or "- none required"


# ── stage 1: the blueprint ──────────────────────────────────────────────────────────────────────


def blueprint_prompt(req):
    s = req["size"]
    refs = ""
    if req.get("references"):
        refs = ("\nMatch the art style of the attached reference image(s) — rendering, proportions, "
                "colour treatment — for this one object only; do not copy their scene.\n")
    notes = f"\nNotes: {req['notes'].strip()}\n" if req.get("notes") else ""
    return f"""Draw an orthographic TURNAROUND SHEET (a modelling blueprint) of ONE 3D game model.

Subject: {req['subject'].strip()}
Overall size: {size_line(req)}.
{refs}{notes}
Layout — follow it exactly, a modeller measures this sheet:
- A 2x2 grid of four equal square cells on ONE plain, flat, pure white (#FFFFFF) background.
- Top-left cell: FRONT view (looking straight at the model's front).
- Top-right cell: RIGHT side view (looking at the model's right side; the model's FRONT points to the
  LEFT edge of the cell).
- Bottom-left cell: BACK view.
- Bottom-right cell: TOP view from directly above (the model's FRONT points DOWN, toward the bottom
  edge of the cell).
- Strict orthographic projection in every cell: no perspective, no foreshortening, no tilt, no
  3/4 angle. The same model at the SAME scale in all four cells, centred in its cell, filling about
  70% of it. Nothing crosses into another cell.
- Proportions from the size above: the FRONT and BACK views are {s['width']:g}:{s['height']:g}
  (wide:tall), the RIGHT view {s['length']:g}:{s['height']:g} (long:tall), the TOP view
  {s['width']:g}:{s['length']:g} (wide:long).
- Draw the model as a solid, filled, flat-shaded toy-like 3D object with simple soft shading, so every
  part reads as a filled coloured shape. Not line art, not a wireframe, not a sketch.
- No text, no labels, no arrows, no dimension lines, no grid, no frame or cell borders, no ground,
  no cast shadow, no other object.

Colour the parts with only these colours:
{palette_lines(req)}
"""


def bg_colour(im):
    """The colour of the image's outer 2% border: per channel, the median of the four strips' medians."""
    from PIL import ImageStat
    w, h = im.size
    m = max(2, min(w, h) // 50)
    strips = [im.crop(box).convert("RGB") for box in ((0, 0, w, m), (0, h - m, w, h), (0, 0, m, h), (w - m, 0, w, h))]
    medians = [ImageStat.Stat(strip).median for strip in strips]
    return tuple(sorted(md[c] for md in medians)[2] for c in range(3))


def fill_holes(mask):
    """Subject = everything the border cannot reach through background, so enclosed gaps count."""
    from PIL import Image, ImageDraw
    padded = Image.new("L", (mask.width + 2, mask.height + 2), 0)
    padded.paste(mask, (1, 1))
    padded = padded.point(lambda v: 0 if v else 255)  # background 255, subject 0
    ImageDraw.floodfill(padded, (0, 0), 128)
    return padded.crop((1, 1, mask.width + 1, mask.height + 1)).point(lambda v: 0 if v == 128 else 255)


def sheet_mask(cell, bg, tol=40):
    from PIL import Image, ImageChops
    small = cell.convert("RGB").resize((MASK_PX, MASK_PX), Image.BILINEAR)
    r, g, b = ImageChops.difference(small, Image.new("RGB", small.size, bg)).split()
    far = ImageChops.lighter(ImageChops.lighter(r, g), b).point(lambda v: 255 if v > tol else 0)
    return fill_holes(far)


def render_mask(png):
    from PIL import Image
    with Image.open(png) as im:
        alpha = im.convert("RGBA").getchannel("A").resize((MASK_PX, MASK_PX), Image.BILINEAR)
    return fill_holes(alpha.point(lambda v: 255 if v >= 128 else 0))


def cells(im):
    w, h = im.size
    boxes = [(0, 0, w // 2, h // 2), (w // 2, 0, w, h // 2), (0, h // 2, w // 2, h), (w // 2, h // 2, w, h)]
    return [(view, im.crop(box)) for view, box in zip(VIEWS, boxes)]


def touches_edge(box, px=MASK_PX):
    return box[0] <= 1 or box[1] <= 1 or box[2] >= px - 1 or box[3] >= px - 1


def isolate_subject(mask):
    """(subject mask, the largest part touches the cell edge, spill count). A neighbouring view that
    strays across the grid line arrives as a separate edge-touching part: it is dropped, not measured."""
    from PIL import Image, ImageChops, ImageDraw
    work = mask.copy()
    pixels = work.load()
    parts, label = [], 1
    for y in range(work.height):
        for x in range(work.width):
            if pixels[x, y] == 255 and label < 255:
                ImageDraw.floodfill(work, (x, y), label)
                part = work.point(lambda v, lab=label: 255 if v == lab else 0)
                parts.append((part.histogram()[255], part.getbbox(), part))
                label += 1
    if not parts:
        return mask, False, 0
    parts.sort(key=lambda p: -p[0])
    largest = parts[0]
    keep = [largest] + [p for p in parts[1:] if not touches_edge(p[1])]
    subject = Image.new("L", mask.size, 0)
    for _, _, part in keep:
        subject = ImageChops.lighter(subject, part)
    return subject, touches_edge(largest[1]), len(parts) - len(keep)


def sheet_masks(png, notes=None):
    from PIL import Image
    with Image.open(png) as im:
        im = im.convert("RGB")
        bg = bg_colour(im)
        masks = {}
        for view, cell in cells(im):
            subject, crosses, spill = isolate_subject(sheet_mask(cell, bg))
            masks[view] = subject
            if notes is not None:
                notes[view] = {"crosses": crosses, "spill": spill}
        return bg, masks


def spread(values):
    values = [v for v in values if v]
    return round(max(values) / min(values) - 1, 3) if len(values) > 1 else 0.0


def analyze_blueprint(png, req):
    notes = {}
    bg, masks = sheet_masks(png, notes)
    report = {"background": "%02X%02X%02X" % bg, "views": {}, "problems": [], "warnings": []}
    dims = {}
    for view, mask in masks.items():
        box = mask.getbbox()
        fill = mask.histogram()[255] / float(MASK_PX * MASK_PX)
        if not box or fill < 0.01:
            report["problems"].append(f"{view}: no subject in its cell")
            continue
        if notes[view]["crosses"]:
            report["problems"].append(f"{view}: the subject runs into its cell edge (crosses the grid)")
        if notes[view]["spill"]:
            report["warnings"].append(f"{view}: a neighbouring view spills into this cell (ignored)")
        w, h = box[2] - box[0], box[3] - box[1]
        across, down = EXPECT[view]
        want = req["size"][across] / req["size"][down]
        got = w / float(h)
        report["views"][view] = {"bbox": list(box), "fill": round(fill, 3), "aspect": round(got, 3),
                                 "want_aspect": round(want, 3), "aspect_error": round(abs(got / want - 1), 3)}
        dims[view] = (w, h)
    if len(dims) == 4:
        # Informational: an image model rarely keeps one scale across cells, and nothing downstream needs
        # it to (each view is read against its own bounding box, the size comes from the request).
        report["scale_spread"] = max(
            spread([dims["front"][1], dims["right"][1], dims["back"][1]]),   # height
            spread([dims["front"][0], dims["back"][0], dims["top"][0]]),     # width
            spread([dims["right"][0], dims["top"][1]]))                      # length
        if report["scale_spread"] > SCALE_TOL:
            report["warnings"].append(f"views drawn at different scales (spread {report['scale_spread']:.0%})")
    if report["problems"]:
        verdict = "LAYOUT"
    elif any(v["aspect_error"] > ASPECT_TOL for v in report["views"].values()):
        verdict = "PROPORTION"
    else:
        verdict = "ok"
    report["verdict"] = verdict
    return report


def asset_gen_request(req, prompt):
    return {"id": req["id"], "mode": "generate", "prompt": prompt, "references": req.get("references", [])}


def cmd_blueprint(args):
    req = load_request(args.request)
    ag_req = asset_gen_request(req, blueprint_prompt(req))
    text = ASSET_GEN.prompt_text(ag_req)
    if args.dry_run:
        print(" ".join(ASSET_GEN.argv(ag_req)) + " < prompt")
        print(text)
        return EXIT_OK
    folder = scratch(req, "blueprint")
    (folder / "prompt.txt").write_text(text)
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.variants) as pool:
        records = list(pool.map(lambda n: ASSET_GEN.run_variant(ag_req, n, text, folder),
                                range(1, args.variants + 1)))
    passed = 0
    for r in records:
        if not r["generations"]:
            say(f"{req['id']} blueprint v{r['variant']}: NO IMAGE rc={r['rc']} {r['wall_s']}s")
            continue
        report = analyze_blueprint(folder / f"v{r['variant']}.png", req)
        r["blueprint"] = report
        (folder / f"v{r['variant']}.json").write_text(json.dumps(r, indent=1) + "\n")
        passed += report["verdict"] == "ok"
        aspects = " ".join(f"{v}={d['aspect_error']:.0%}" for v, d in report["views"].items())
        detail = "; ".join(report["problems"] + report["warnings"]) or "four clean views"
        detail += f" — aspect error {aspects}"
        warn = f" WARNING generations={r['generations']} shell={len(r['shell_commands'])}" \
            if r["generations"] > 1 or r["shell_commands"] else ""
        say(f"{req['id']} blueprint v{r['variant']}: {report['verdict']} {r['wall_s']}s — {detail}{warn}")
    if not any(r["generations"] for r in records):
        print("[model-gen] no variant produced an image", file=sys.stderr)
        return EXIT_ERROR
    say(f"candidates: {rel(folder)}/ — look at them, then: "
        f"python3 Tools/pf/model-gen.py select-blueprint {args.request} <n>")
    return EXIT_OK if passed else EXIT_DRIFT


def cmd_select_blueprint(args):
    req = load_request(args.request)
    folder = CANDIDATES / req["id"] / "blueprint"
    src, facts_path = folder / f"v{args.variant}.png", folder / f"v{args.variant}.json"
    if not src.is_file():
        die(f"no blueprint candidate {rel(src)}")
    record = json.loads(facts_path.read_text())
    out = out_dir(req)
    out.mkdir(parents=True, exist_ok=True)
    dst = out / "blueprint.png"
    shutil.copyfile(src, dst)
    provenance = {
        "schema": "model-gen-blueprint/v1",
        "id": req["id"],
        "status": "pending-user-review",
        "request": rel(req["_path"]),
        "tool": "codex exec built-in image_gen (via asset-gen)",
        "model": os.environ.get("ASSETGEN_MODEL", "gpt-6-astra"),
        "prompt": (folder / "prompt.txt").read_text(),
        "inputs": [{"path": r["path"], "role": r.get("role", "style"), "sha256": sha256(ROOT / r["path"])}
                   for r in req.get("references", [])],
        "output": {"path": rel(dst), "sha256": sha256(dst), **record.get("facts", {})},
        "analysis": record.get("blueprint"),
        "variant": args.variant,
        "selected_at": now(),
    }
    Path(str(dst) + ".gen.json").write_text(json.dumps(provenance, indent=1) + "\n")
    verdict = (record.get("blueprint") or {}).get("verdict", "?")
    say(f"selected blueprint v{args.variant} ({verdict}) -> {rel(dst)} (+ .gen.json, status pending-user-review)")
    return EXIT_OK


# ── stage 2: the model ──────────────────────────────────────────────────────────────────────────


def mg_api():
    match = re.search(r'MG_API = r"""\n(.*?)\n"""', HARNESS.read_text(), re.S)
    if not match:
        die(f"{rel(HARNESS)} carries no MG_API block")
    return match.group(1)


AUTHOR_BRIEF = """You are modelling ONE low-poly 3D game asset by writing a Blender 5.2 Python script.
A tool runs your script headless, measures the result against the hard checks below, exports FBX
for Unity and renders it from the blueprint's four views. You never see Blender: only this brief, the
images, and (after round 1) what the tool measured.

Reply with exactly ONE fenced ```python block holding the COMPLETE script, and nothing after it. Do
not run shell commands and do not try to read or write files: you have no workspace, and the tool
runs the script itself.

## How to model it
- Silhouette first. The model is read from a high game camera at a distance: chunky, stylised toy
  proportions, big readable shapes, a few purposeful details. Spend triangles on the outline the
  views show, not on faces nobody sees.
- Build from the `mg` helpers (in scope, no import) and plain bmesh/mathutils where a shape needs it.
  Allowed imports: bpy, bmesh, math, mathutils — nothing else. No file, OS, network or randomness;
  no bpy.ops calls, no bpy.data.materials (use mg.color), no bpy.app/bpy.utils. The tool refuses a
  script that tries, before running it.
- Hard checks, all required: the overall bounding box (±3%), the ground and centre pivot, the
  triangle budget, every face on a palette material via mg.color, the required parts present under
  their exact names. Mirrors, bumpers and wheels count toward the bounding box.
- When the blueprint and the bounding box disagree, the bounding box wins; follow the blueprint's
  shapes, part layout and colours inside it.
- Bevel the big edges a little (it reads as a toy, not a crate); leave small details sharp.
- A part that moves (wheel, brush, fan, door) is its own object, origin at its pivot, never joined.
  Join static detail with mg.join so it is one draw.
"""


def author_prompt(req, legend, prev, api):
    s = req["size"]
    notes = f"\nNotes: {req['notes'].strip()}\n" if req.get("notes") else ""
    text = f"""{AUTHOR_BRIEF}
## The asset
`{req['id']}`: {req['subject'].strip()}
{notes}
Hard checks:
- Overall bounding box: width (X) {s['width']:g} m, height (Z) {s['height']:g} m, length (Y) {s['length']:g} m, ±3%.
- Lowest point on z = 0; bounding box centred on x = 0, y = 0; the FRONT faces -Y.
- At most {req['max_tris']} triangles, counted after bevels.
- Every face on a palette material, mg.color(key):
{palette_lines(req)}
- Required separate parts (exact names):
{parts_lines(req)}

## The attached images
{legend}

Image 1's cells: top-left FRONT (seen from -Y; image right = +X), top-right RIGHT (seen from +X; the
front points LEFT, image right = +Y), bottom-left BACK (seen from +Y), bottom-right TOP (seen from +Z;
the front points DOWN, image up = +Y).

## The mg helpers
{api}
"""
    if prev:
        facts = prev["facts"]
        failed = [f"- {c['id']}: {c['detail']}" for c in facts.get("checks", []) if not c["ok"]]
        if facts.get("script_error"):
            failed.insert(0, f"- the script raised: {facts['script_error']}")
        iou = facts.get("iou") or {}
        scores = ", ".join(f"{v} {iou[v]:.2f}" for v in VIEWS if v in iou) or "not rendered"
        measured = facts.get("size")
        size = (f"{measured['width']:.3f} × {measured['height']:.3f} × {measured['length']:.3f} m (w × h × l)"
                if measured else "nothing measured")
        text += f"""
## Round {prev['round']}: your previous script
```python
{prev['script'] or '# (no script came back)'}
```

## What the tool measured
- Size: {size}; triangles: {facts.get('tris', '?')}
- Silhouette match against the blueprint (1.00 = identical outline, scaled to the same box): {scores}
- Failed checks:
{chr(10).join(failed) or '- none'}

Fix every failed check first. Then, view by view in the comparison image, move the silhouettes and
part layout toward the blueprint where they differ most. Return the complete revised script.
"""
    return text


def author_images(req, blueprint, prev):
    """(absolute path, legend) in attachment order."""
    images = [(blueprint, "the approved BLUEPRINT: what to build")]
    images += [(ROOT / r["path"], f"REFERENCE ({r.get('role', 'style')} only)") for r in req.get("references", [])]
    if prev:
        rdir = prev["dir"]
        if (rdir / "compare.png").is_file():
            images.append((rdir / "compare.png",
                           "COMPARISON of your previous model: per view, blueprint left, your render right"))
        if (rdir / "hero.png").is_file():
            images.append((rdir / "hero.png", "your previous model from a 3/4 angle"))
    legend = "\n".join(f"- Image {i}: {label}" for i, (_, label) in enumerate(images, 1))
    return [str(p) for p, _ in images], legend


def author_argv(images):
    args = [ASSET_GEN.codex_bin(), "exec", "--json", "-s", "read-only", "--skip-git-repo-check",
            "--ignore-user-config", "--ephemeral"]
    if os.environ.get("MODELGEN_MODEL"):
        args += ["-m", os.environ["MODELGEN_MODEL"]]
    args += ["-c", f'model_reasoning_effort="{os.environ.get("MODELGEN_EFFORT", "medium")}"']
    if images:
        args += ["-i", *images]
    return args + ["-"]  # -i is variadic: the prompt goes on stdin


def run_author(text, images, rdir):
    t0 = time.time()
    log = rdir / "codex.jsonl"
    timeout = int(os.environ.get("MODELGEN_TIMEOUT_S", "900"))
    try:
        # Outside the repo: its AGENTS.md and hooks are for coding agents, not for this call.
        with open(log, "w") as fh, tempfile.TemporaryDirectory(prefix="model-gen-") as cwd:
            rc = subprocess.run(author_argv(images), input=text, text=True, stdout=fh,
                                stderr=subprocess.STDOUT, cwd=cwd, timeout=timeout).returncode
    except subprocess.TimeoutExpired:
        rc = "timeout"
    thread, reply, shell, usage = None, "", [], None
    for line in log.read_text().splitlines():
        if not line.startswith("{"):
            continue
        event = json.loads(line)
        thread = thread or event.get("thread_id")
        usage = event.get("usage") or usage
        item = event.get("item") or {}
        if item.get("type") == "agent_message":
            reply = item.get("text") or reply
        elif item.get("type") == "command_execution":
            shell.append(item.get("command"))
    return {"rc": rc, "wall_s": round(time.time() - t0, 1), "thread_id": thread, "reply": reply,
            "shell_commands": shell, "usage": usage}


def extract_script(reply):
    blocks = re.findall(r"```(?:python|py)?[ \t]*\n(.*?)```", reply or "", re.S)
    return blocks[-1].strip() + "\n" if blocks else None


def dotted(node):
    parts = []
    while isinstance(node, ast.Attribute):
        parts.append(node.attr)
        node = node.value
    if isinstance(node, ast.Name):
        parts.append(node.id)
        return ".".join(reversed(parts))
    return None


def script_guard(source):
    """Refusals for a model-written script, before Blender runs it. A screen, not a sandbox: it keeps
    an honest script inside geometry (no files, OS, operators, handlers, randomness), and names what it
    refused so the next round can fix it."""
    try:
        tree = ast.parse(source)
    except SyntaxError as exc:
        return [f"SyntaxError: {exc.msg} (line {exc.lineno})"]
    nodes = list(ast.walk(tree))
    inner = {id(n.value) for n in nodes if isinstance(n, ast.Attribute)}
    refused = []
    for node in nodes:
        if isinstance(node, ast.Import):
            for a in node.names:
                if a.name.split(".")[0] not in ALLOWED_IMPORTS:
                    refused.append(f"import {a.name}")
                elif a.name.startswith("bpy") and a.asname:
                    refused.append(f"import {a.name} as {a.asname} (use bpy by its name)")
        elif isinstance(node, ast.ImportFrom):
            module = node.module or ""
            if node.level or module.split(".")[0] not in ALLOWED_IMPORTS or module.startswith("bpy"):
                refused.append(f"from {module or '.'} import … (only mathutils/bmesh/math names may be imported)")
        elif isinstance(node, ast.Name):
            if node.id in REFUSED_NAMES:
                refused.append(f"{node.id}()")
            elif node.id == "bpy" and id(node) not in inner:
                refused.append("bpy used bare (aliased or passed around)")
        elif isinstance(node, ast.Attribute) and id(node) not in inner:
            chain = dotted(node)
            for link in ([chain] if chain else []) + [node.attr]:
                if link.startswith("__") or ".__" in link:
                    refused.append(f"dunder attribute in {chain or node.attr}")
            if chain and any(chain == c or chain.startswith(c + ".") for c in REFUSED_CHAINS):
                refused.append(chain + (" (bpy.ops is refused: build with mg and bmesh)" if chain.startswith("bpy.ops") else ""))
    return sorted(set(refused))


def blender_bin():
    explicit = os.environ.get("BLENDER_BIN")
    if explicit:
        return explicit
    mac = Path("/Applications/Blender.app/Contents/MacOS/Blender")
    if mac.exists():
        return str(mac)
    found = shutil.which("blender")
    if not found:
        die("Blender not found: install Blender 5.x or set BLENDER_BIN")
    return found


def harness_spec(req):
    return {"palette": req["palette"], "size": req["size"], "max_tris": req["max_tris"],
            "parts": [p["name"] for p in req.get("parts", [])], "size_tolerance": 0.03,
            "hero": req.get("hero", {"pitch": 30, "yaw": 35}), "view_px": 512, "hero_px": 768}


def run_blender(script, req, rdir):
    """Run the harness on one script. Returns facts (ok False with a reason on any failure)."""
    spec_path = rdir / "spec.json"
    spec_path.write_text(json.dumps(harness_spec(req), indent=1) + "\n")
    for stale in ["facts.json", "model.fbx", "hero.png"] + [f"view_{v}.png" for v in VIEWS]:
        (rdir / stale).unlink(missing_ok=True)
    cmd = [blender_bin(), "-b", "--factory-startup", "--python-exit-code", "3", "-P", str(HARNESS), "--",
           "--script", str(script), "--spec", str(spec_path), "--out", str(rdir)]
    timeout = int(os.environ.get("MODELGEN_BLENDER_TIMEOUT_S", "300"))
    try:
        with open(rdir / "blender.log", "w") as fh, tempfile.TemporaryDirectory(prefix="model-gen-bl-") as cwd:
            subprocess.run(cmd, stdout=fh, stderr=subprocess.STDOUT, cwd=cwd, timeout=timeout)
    except subprocess.TimeoutExpired:
        return {"ok": False, "checks": [], "script_error": f"Blender did not finish within {timeout} s "
                                                           "(an endless loop, or far too much geometry)"}
    facts_path = rdir / "facts.json"
    if not facts_path.is_file():
        tail = "\n".join((rdir / "blender.log").read_text(errors="replace").splitlines()[-15:])
        return {"ok": False, "checks": [], "harness_error": f"no facts.json; Blender log tail:\n{tail}"}
    return json.loads(facts_path.read_text())


def shape_iou(a, b, px=128):
    """Outline match of two masks, each cropped to its own bounding box and scaled to one square."""
    from PIL import Image, ImageChops
    box_a, box_b = a.getbbox(), b.getbbox()
    if not box_a or not box_b:
        return 0.0
    norm_a = a.crop(box_a).resize((px, px), Image.NEAREST).convert("1")
    norm_b = b.crop(box_b).resize((px, px), Image.NEAREST).convert("1")
    inter = ImageChops.logical_and(norm_a, norm_b).convert("L").histogram()[255]
    union = ImageChops.logical_or(norm_a, norm_b).convert("L").histogram()[255]
    return round(inter / union, 3) if union else 0.0


def views_sheet(rdir, cell=512):
    from PIL import Image
    sheet = Image.new("RGB", (cell * 2, cell * 2), (255, 255, 255))
    for i, view in enumerate(VIEWS):
        with Image.open(rdir / f"view_{view}.png") as im:
            im = im.convert("RGBA").resize((cell, cell), Image.LANCZOS)
            sheet.paste(im, ((i % 2) * cell, (i // 2) * cell), im)
    sheet.save(rdir / "views.png")


def compare_sheet(blueprint, rdir, iou, cell=384):
    """Per view: the blueprint cell, then the render, each labelled. Two views per row."""
    from PIL import Image, ImageDraw
    with Image.open(blueprint) as bp:
        bp_cells = dict(cells(bp.convert("RGB")))
    sheet = Image.new("RGB", (cell * 4, cell * 2 + 2 * 24), (255, 255, 255))
    draw = ImageDraw.Draw(sheet)
    for i, view in enumerate(VIEWS):
        x, y = (i % 2) * cell * 2, (i // 2) * (cell + 24)
        sheet.paste(bp_cells[view].resize((cell, cell), Image.LANCZOS), (x, y + 24))
        with Image.open(rdir / f"view_{view}.png") as im:
            im = im.convert("RGBA").resize((cell, cell), Image.LANCZOS)
            sheet.paste(im, (x + cell, y + 24), im)
        draw.text((x + 6, y + 6), f"{view.upper()} blueprint", fill=(40, 40, 40))
        draw.text((x + cell + 6, y + 6), f"{view.upper()} model  outline match {iou.get(view, 0):.2f}", fill=(40, 40, 40))
        draw.line([(x + cell, y + 24), (x + cell, y + 24 + cell)], fill=(200, 200, 200))
    sheet.save(rdir / "compare.png")


def score_round(blueprint, rdir, facts):
    if not facts.get("views"):
        return
    _, bp_masks = sheet_masks(blueprint)
    facts["iou"] = {v: shape_iou(bp_masks[v], render_mask(rdir / f"view_{v}.png")) for v in VIEWS}
    facts["iou_mean"] = round(sum(facts["iou"].values()) / len(VIEWS), 3)
    views_sheet(rdir)
    compare_sheet(blueprint, rdir, facts["iou"])


def failed_checks(facts):
    out = [c["id"] for c in facts.get("checks", []) if not c["ok"]]
    if facts.get("script_error"):
        out.insert(0, "script")
    if facts.get("harness_error"):
        out.insert(0, "harness")
    return out


def run_chain(req, n, rounds, blueprint, api):
    vdir = CANDIDATES / req["id"] / "model" / f"v{n}"
    target = float(os.environ.get("MODELGEN_IOU_TARGET", "0.88"))
    history, prev = [], None
    for k in range(1, rounds + 1):
        rdir = vdir / f"r{k}"
        if rdir.exists():
            shutil.rmtree(rdir)
        rdir.mkdir(parents=True)
        images, legend = author_images(req, blueprint, prev)
        text = author_prompt(req, legend, prev, api)
        (rdir / "prompt.txt").write_text(text)
        call = run_author(text, images, rdir)
        script = extract_script(call["reply"])
        record = {"round": k, "rc": call["rc"], "wall_s": call["wall_s"], "thread_id": call["thread_id"],
                  "shell_commands": call["shell_commands"], "usage": call["usage"]}
        if script is None:
            if not call["reply"]:
                record["error"] = f"Codex returned no reply (rc={call['rc']}); see {rel(rdir / 'codex.jsonl')}"
                history.append(record)
                break  # a transport failure repeats; the next round would only spend more
            facts = {"ok": False, "checks": [],
                     "script_error": "the reply held no ```python block; reply with exactly one complete script"}
        else:
            (rdir / "build.py").write_text(script)
            refused = script_guard(script)
            if refused:
                facts = {"ok": False, "checks": [], "script_error": "refused before running: " + "; ".join(refused)}
            else:
                t0 = time.time()
                facts = run_blender(rdir / "build.py", req, rdir)
                record["blender_s"] = round(time.time() - t0, 1)
                score_round(blueprint, rdir, facts)
                if facts.get("harness_error"):
                    record["error"] = f"the harness failed (not the script): see {rel(rdir / 'facts.json')}"
                    (rdir / "facts.json").write_text(json.dumps(facts, indent=1) + "\n")
                    history.append(record)
                    say(f"{req['id']} model v{n} r{k}: HARNESS ERROR — {record['error']}")
                    break  # our failure, not the model's: another round cannot fix it
        (rdir / "facts.json").write_text(json.dumps(facts, indent=1) + "\n")
        record.update(ok=bool(facts.get("ok")), failed=failed_checks(facts), tris=facts.get("tris"),
                      size=facts.get("size"), iou=facts.get("iou"), iou_mean=facts.get("iou_mean"))
        history.append(record)
        say(f"{req['id']} model v{n} r{k}: " + (
            f"ok iou={facts.get('iou_mean')} tris={facts.get('tris')}" if facts.get("ok") else
            f"FAIL {','.join(record['failed']) or record.get('error', '')}"
            + (f" iou={facts['iou_mean']}" if facts.get("iou_mean") is not None else "")) + f" ({call['wall_s']}s)")
        prev = {"round": k, "script": script, "facts": facts, "dir": rdir}
        if facts.get("ok") and facts.get("iou_mean", 0) >= target:
            break
    passing = [r for r in history if r.get("ok")]
    best = max(passing, key=lambda r: r.get("iou_mean") or 0)["round"] if passing else None
    summary = {"variant": n, "best_round": best, "rounds": history}
    (CANDIDATES / req["id"] / "model" / f"v{n}.json").write_text(json.dumps(summary, indent=1) + "\n")
    return summary


def selected_blueprint(req):
    bp = out_dir(req) / "blueprint.png"
    if not bp.is_file():
        die(f"no selected blueprint at {rel(bp)}: run `blueprint`, look, then `select-blueprint` first")
    gen = Path(str(bp) + ".gen.json")
    status = json.loads(gen.read_text()).get("status") if gen.is_file() else None
    return bp, status


def cmd_build(args):
    req = load_request(args.request)
    blueprint, status = selected_blueprint(req)
    api = mg_api()
    if args.dry_run:
        images, legend = author_images(req, blueprint, None)
        print(" ".join(author_argv(images)) + " < prompt")
        print(author_prompt(req, legend, None, api))
        return EXIT_OK
    if status != "approved":
        say(f"WARNING: the blueprint is '{status}', not 'approved'. An interactive run builds only from a "
            "blueprint a person approved.")
    blender_bin()
    scratch(req, "model")
    with concurrent.futures.ThreadPoolExecutor(max_workers=args.variants) as pool:
        summaries = list(pool.map(lambda n: run_chain(req, n, args.rounds, blueprint, api),
                                  range(1, args.variants + 1)))
    ran = False
    for s in summaries:
        ran = ran or any(r.get("blender_s") is not None for r in s["rounds"])
        if s["best_round"]:
            r = s["rounds"][s["best_round"] - 1]
            say(f"{req['id']} model v{s['variant']}: best r{s['best_round']} iou={r['iou_mean']} "
                f"tris={r['tris']} size={r['size']}")
        else:
            last = s["rounds"][-1] if s["rounds"] else {}
            say(f"{req['id']} model v{s['variant']}: no round passed (last: "
                f"{','.join(last.get('failed', [])) or last.get('error', 'nothing ran')})")
    folder = CANDIDATES / req["id"] / "model"
    if not ran:
        print("[model-gen] no round produced a script Blender could run", file=sys.stderr)
        return EXIT_ERROR
    say(f"candidates: {rel(folder)}/v<n>/r<k>/ (hero.png, compare.png) — look at them, then: "
        f"python3 Tools/pf/model-gen.py select {args.request} <n>")
    return EXIT_OK if any(s["best_round"] for s in summaries) else EXIT_DRIFT


def cmd_select(args):
    req = load_request(args.request)
    blueprint, _ = selected_blueprint(req)
    summary_path = CANDIDATES / req["id"] / "model" / f"v{args.variant}.json"
    if not summary_path.is_file():
        die(f"no model candidate v{args.variant}: run `build` first")
    summary = json.loads(summary_path.read_text())
    k = args.round or summary.get("best_round")
    if not k:
        die(f"v{args.variant} has no passing round; name one with --round K --force to take it anyway")
    rdir = summary_path.parent / f"v{args.variant}" / f"r{k}"
    facts = json.loads((rdir / "facts.json").read_text())
    if not facts.get("ok") and not args.force:
        die(f"v{args.variant} r{k} failed {','.join(failed_checks(facts))}; --force takes it anyway")
    if not (rdir / "model.fbx").is_file():
        die(f"v{args.variant} r{k} exported no FBX")
    out = out_dir(req)
    out.mkdir(parents=True, exist_ok=True)
    fbx = out / f"{req['id']}.fbx"
    shutil.copyfile(rdir / "build.py", out / "build.py")
    shutil.copyfile(rdir / "model.fbx", fbx)
    for name in ("views.png", "hero.png", "compare.png"):
        if (rdir / name).is_file():
            shutil.copyfile(rdir / name, out / name)
    record = summary["rounds"][k - 1]
    provenance = {
        "schema": "model-gen-provenance/v1",
        "id": req["id"],
        "status": "pending-user-review",
        "request": rel(req["_path"]),
        "consumer": req.get("consumer"),
        "blueprint": {"path": rel(blueprint), "sha256": sha256(blueprint)},
        "author": {"tool": "codex exec", "model": os.environ.get("MODELGEN_MODEL", "codex default"),
                   "effort": os.environ.get("MODELGEN_EFFORT", "medium"), "thread_id": record.get("thread_id")},
        "harness": {"version": facts.get("harness"), "blender": facts.get("blender")},
        "variant": args.variant,
        "round": k,
        "rounds": [{key: r.get(key) for key in ("round", "ok", "failed", "iou_mean", "tris")} for r in summary["rounds"]],
        "forced": bool(not facts.get("ok")),
        "script": {"path": rel(out / "build.py"), "sha256": sha256(out / "build.py"),
                   "selected_sha256": sha256(out / "build.py")},
        "fbx": {"path": rel(fbx), "sha256": sha256(fbx)},
        "facts": compact_facts(facts),
        "selected_at": now(),
    }
    (out / "model.gen.json").write_text(json.dumps(provenance, indent=1) + "\n")
    say(f"selected model v{args.variant} r{k} -> {rel(out)}/ ({req['id']}.fbx, build.py, views, "
        "model.gen.json status pending-user-review)")
    return EXIT_OK


def compact_facts(facts):
    keep = ("ok", "size", "bounds", "tris", "materials", "empties", "iou", "iou_mean", "checks")
    out = {k: facts.get(k) for k in keep if k in facts}
    out["objects"] = [{"name": o["name"], "tris": o["tris"], "parent": o["parent"]} for o in facts.get("objects", [])]
    return out


def cmd_rebuild(args):
    req = load_request(args.request)
    out = out_dir(req)
    gen_path, script = out / "model.gen.json", out / "build.py"
    if not gen_path.is_file() or not script.is_file():
        die(f"nothing selected in {rel(out)}: `select` a model first")
    refused = script_guard(script.read_text())
    if refused:
        die("build.py refused: " + "; ".join(refused))
    rdir = scratch(req, "rebuild")
    facts = run_blender(script, req, rdir)
    if (out / "blueprint.png").is_file():
        score_round(out / "blueprint.png", rdir, facts)
    if not facts.get("ok"):
        say(f"rebuild FAILED {','.join(failed_checks(facts))}: {facts.get('script_error') or facts.get('harness_error') or ''}"
            f" — nothing in {rel(out)} was changed; facts in {rel(rdir)}/facts.json")
        return EXIT_DRIFT
    fbx = out / f"{req['id']}.fbx"
    shutil.copyfile(rdir / "model.fbx", fbx)
    for name in ("views.png", "hero.png", "compare.png"):
        if (rdir / name).is_file():
            shutil.copyfile(rdir / name, out / name)
    provenance = json.loads(gen_path.read_text())
    provenance["script"]["sha256"] = sha256(script)
    provenance["script"]["edited"] = provenance["script"]["sha256"] != provenance["script"].get("selected_sha256")
    provenance["fbx"]["sha256"] = sha256(fbx)
    provenance["harness"] = {"version": facts.get("harness"), "blender": facts.get("blender")}
    provenance["facts"] = compact_facts(facts)
    provenance["rebuilt_at"] = now()
    gen_path.write_text(json.dumps(provenance, indent=1) + "\n")
    say(f"rebuilt {rel(fbx)} tris={facts.get('tris')} iou={facts.get('iou_mean')}"
        + (" (build.py was edited since selection)" if provenance["script"]["edited"] else ""))
    return EXIT_OK


# ── status ──────────────────────────────────────────────────────────────────────────────────────


def stage_state(gen_path, sha_keys):
    """(label, drift messages) for one selected artifact and its provenance."""
    if not gen_path.is_file():
        return ("—", [])
    gen = json.loads(gen_path.read_text())
    drift = []
    for key, path in sha_keys(gen):
        p = ROOT / path
        if not p.is_file():
            drift.append(f"{path} is missing")
        elif sha256(p) != key:
            drift.append(f"{path} no longer matches its provenance")
    return (gen.get("status", "?"), drift)


def cmd_status(args):
    paths = [Path(p) for p in args.requests] or sorted(REQUESTS.glob("*.json"))
    rows, drift = [], []
    for p in paths:
        req = load_request(p)
        out = out_dir(req)
        if args.under and not out.resolve().is_relative_to((ROOT / args.under).resolve()):
            continue
        bp_state, bp_drift = stage_state(out / "blueprint.png.gen.json",
                                         lambda g: [(g["output"]["sha256"], g["output"]["path"])])
        model_state, model_drift = stage_state(out / "model.gen.json",
                                               lambda g: [(g["script"]["sha256"], g["script"]["path"]),
                                                          (g["fbx"]["sha256"], g["fbx"]["path"])])
        facts = {}
        if (out / "model.gen.json").is_file():
            facts = json.loads((out / "model.gen.json").read_text()).get("facts", {})
        size = facts.get("size")
        rows.append({"id": req["id"], "blueprint": bp_state, "model": model_state,
                     "tris": f"{facts['tris']} / {req['max_tris']}" if facts.get("tris") is not None else f"— / {req['max_tris']}",
                     "size": (f"{size['width']:.2f} × {size['height']:.2f} × {size['length']:.2f}" if size else "—"),
                     "match": f"{facts['iou_mean']:.2f}" if facts.get("iou_mean") is not None else "—",
                     "out": rel(out)})
        drift += [f"{req['id']}: {d}" for d in bp_drift + model_drift]
    header = "| Model | Blueprint | Model status | Triangles | Size W × H × L (m) | Outline match | Files |\n" \
             "|---|---|---|---|---|---|---|\n"
    table = header + "".join(f"| `{r['id']}` | {r['blueprint']} | {r['model']} | {r['tris']} | {r['size']} | "
                             f"{r['match']} | `{r['out']}/` |\n" for r in rows)
    print(table, end="")
    for d in drift:
        print(f"[model-gen] DRIFT {d}", file=sys.stderr)
    if args.md:
        md = Path(args.md)
        md.parent.mkdir(parents=True, exist_ok=True)
        md.write_text("# Models\n\nGenerated by `python3 Tools/pf/model-gen.py status --md` — the blueprint and "
                      "model state of every 3D model this package owns (procedure: the `pf-model-gen` skill). "
                      "Each `Files` folder holds `blueprint.png`, `build.py` (the source), the FBX, "
                      "`views.png`, `hero.png` and their `.gen.json` provenance.\n\n" + table)
        say(f"wrote {rel(md)}")
    return EXIT_DRIFT if drift else EXIT_OK


# ── plumbing ────────────────────────────────────────────────────────────────────────────────────


def scratch(req, stage):
    folder = CANDIDATES / req["id"] / stage
    folder.mkdir(parents=True, exist_ok=True)
    ignore = CANDIDATES / ".gitignore"
    if not ignore.exists():
        ignore.write_text("# model-gen scratch: only the selected files and their .gen.json are committed.\n*\n")
    return folder


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    b = sub.add_parser("blueprint")
    b.add_argument("request")
    b.add_argument("--variants", type=int, default=2)
    b.add_argument("--dry-run", action="store_true")
    sb = sub.add_parser("select-blueprint")
    sb.add_argument("request")
    sb.add_argument("variant", type=int)
    m = sub.add_parser("build")
    m.add_argument("request")
    m.add_argument("--variants", type=int, default=1)
    m.add_argument("--rounds", type=int, default=3)
    m.add_argument("--dry-run", action="store_true")
    s = sub.add_parser("select")
    s.add_argument("request")
    s.add_argument("variant", type=int)
    s.add_argument("--round", type=int)
    s.add_argument("--force", action="store_true")
    r = sub.add_parser("rebuild")
    r.add_argument("request")
    st = sub.add_parser("status")
    st.add_argument("requests", nargs="*")
    st.add_argument("--under")
    st.add_argument("--md")
    args = ap.parse_args()
    if getattr(args, "variants", 1) < 1 or getattr(args, "rounds", 1) < 1:
        die("--variants and --rounds must be >= 1")
    return {"blueprint": cmd_blueprint, "select-blueprint": cmd_select_blueprint, "build": cmd_build,
            "select": cmd_select, "rebuild": cmd_rebuild, "status": cmd_status}[args.cmd](args)


if __name__ == "__main__":
    sys.exit(main())
