#!/usr/bin/env python3
# GENERATED by PrototypeFramework 0.4.2 from Documentation~/agent/tools/pixel-probe.py — do not edit here. Change it in the framework repo, then run Framework/Agent Docs/Sync (editor) or Tools/Build/pf-build.sh agentdocs.
# pixel-probe.py — settle a capture's *floor* deterministically, with no model in the loop.
#
# `visual-judge.sh` asks a vision model "does this look right?" — the ceiling, and the right
# question for a `kind: finish` story. This asks the floor question a `kind: function` story
# actually needs: "is this wired up at all?" — did anything render, is it the right material,
# the right colour space, is the renderer enabled, is it on top of what it should be on top of.
# Every one of those failures moves a *known pixel* to a *known wrong colour*, so every one of
# them is settled by reading that pixel and comparing it to the design token it was drawn from.
# No LLM, no quota, no non-determinism: this runs inside `dotnet test` and answers the same way
# every time.
#
# It never judges composition, balance, polish or "does it look good" — those are the ceiling's
# and they belong to `visual-judge.sh` against an approved reference.
#
# Usage:
#   Tools/pf/pixel-probe.py --capture <png> --points <points.json>
#                               [--min-variance <f>] [--window <n>] [--verbose]
#   Tools/pf/pixel-probe.py --variance-only <png> [--min-variance <f>]
#   Tools/pf/pixel-probe.py --generate <layout.json> [--out <points.json>]
#
#   --capture        the PNG to read
#   --points         the sample-point declaration (schema `pixel-probe/v1`, see below)
#   --variance-only  print the capture's luma variance and settle ONLY the broken-capture check
#                    (this is the mode `visual-judge.sh` shells out to)
#   --min-variance   override the flat-capture threshold (default: the points file, else 4.0)
#   --window         override every probe's sample-box size (odd, in design units)
#   --generate       machine-generate a points file from a higher-level layout declaration
#                    (schema `pixel-probe-layout/v1`) — anchored rects × design tokens, so no
#                    coordinate and no hex value is ever hand-typed into the points file
#   --out            where --generate writes (default: stdout)
#
# Exit-code contract (CliConventions.ExitCode): 0 Ok · 1 Drift · 2 Error.
#   0 = every probe within tolerance (or, in --variance-only, the capture is not flat)
#   1 = at least one probe outside tolerance (or, in --variance-only, the capture IS flat)
#   2 = could not run (no capture, no points file, undecodable PNG, malformed declaration)
#
# The flat-capture check runs FIRST and outranks every probe. A capture that is very nearly one
# flat colour is a BROKEN CAPTURE, not a wrong colour: every probe would "fail" and every one of
# those failures would name the wrong cause. Reported as exit 2, never as exit 1. This is not
# hypothetical here — see `Tools/UiGate/judge-calibration.md`: the Game View's render texture has
# been observed reading back a uniform `RGBA(0.098, 0.098, 0.122, 1)` across the entire frame.
#
# Why ΔE76 (CIE76) and not an RGB distance
#   sRGB distance is not perceptually even: 20 units apart is glaring in a dark navy like
#   `ShelfRecess` and invisible in a cream like `Ground`, so one repo-wide RGB tolerance is either
#   too tight on the lights or too loose on the darks. ΔE76 is computed in CIELAB, which is
#   roughly perceptually uniform, so ONE number means the same thing on every token: ~1 is the
#   just-noticeable difference, ~2-3 is "a careful eye sees it", >10 is "those are different
#   colours". It also has the property this gate needs most — a colour-space mistake (a linear
#   value written where an sRGB one was meant, or the reverse) shifts midtone LIGHTNESS hard, and
#   L* is exactly what ΔE76 is most sensitive to. CIE76 rather than CIEDE2000 on purpose: the
#   later formulas buy accuracy in saturated hue differences this gate does not need, at the cost
#   of a page of magic constants nobody in review can check by hand.
#
# Decoder: Pillow when importable (fast path), otherwise a stdlib-only PNG reader (zlib +
# struct — 8/16-bit, colour types 0/2/3/4/6, non-interlaced). numpy is NOT required and is NOT
# present on this rig. Both paths produce identical numbers: variance is always measured on the
# same integer luma over the same deterministic subsample, so a variance reading is comparable
# across runs and across machines (which is what `visual-judge.sh`'s HALT rule leans on).

import argparse
import ast
import json
import os
import re
import struct
import sys
import zlib

TOOL = "pixel-probe"

EXIT_OK = 0
EXIT_DRIFT = 1
EXIT_ERROR = 2

DEFAULT_MIN_VARIANCE = 4.0
DEFAULT_TOLERANCE = 10.0
DEFAULT_WINDOW = 5
DEFAULT_SPACE = (1080, 1920)

# Cap on how many pixels the variance reading looks at. A flat frame is flat everywhere, so a
# deterministic stride is as good as the full frame and keeps the stdlib decoder path usable.
VARIANCE_SAMPLE_CAP = 262144


class ProbeError(Exception):
    """Anything that makes the run impossible — always exit 2, never exit 1."""


def warn(msg):
    sys.stderr.write("[%s] %s\n" % (TOOL, msg))


# --- image loading ----------------------------------------------------------------------------


class Raster(object):
    """A decoded image as one flat RGB byte buffer. Deliberately decoder-agnostic."""

    __slots__ = ("width", "height", "data")

    def __init__(self, width, height, data):
        self.width = width
        self.height = height
        self.data = data

    def rgb(self, x, y):
        i = (y * self.width + x) * 3
        return self.data[i], self.data[i + 1], self.data[i + 2]


def _load_with_pillow(path):
    try:
        from PIL import Image
    except ImportError:
        return None
    try:
        with Image.open(path) as im:
            rgb = im.convert("RGB")
            return Raster(rgb.width, rgb.height, bytearray(rgb.tobytes()))
    except Exception as exc:  # a corrupt file is an error, not a verdict
        raise ProbeError("Pillow could not decode %s: %s" % (path, exc))


_PNG_CHANNELS = {0: 1, 2: 3, 3: 1, 4: 2, 6: 4}


def _paeth(a, b, c):
    p = a + b - c
    pa, pb, pc = abs(p - a), abs(p - b), abs(p - c)
    if pa <= pb and pa <= pc:
        return a
    if pb <= pc:
        return b
    return c


def _load_with_stdlib(path):
    """Minimal PNG reader: enough for anything Unity writes, nothing more."""
    with open(path, "rb") as fh:
        blob = fh.read()
    if blob[:8] != b"\x89PNG\r\n\x1a\n":
        raise ProbeError("not a PNG file: %s" % path)

    pos = 8
    header = None
    palette = None
    idat = []
    while pos + 8 <= len(blob):
        (length,) = struct.unpack(">I", blob[pos:pos + 4])
        kind = blob[pos + 4:pos + 8]
        body = blob[pos + 8:pos + 8 + length]
        pos += 12 + length
        if kind == b"IHDR":
            header = struct.unpack(">IIBBBBB", body)
        elif kind == b"PLTE":
            palette = body
        elif kind == b"IDAT":
            idat.append(body)
        elif kind == b"IEND":
            break
    if header is None:
        raise ProbeError("PNG has no IHDR chunk: %s" % path)

    width, height, depth, colour, compression, filt, interlace = header
    if interlace:
        raise ProbeError(
            "interlaced PNG needs Pillow to decode (%s); `pip install Pillow`" % path)
    if compression != 0 or filt != 0:
        raise ProbeError("unsupported PNG compression/filter in %s" % path)
    if depth not in (8, 16) or colour not in _PNG_CHANNELS:
        raise ProbeError("unsupported PNG bit depth %d / colour type %d in %s"
                         % (depth, colour, path))
    if colour == 3 and palette is None:
        raise ProbeError("palette PNG with no PLTE chunk: %s" % path)

    channels = _PNG_CHANNELS[colour]
    step = channels * (depth // 8)
    stride = width * step
    raw = zlib.decompress(b"".join(idat))
    if len(raw) < (stride + 1) * height:
        raise ProbeError("truncated PNG image data: %s" % path)

    # Un-filter, scanline by scanline, in place.
    lines = []
    prev = bytearray(stride)
    at = 0
    for _ in range(height):
        ftype = raw[at]
        line = bytearray(raw[at + 1:at + 1 + stride])
        at += 1 + stride
        if ftype == 1:
            for i in range(step, stride):
                line[i] = (line[i] + line[i - step]) & 0xFF
        elif ftype == 2:
            for i in range(stride):
                line[i] = (line[i] + prev[i]) & 0xFF
        elif ftype == 3:
            for i in range(stride):
                left = line[i - step] if i >= step else 0
                line[i] = (line[i] + ((left + prev[i]) >> 1)) & 0xFF
        elif ftype == 4:
            for i in range(stride):
                left = line[i - step] if i >= step else 0
                upleft = prev[i - step] if i >= step else 0
                line[i] = (line[i] + _paeth(left, prev[i], upleft)) & 0xFF
        elif ftype != 0:
            raise ProbeError("unknown PNG filter type %d in %s" % (ftype, path))
        lines.append(line)
        prev = line

    # Flatten to RGB. 16-bit keeps the high byte; alpha is dropped (captures are opaque).
    hi = 1 if depth == 16 else 0
    out = bytearray(width * height * 3)
    o = 0
    for line in lines:
        for x in range(width):
            base = x * step
            if colour == 3:
                idx = line[base] * 3
                out[o] = palette[idx]
                out[o + 1] = palette[idx + 1]
                out[o + 2] = palette[idx + 2]
            elif colour in (0, 4):
                g = line[base + hi]
                out[o] = out[o + 1] = out[o + 2] = g
            else:
                out[o] = line[base + hi]
                out[o + 1] = line[base + (depth // 8) + hi]
                out[o + 2] = line[base + 2 * (depth // 8) + hi]
            o += 3
    return Raster(width, height, out)


def load_raster(path):
    if not os.path.isfile(path):
        raise ProbeError("capture not found: %s" % path)
    raster = _load_with_pillow(path)
    if raster is None:
        raster = _load_with_stdlib(path)
    if raster.width == 0 or raster.height == 0:
        raise ProbeError("capture has zero extent: %s" % path)
    return raster


# --- colour -----------------------------------------------------------------------------------


def parse_hex(text):
    s = str(text).strip().lstrip("#")
    if len(s) == 3:
        s = "".join(c * 2 for c in s)
    if len(s) == 8:  # #RRGGBBAA — alpha is not a thing a probe can read back
        s = s[:6]
    if len(s) != 6 or re.search(r"[^0-9a-fA-F]", s):
        raise ProbeError("not a hex colour: %r" % (text,))
    return int(s[0:2], 16), int(s[2:4], 16), int(s[4:6], 16)


def hex_of(rgb):
    return "#%02X%02X%02X" % (int(round(rgb[0])), int(round(rgb[1])), int(round(rgb[2])))


def _srgb_to_linear(c):
    c = c / 255.0
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


_D65 = (0.95047, 1.00000, 1.08883)


def linear_to_lab(r, g, b):
    """Linear-light sRGB -> CIELAB (D65). Linear in, because a sampled patch is averaged in
    linear light — averaging gamma-encoded bytes biases a gradient towards its dark end."""
    x = 0.4124564 * r + 0.3575761 * g + 0.1804375 * b
    y = 0.2126729 * r + 0.7151522 * g + 0.0721750 * b
    z = 0.0193339 * r + 0.1191920 * g + 0.9503041 * b

    def f(t):
        t = t if t > 0.0 else 0.0
        return t ** (1.0 / 3.0) if t > 216.0 / 24389.0 else (841.0 / 108.0) * t + 4.0 / 29.0

    fx, fy, fz = f(x / _D65[0]), f(y / _D65[1]), f(z / _D65[2])
    return 116.0 * fy - 16.0, 500.0 * (fx - fy), 200.0 * (fy - fz)


def srgb_bytes_to_lab(rgb):
    return linear_to_lab(*[_srgb_to_linear(c) for c in rgb])


def delta_e76(lab_a, lab_b):
    return ((lab_a[0] - lab_b[0]) ** 2
            + (lab_a[1] - lab_b[1]) ** 2
            + (lab_a[2] - lab_b[2]) ** 2) ** 0.5


# --- the flat-capture check -------------------------------------------------------------------


def luma_variance(raster):
    """Population variance of integer Rec.601 luma over a deterministic subsample.

    Same algorithm on both decoder paths on purpose: `visual-judge.sh`'s HALT rule compares one
    run's reading against the previous run's, so the number has to mean the same thing twice."""
    total = raster.width * raster.height
    stride = 1
    while total // stride > VARIANCE_SAMPLE_CAP:
        stride += 1
    data = raster.data
    n = 0
    acc = 0
    acc_sq = 0
    for i in range(0, total, stride):
        j = i * 3
        y = (299 * data[j] + 587 * data[j + 1] + 114 * data[j + 2]) // 1000
        acc += y
        acc_sq += y * y
        n += 1
    if n == 0:
        raise ProbeError("no pixels sampled")
    mean = acc / float(n)
    return max(0.0, acc_sq / float(n) - mean * mean), n, stride


def check_variance(raster, path, minimum):
    variance, sampled, stride = luma_variance(raster)
    flat = variance < minimum
    if flat:
        warn("BROKEN CAPTURE: %s is very nearly one flat colour "
             "(luma variance %.4f < %.4f, %d px sampled at stride %d)."
             % (path, variance, minimum, sampled, stride))
        warn("This is a capture-pipeline fault, not a UI fault — nothing was drawn into the "
             "frame. Do not read any verdict below it.")
    return variance, flat


# --- points file ------------------------------------------------------------------------------


_ANCHORS = {
    "center": (0.5, 0.5),
    "top-left": (0.0, 0.0),
    "top-center": (0.5, 0.0),
    "top-right": (1.0, 0.0),
    "left-center": (0.0, 0.5),
    "right-center": (1.0, 0.5),
    "bottom-left": (0.0, 1.0),
    "bottom-center": (0.5, 1.0),
    "bottom-right": (1.0, 1.0),
}


def read_json(path, what):
    if not os.path.isfile(path):
        raise ProbeError("%s not found: %s" % (what, path))
    try:
        with open(path, "r") as fh:
            return json.load(fh)
    except ValueError as exc:
        raise ProbeError("%s is not valid JSON (%s): %s" % (what, exc, path))


def sample_patch(raster, cx, cy, window):
    """Mean colour of a window x window box, averaged in LINEAR light, clamped to the frame."""
    half = max(0, window // 2)
    x0, x1 = max(0, cx - half), min(raster.width - 1, cx + half)
    y0, y1 = max(0, cy - half), min(raster.height - 1, cy + half)
    lin = [0.0, 0.0, 0.0]
    srgb = [0, 0, 0]
    n = 0
    for y in range(y0, y1 + 1):
        for x in range(x0, x1 + 1):
            px = raster.rgb(x, y)
            for c in range(3):
                lin[c] += _srgb_to_linear(px[c])
                srgb[c] += px[c]
            n += 1
    lin = [v / n for v in lin]
    srgb = [v / float(n) for v in srgb]
    return lin, srgb


def run_probes(raster, spec, capture_path, window_override, verbose):
    space = spec.get("space") or {}
    design_w = int(space.get("width", DEFAULT_SPACE[0]))
    design_h = int(space.get("height", DEFAULT_SPACE[1]))
    origin = space.get("origin", "top-left")
    if origin not in ("top-left", "bottom-left"):
        raise ProbeError("space.origin must be 'top-left' or 'bottom-left', got %r" % origin)
    if design_w <= 0 or design_h <= 0:
        raise ProbeError("space.width/height must be positive")

    defaults = spec.get("defaults") or {}
    def_tol = float(defaults.get("tolerance", DEFAULT_TOLERANCE))
    def_win = int(defaults.get("window", DEFAULT_WINDOW))

    points = spec.get("points")
    if not isinstance(points, list) or not points:
        raise ProbeError("points file declares no `points` array")

    sx = raster.width / float(design_w)
    sy = raster.height / float(design_h)
    if verbose:
        warn("design space %dx%d (%s origin) -> capture %dx%d, scale %.4f x %.4f"
             % (design_w, design_h, origin, raster.width, raster.height, sx, sy))

    failures = 0
    for index, point in enumerate(points):
        label = point.get("label") or "point %d" % (index + 1)
        try:
            dx = float(point["x"])
            dy = float(point["y"])
            expect = parse_hex(point["expect"])
        except KeyError as exc:
            raise ProbeError("point %r is missing %s" % (label, exc))
        tol = float(point.get("tolerance", def_tol))
        win = int(window_override if window_override else point.get("window", def_win))

        if origin == "bottom-left":
            dy = design_h - 1 - dy
        px = int(round(dx * sx))
        py = int(round(dy * sy))
        if not (0 <= px < raster.width and 0 <= py < raster.height):
            print("FAIL | %-52s | (%d,%d) falls outside the %dx%d capture"
                  % (label, px, py, raster.width, raster.height))
            failures += 1
            continue

        lin, srgb = sample_patch(raster, px, py, win)
        got_lab = linear_to_lab(*lin)
        want_lab = srgb_bytes_to_lab(expect)
        de = delta_e76(got_lab, want_lab)
        rgb_gap = max(abs(srgb[c] - expect[c]) for c in range(3))
        ok = de <= tol
        failures += 0 if ok else 1
        token = point.get("token")
        print("%s | %-52s | got %s want %s%s | dE76 %6.2f (tol %5.2f) | max RGB gap %5.1f | @(%d,%d) %dpx box"
              % ("PASS" if ok else "FAIL",
                 label,
                 hex_of(srgb),
                 hex_of(expect),
                 (" [%s]" % token) if token else "",
                 de, tol, rgb_gap, px, py, win))
        if verbose and point.get("from"):
            warn("    %s: %s" % (label, point["from"]))

    print("[%s] %s capture=%s points=%d failed=%d"
          % (TOOL, "DRIFT" if failures else "Ok", capture_path, len(points), failures))
    return EXIT_DRIFT if failures else EXIT_OK


# --- the generator ----------------------------------------------------------------------------
#
# Every visual constant in a SKU lives in its own `Assets/<sku>/Views/DesignTokens.cs`, and the
# field assertions already know each element's rect. So a sample point should be DERIVED from
# (rect, colour token), never typed: type a coordinate and the probe file silently rots the first
# time a token moves. The layout schema below is that derivation, written down.


_TOKEN_RE = re.compile(
    r"public\s+const\s+(?:int|float|double|string)\s+(\w+)\s*=\s*([^;]+);")


def load_design_tokens(path):
    if not os.path.isfile(path):
        raise ProbeError("tokenSource not found: %s" % path)
    with open(path, "r") as fh:
        source = fh.read()
    raw = {}
    for name, value in _TOKEN_RE.findall(source):
        raw[name] = value.strip()

    resolved = {}

    def resolve(name, seen):
        if name in resolved:
            return resolved[name]
        if name in seen:
            raise ProbeError("design token %s is defined circularly" % name)
        seen.add(name)
        value = raw[name]
        if value.startswith('"'):
            out = value.strip('"')
        elif re.match(r"^-?\d+(\.\d+)?[fdFD]?$", value):
            out = float(value.rstrip("fdFD")) if ("." in value) else int(value)
        elif value in raw:
            out = resolve(value, seen)
        else:
            raise ProbeError("cannot resolve design token %s = %s" % (name, value))
        resolved[name] = out
        return out

    for name in list(raw):
        resolve(name, set())
    return resolved


_ALLOWED_BINOPS = (ast.Add, ast.Sub, ast.Mult, ast.Div, ast.FloorDiv, ast.Mod, ast.Pow)


def evaluate(expression, symbols):
    """Arithmetic over design tokens. Deliberately not `eval`: names come from the token table
    and nothing else, and no call, attribute or subscript is reachable."""
    if isinstance(expression, (int, float)):
        return expression
    try:
        tree = ast.parse(str(expression), mode="eval")
    except SyntaxError as exc:
        raise ProbeError("cannot parse expression %r (%s)" % (expression, exc))

    def walk(node):
        if isinstance(node, ast.Expression):
            return walk(node.body)
        if isinstance(node, ast.Constant) and isinstance(node.value, (int, float)):
            return node.value
        if isinstance(node, ast.Name):
            if node.id not in symbols:
                raise ProbeError("unknown design token %r in expression %r"
                                 % (node.id, expression))
            value = symbols[node.id]
            if not isinstance(value, (int, float)):
                raise ProbeError("design token %s is not numeric (%r)" % (node.id, value))
            return value
        if isinstance(node, ast.UnaryOp) and isinstance(node.op, (ast.UAdd, ast.USub)):
            value = walk(node.operand)
            return value if isinstance(node.op, ast.UAdd) else -value
        if isinstance(node, ast.BinOp) and isinstance(node.op, _ALLOWED_BINOPS):
            left, right = walk(node.left), walk(node.right)
            op = node.op
            if isinstance(op, ast.Add):
                return left + right
            if isinstance(op, ast.Sub):
                return left - right
            if isinstance(op, ast.Mult):
                return left * right
            if isinstance(op, ast.Div):
                return left / right
            if isinstance(op, ast.FloorDiv):
                return left // right
            if isinstance(op, ast.Mod):
                return left % right
            return left ** right
        raise ProbeError("expression %r uses a construct this evaluator refuses" % expression)

    return walk(tree)


def resolve_rects(layout, symbols):
    declared = layout.get("rects") or {}
    if not isinstance(declared, dict):
        raise ProbeError("layout `rects` must be an object")
    rects = {}

    def build(name, seen):
        if name in rects:
            return rects[name]
        if name in seen:
            raise ProbeError("rect %s is defined circularly" % name)
        seen.add(name)
        spec = declared.get(name)
        if spec is None:
            raise ProbeError("unknown rect %r" % name)
        if isinstance(spec, list):
            if len(spec) != 4:
                raise ProbeError("rect %s as a list must be [x, y, w, h]" % name)
            rect = [evaluate(v, symbols) for v in spec]
        elif isinstance(spec, dict):
            if "from" in spec:
                base = list(build(spec["from"], seen))
            else:
                base = [0.0, 0.0, 0.0, 0.0]
            for key, slot in (("x", 0), ("y", 1), ("w", 2), ("h", 3)):
                if key in spec:
                    base[slot] = evaluate(spec[key], symbols)
            if "size" in spec:
                base[2] = evaluate(spec["size"][0], symbols)
                base[3] = evaluate(spec["size"][1], symbols)
            if "offset" in spec:
                base[0] += evaluate(spec["offset"][0], symbols)
                base[1] += evaluate(spec["offset"][1], symbols)
            if "inset" in spec:
                pad = evaluate(spec["inset"], symbols)
                base = [base[0] + pad, base[1] + pad, base[2] - 2 * pad, base[3] - 2 * pad]
            rect = base
        else:
            raise ProbeError("rect %s must be a list or an object" % name)
        if rect[2] <= 0 or rect[3] <= 0:
            raise ProbeError("rect %s resolves to a non-positive extent %r" % (name, rect))
        rects[name] = rect
        return rect

    for name in declared:
        if name.startswith("_"):
            continue
        build(name, set())
    return rects


def generate_points(layout_path):
    layout = read_json(layout_path, "layout")
    symbols = {}
    token_source = layout.get("tokenSource")
    if token_source:
        if not os.path.isabs(token_source):
            token_source = os.path.join(repo_root(), token_source)
        symbols.update(load_design_tokens(token_source))
    for name, value in (layout.get("consts") or {}).items():
        if name.startswith("_"):  # `_note` keys are prose for the reader, not symbols
            continue
        symbols[name] = evaluate(value, symbols) if isinstance(value, str) else value

    space = layout.get("space") or {}
    out_space = {
        "width": int(evaluate(space.get("width", DEFAULT_SPACE[0]), symbols)),
        "height": int(evaluate(space.get("height", DEFAULT_SPACE[1]), symbols)),
        "origin": space.get("origin", "top-left"),
    }

    rects = resolve_rects(layout, symbols)
    probes = layout.get("probes")
    if not isinstance(probes, list) or not probes:
        raise ProbeError("layout declares no `probes` array")

    points = []
    for index, probe in enumerate(probes):
        label = probe.get("label") or "probe %d" % (index + 1)
        rect_name = probe.get("rect")
        if rect_name not in rects:
            raise ProbeError("probe %r names unknown rect %r" % (label, rect_name))
        rect = list(rects[rect_name])
        if "inset" in probe:
            pad = evaluate(probe["inset"], symbols)
            rect = [rect[0] + pad, rect[1] + pad, rect[2] - 2 * pad, rect[3] - 2 * pad]
        anchor = probe.get("at", "center")
        if anchor not in _ANCHORS:
            raise ProbeError("probe %r uses unknown anchor %r (known: %s)"
                             % (label, anchor, ", ".join(sorted(_ANCHORS))))
        fx, fy = _ANCHORS[anchor]
        x = rect[0] + fx * (rect[2] - 1)
        y = rect[1] + fy * (rect[3] - 1)
        if "nudge" in probe:
            x += evaluate(probe["nudge"][0], symbols)
            y += evaluate(probe["nudge"][1], symbols)

        expect = probe.get("expect")
        if expect is None:
            raise ProbeError("probe %r declares no `expect`" % label)
        token = None
        if not str(expect).startswith("#"):
            if expect not in symbols:
                raise ProbeError("probe %r expects unknown design token %r" % (label, expect))
            token = "DesignTokens.%s" % expect
            expect = symbols[expect]

        point = {
            "label": label,
            "x": int(round(x)),
            "y": int(round(y)),
            "expect": hex_of(parse_hex(expect)),
            "from": "rect %s [%g %g %g %g] at %s"
                    % (rect_name, rect[0], rect[1], rect[2], rect[3], anchor),
        }
        if token:
            point["token"] = token
        if "tolerance" in probe:
            point["tolerance"] = probe["tolerance"]
        if "window" in probe:
            point["window"] = probe["window"]
        points.append(point)

    return {
        "$schema": "pixel-probe/v1",
        "generated": "machine-generated by Tools/pf/pixel-probe.py --generate %s — "
                     "edit the layout, never this file"
                     % os.path.relpath(layout_path, repo_root()),
        "surface": layout.get("surface", "unnamed"),
        "space": out_space,
        "variance": layout.get("variance", {"minLuma": DEFAULT_MIN_VARIANCE}),
        "defaults": layout.get("defaults", {"tolerance": DEFAULT_TOLERANCE,
                                            "window": DEFAULT_WINDOW}),
        "points": points,
    }


def repo_root():
    return os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# --- entry point ------------------------------------------------------------------------------


def main(argv):
    parser = argparse.ArgumentParser(
        add_help=True,
        description="Settle a capture's floor deterministically — no model, no quota. "
                    "Exit 0 Ok, 1 Drift, 2 Error. See the header of this file for the full "
                    "contract and for why the tolerance is a CIE76 dE.")
    parser.add_argument("--capture", help="the PNG to read")
    parser.add_argument("--points", help="sample-point declaration (schema pixel-probe/v1)")
    parser.add_argument("--variance-only", dest="variance_only", metavar="PNG",
                        help="print the luma variance and settle ONLY the broken-capture check")
    parser.add_argument("--min-variance", type=float, default=None,
                        help="flat-capture threshold (default: the points file, else %.1f)"
                             % DEFAULT_MIN_VARIANCE)
    parser.add_argument("--window", type=int, default=None,
                        help="override every probe's sample-box size, in design units")
    parser.add_argument("--generate", metavar="LAYOUT",
                        help="machine-generate a points file from a layout declaration "
                             "(schema pixel-probe-layout/v1)")
    parser.add_argument("--out", help="where --generate writes (default: stdout)")
    parser.add_argument("--verbose", action="store_true",
                        help="also report the design->capture scale and each point's provenance")
    args = parser.parse_args(argv)

    if args.generate:
        spec = generate_points(args.generate)
        text = json.dumps(spec, indent=2) + "\n"
        if args.out:
            with open(args.out, "w") as fh:
                fh.write(text)
            warn("wrote %d points to %s" % (len(spec["points"]), args.out))
        else:
            sys.stdout.write(text)
        return EXIT_OK

    if args.variance_only:
        raster = load_raster(args.variance_only)
        minimum = args.min_variance if args.min_variance is not None else DEFAULT_MIN_VARIANCE
        variance, flat = check_variance(raster, args.variance_only, minimum)
        print("%.4f" % variance)
        return EXIT_DRIFT if flat else EXIT_OK

    if not args.capture:
        raise ProbeError("give --capture, or --variance-only, or --generate")
    if not args.points:
        raise ProbeError("give --points <json> (or --variance-only for the flat-capture check)")

    spec = read_json(args.points, "points file")
    raster = load_raster(args.capture)

    minimum = args.min_variance
    if minimum is None:
        minimum = float((spec.get("variance") or {}).get("minLuma", DEFAULT_MIN_VARIANCE))
    variance, flat = check_variance(raster, args.capture, minimum)
    if flat:
        return EXIT_ERROR  # a broken capture is an ERROR, never a colour DRIFT
    if args.verbose:
        warn("luma variance %.4f (>= %.4f) — capture carries real content" % (variance, minimum))

    return run_probes(raster, spec, args.capture, args.window, args.verbose)


if __name__ == "__main__":
    try:
        sys.exit(main(sys.argv[1:]))
    except ProbeError as error:
        sys.stderr.write("[%s] ERROR: %s\n" % (TOOL, error))
        sys.exit(EXIT_ERROR)
    except KeyboardInterrupt:
        sys.exit(EXIT_ERROR)
