#!/usr/bin/env python3
# GENERATED by PrototypeFramework 0.4.2 from Documentation~/agent/tools/preflight-index.py — do not edit here. Change it in the framework repo, then run Framework/Agent Docs/Sync (editor) or Tools/Build/pf-build.sh agentdocs.
# /// script
# requires-python = ">=3.9"
# dependencies = ["pyyaml"]
# ///
"""preflight-index — index the intent a bmad-loop is about to implement, for a story preflight.

The mechanical half of the `pf-story-preflight` skill (procedure: the skill and
`docs/framework/recipes/story-preflight-checks.md`). Deterministic scaffolding only: it parses the
intent contract the loop hands each dev session, joins every unit's status and any existing spec,
and raises heuristic flags that tell the auditor where to look. It never decides that something is a
finding — a flag is a place to read, not a verdict.

Intent sources, auto-detected in this order (force one with --source):
  stories  `.bmad-loop/policy.toml` [stories] source = "stories" (or --spec-folder holding a
           stories.yaml): SPEC.md + companions + stories.yaml; story specs in <folder>/stories/.
  epics    {planning_artifacts}/epics.md (sprint mode): `### Story X.Y` blocks, sprint-status.yaml,
           story specs `spec-X-Y-*.md` in {implementation_artifacts}.
  spec     the one spec folder whose SPEC.md has no stories.yaml yet: every CAP-n is a unit.

Usage (from the repo root):
  python3 Tools/pf/preflight-index.py [--source auto|epics|stories|spec] [--epics P]
          [--spec-folder P] [--scope SCOPE] [--format md|json] [--out FILE]

SCOPE: remaining (default: every unit not `done`) | all | epic:2,5 (epics) | story:2.4,9.1 (epics)
       | story:1,3 (stories) | cap:1,4 (stories: the stories naming those CAPs; spec: those CAPs)
Exit codes: 0 ok · 2 error (no intent source, missing file, bad scope).
PyYAML reads stories.yaml when installed; a reader for its documented schema is the fallback.
"""
import argparse
import glob
import json
import os
import re
import subprocess
import sys

# ── Heuristic triggers, applied to acceptance criteria, CAP success lines and notes ────────────────
N = r"(?<![\d./])\d+(?:[.,]\d+)*"
NUMERIC = re.compile(
    r"(within ±? ?" + N + r"(?: ?%| ?°)?|within ±|[≤≥<>] ?" + N + r"|at (?:most|least) " + N + r"|"
    + N + r" ?ms\b|" + N + r" ?s\b|" + N + r" ?%|"
    + N + r" (?:steps|moves|levels|times|runs|seeds|walks|attempts|expansions|candidates|frames|iterations))",
    re.I,
)
RANDOM = re.compile(r"(random|seed|Pcg32|walk|jitter|noise|shuffle|sampled)", re.I)
VAGUE = re.compile(
    r"\b(realistic|typical|reasonable|appropriate|approximately|about|roughly|some|several|"
    r"smooth(ly)?|feels?|quickly|fast|slow|similar|natural(ly)?|looks? like|as needed|etc\.?)\b",
    re.I,
)
BLOCKIF = re.compile(
    r"(PlayMode|batchmode|pf-build\.sh|\bCI\b|on device|real phone|on (?:a )?(?:real )?(?:device|phone|hardware)|"
    r"by eye|manual(?:ly)? (?:QA|test|check|pass)|store account|asmdef|asmref|RenderLayer|"
    r"boot node|IBootNode|new event|migrator|Packages/|PackageCache|sprint-status)",
    re.I,
)
PATH = re.compile(r"`([A-Za-z0-9_.{}<>*-]+/[A-Za-z0-9_./{}<>*-]+\.[A-Za-z0-9]+)`")
IDENT = re.compile(r"`([A-Z][A-Za-z0-9_]+)(?:[.(`<])")
GIVEN = re.compile(r"^\s*(?:[-*]\s+|\d+[.)]\s+)?\*\*Given\*\*", re.I)
BOLD_LINE = re.compile(r"^\*\*(?!(?:Given|When|Then|And|But)\*\*)")
LABEL = re.compile(r"\*\*([A-Z][A-Za-z0-9 &/'()-]{0,48}?):\*\*")
TABLE_FIELD = re.compile(r"^\|\s*\*\*([^*|]+?)\*\*\s*\|\s*(.*?)\s*\|?\s*$")
CAP_REF = re.compile(r"\bCAP-(\d+)\b")

ORIGIN_LABEL = {
    "notes": "named outside this story's ACs — likely produced here",
    "earlier story": "named by an earlier story",
    "unowned": "⚠ consumed here, no earlier story names it",
}


def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def flags_in(text):
    hits = {
        "numeric": sorted({m.group(0) for m in NUMERIC.finditer(text)}),
        "random": sorted({m.group(0).lower() for m in RANDOM.finditer(text)}),
        "vague": sorted({m.group(0).lower() for m in VAGUE.finditer(text)}),
        "block_if": sorted({m.group(0) for m in BLOCKIF.finditer(text)}),
    }
    return {k: v for k, v in hits.items() if v}


def line_index(text):
    offsets, pos = [], 0
    for ln in text.splitlines(keepends=True):
        offsets.append(pos)
        pos += len(ln)

    def line_of(index):
        lo, hi = 0, max(len(offsets) - 1, 0)
        while lo < hi:
            mid = (lo + hi + 1) // 2
            if offsets[mid] <= index:
                lo = mid
            else:
                hi = mid - 1
        return lo + 1

    return line_of


def git(*args):
    try:
        out = subprocess.run(["git"] + list(args), capture_output=True, text=True, timeout=20)
        return out.stdout.strip() if out.returncode == 0 else ""
    except (OSError, subprocess.SubprocessError):
        return ""


# ── Project configuration ─────────────────────────────────────────────────────────────────────────

def bmad_config():
    """BMAD's own paths and languages: core config, then the bmm module's (which wins)."""
    cfg = {}
    for p in ("_bmad/core/config.yaml", "_bmad/bmm/config.yaml"):
        if os.path.exists(p):
            for m in re.finditer(r'^([A-Za-z_]+):\s*["\']?([^"\'\n#]*?)["\']?\s*(?:#.*)?$', read(p), re.M):
                if m.group(2).strip():
                    cfg[m.group(1)] = m.group(2).strip()

    def path(key, default):
        value = cfg.get(key) or default
        value = value.replace("{project-root}/", "").replace("{project-root}", ".")
        return os.path.normpath(value)

    return {
        "planning": path("planning_artifacts", "_bmad-output/planning-artifacts"),
        "impl": path("implementation_artifacts", "_bmad-output/implementation-artifacts"),
        "output": path("output_folder", "_bmad-output"),
        "communication_language": cfg.get("communication_language", ""),
        "document_output_language": cfg.get("document_output_language", "English"),
    }


def loop_policy():
    """The bmad-loop story-queue selection, or None when the loop is not installed here."""
    p = os.path.join(".bmad-loop", "policy.toml")
    if not os.path.exists(p):
        return None
    text = read(p)
    try:
        import tomllib  # Python 3.11+
        stories = tomllib.loads(text).get("stories", {}) or {}
        return {"source": stories.get("source", "sprint-status"), "spec_folder": stories.get("spec_folder", "")}
    except Exception:  # older Python, or a file tomllib rejects: read the two keys directly
        m = re.search(r"^\[stories\](.*?)(?=^\[|\Z)", text, re.M | re.S)
        sect = m.group(1) if m else ""
        src = re.search(r'^\s*source\s*=\s*"([^"]*)"', sect, re.M)
        folder = re.search(r'^\s*spec_folder\s*=\s*"([^"]*)"', sect, re.M)
        return {"source": src.group(1) if src else "sprint-status", "spec_folder": folder.group(1) if folder else ""}


def spec_folders(cfg):
    return sorted(os.path.dirname(p) for p in glob.glob(os.path.join(cfg["output"], "specs", "*", "SPEC.md")))


def project_map(cfg, policy, intent_files):
    """Where this SKU keeps what a story cites — discovered, never configured."""
    sku = ""
    for pattern in ("Assets/*/*FrameworkSettings.asset", "Assets/*/*/*FrameworkSettings.asset"):
        hits = sorted(glob.glob(pattern))
        if hits:
            sku = "Assets/" + hits[0].split("/")[1] + "/"
            break
    planning = cfg["planning"]
    spines = sorted(set(glob.glob(os.path.join(planning, "**", "ARCHITECTURE-SPINE.md"), recursive=True))
                    | set(glob.glob(os.path.join(planning, "architecture*.md"))))
    ux = sorted(p.rstrip("/") + "/" for p in glob.glob(os.path.join(planning, "ux-designs", "*", "")))
    specs = [s + "/" for s in spec_folders(cfg)]
    others = sorted(p for p in glob.glob(os.path.join(planning, "*.md"))
                    if os.path.basename(p) != "epics.md")
    tests = sorted(d + "/" for d in glob.glob("*HeadlessTests*") if os.path.isdir(d))
    preflight = os.path.join(planning, "preflight")
    reports = sorted(p for p in glob.glob(os.path.join(preflight, "preflight-*.md")))
    calibration = os.path.join(preflight, "calibration.md")
    head = git("rev-parse", "--short", "HEAD")
    dirty = [f for f in intent_files if f and git("status", "--porcelain", "--", f)]
    return {
        "sku_root": sku,
        "test_roots": tests,
        "framework_api_index": "docs/framework/framework-api.index.json"
        if os.path.exists("docs/framework/framework-api.index.json") else "",
        "architecture": spines,
        "ux_packages": ux,
        "spec_folders": specs,
        "other_planning_docs": others,
        "loop": policy,
        "languages": {"talk": cfg["communication_language"], "write": cfg["document_output_language"]},
        "prior_reports": reports,
        "sku_calibration": calibration if os.path.exists(calibration) else "",
        "git_head": head,
        "dirty_intent_files": dirty,
        # Roots a story-relative path may be written against (mockups/ is relative to a UX package).
        "path_roots": [""] + ([sku] if sku else []) + ux + specs,
    }


def missing_paths(text, roots, own_text, earlier_text):
    out = []
    for p in sorted({m.group(1) for m in PATH.finditer(text)}):
        if any(c in p for c in "{}<>*"):
            continue
        if any(os.path.exists(root + p) for root in roots):
            continue
        name = os.path.basename(p)
        if own_text is not None and name in own_text:
            origin = "notes"                 # named outside this story's ACs (usually produced here)
        elif name in earlier_text:
            origin = "earlier story"         # an earlier unit names it, so it should exist by now
        else:
            origin = "unowned"               # consumed here, nothing earlier creates it
        out.append({"path": p, "origin": origin})
    return out


def doc_status(path):
    m = re.search(r"^status:\s*['\"]?([\w-]+)", read(path), re.M | re.I)
    return m.group(1) if m else "?"


# ── Epics mode (sprint-status) ────────────────────────────────────────────────────────────────────

def norm(label):
    return re.sub(r"\s+", " ", label.strip().lower())


def fields(block):
    """`**Label:** value` (several may share a line, split at each label) and `| **Label** | value |`."""
    out = {}
    for line in block.splitlines():
        t = TABLE_FIELD.match(line)
        if t:
            out.setdefault(norm(t.group(1)), t.group(2).strip())
            continue
        marks = list(LABEL.finditer(line))
        for i, m in enumerate(marks):
            end = marks[i + 1].start() if i + 1 < len(marks) else len(line)
            out.setdefault(norm(m.group(1)), line[m.end():end].strip().rstrip("·").strip())
    return out


def ac_section(block):
    i = block.find("**Acceptance Criteria:**")
    if i < 0:
        return ""
    rest = block[i + len("**Acceptance Criteria:**"):]
    out = []
    for line in rest.splitlines():
        if BOLD_LINE.match(line) or re.match(r"^#{2,4} ", line):
            break
        out.append(line)
    return "\n".join(out).strip()


def split_acs(text):
    """One AC = a contiguous run of lines that opens with **Given**."""
    acs, cur = [], []
    for line in text.splitlines():
        s = line.strip()
        if not s:
            if cur:
                acs.append(cur)
                cur = []
            continue
        if GIVEN.match(line):
            if cur:
                acs.append(cur)
            cur = [s]
        elif cur:
            cur.append(s)
    if cur:
        acs.append(cur)
    return [" ".join(a) for a in acs]


def claims_section(block):
    """The non-AC text below the ACs — a Render Floor or Visual Contract the session must also satisfy."""
    i = block.find("**Acceptance Criteria:**")
    if i < 0:
        return ""
    out, in_ac = [], False
    for line in block[i + len("**Acceptance Criteria:**"):].splitlines():
        if re.match(r"^\*\*(Out of scope|Self-check|Preflight)", line, re.I) or re.match(r"^#{2,4} ", line):
            break
        if GIVEN.match(line):
            in_ac = True
        elif not line.strip():
            in_ac = False
        elif not in_ac:
            out.append(line)
    return "\n".join(out).strip()


def notes_section(block):
    m = re.search(r"^\*\*Implementation notes", block, re.M | re.I)
    if not m:
        return ""
    rest = block[m.start():]
    j = rest.find("**Acceptance Criteria:**")
    return rest[:j if j >= 0 else len(rest)].strip()


def sprint_status(path):
    status = {}
    if path and os.path.exists(path):
        for m in re.finditer(r"^\s+['\"]?(\d+)-(\d+)-[\w-]+['\"]?:\s*['\"]?([\w-]+)", read(path), re.M):
            status[f"{m.group(1)}.{m.group(2)}"] = m.group(3)
    return status


def spec_for(impl, story_id):
    major, minor = story_id.split(".")
    if not os.path.isdir(impl):
        return None, None
    names = sorted(os.listdir(impl))
    for prefix in (f"spec-{major}-{minor}-", f"{major}-{minor}-"):
        for name in names:
            if name.startswith(prefix) and name.endswith(".md"):
                path = os.path.join(impl, name)
                return path, doc_status(path)
    return None, None


def story_key(sid):
    return tuple(int(x) for x in sid.split("."))


def parse_epics(text):
    line_of = line_index(text)
    headings = [(m.start(), m.group(1).strip()) for m in re.finditer(r"^## (.+)$", text, re.M)]
    sections = []
    for i, (start, title) in enumerate(headings):
        end = headings[i + 1][0] if i + 1 < len(headings) else len(text)
        sections.append({"title": title, "start": start, "end": end,
                         "line_start": line_of(start), "line_end": line_of(max(end - 1, start))})

    epics = {}
    for m in re.finditer(r"^## Epic (\d+):(.*)$", text, re.M):
        nxt = re.search(r"^### Story |^## ", text[m.end():], re.M)
        shared_end = m.end() + (nxt.start() if nxt else 0)
        epics[m.group(1)] = {"title": m.group(2).strip(), "line": line_of(m.start()),
                             "shared_rules_lines": [line_of(m.end()) + 1, line_of(max(shared_end - 1, m.end()))],
                             "shared_rules": text[m.end():shared_end].strip()}

    # Decision / assumption rows a story may cite by id (`| D34 | …` or `- **D34** …`).
    decisions = {}
    for sec in sections:
        if re.match(r"Epic \d+:", sec["title"]) or not re.search(r"decision|assumption", sec["title"], re.I):
            continue
        body = text[sec["start"]:sec["end"]]
        for m in re.finditer(r"^(?:\|\s*|\s*[-*]\s+)\**([A-Z][A-Za-z]{0,3}-?\d{1,4})\b", body, re.M):
            decisions.setdefault(m.group(1), line_of(sec["start"] + m.start()))

    heads = list(re.finditer(r"^###\s+Story\s+(\d+)\.(\d+)\s*[:.—–-]?\s*(.*)$", text, re.M))
    stories = []
    for i, h in enumerate(heads):
        end = heads[i + 1].start() if i + 1 < len(heads) else len(text)
        tail = re.search(r"^## ", text[h.end():end], re.M)
        if tail:
            end = h.end() + tail.start()
        block = text[h.start():end]
        f = fields(block)
        dep_text = f.get("depends on", "")
        freezes = f.get("freezes for later stories") or f.get("freezes") or ""
        context = f.get("context to load", "")
        self_check = f.get("self-check", "")
        um = re.search(r"unknown\s*=\s*([^·]*)", self_check)
        unknown = um.group(1).strip() if um else (f.get("single unknown") or f.get("unknown") or "")
        acs_text = ac_section(block)
        acs = split_acs(acs_text) if acs_text else split_acs(block)
        stories.append({
            "id": f"{h.group(1)}.{h.group(2)}",
            "epic": h.group(1),
            "title": h.group(3).strip(),
            "line_start": line_of(h.start()),
            "line_end": line_of(end - 1),
            "kind": f.get("kind") or "?",
            "depends_on": sorted(set(re.findall(r"\b(\d+\.\d+)\b", dep_text)), key=story_key),
            "depends_on_text": dep_text,
            "freezes": freezes,
            "context_to_load": context,
            "self_check_unknown": unknown,
            "decisions_cited": sorted(d for d in decisions
                                      if re.search(r"(?<![\w-])" + re.escape(d) + r"(?![\w-])", block)),
            "acs": acs,
            "claims": claims_section(block),
            "notes": notes_section(block),
            # Everything but the ACs and the context line: paths named here are usually produced by this story.
            "own": block.replace(acs_text, "").replace(context, "") if acs_text else block.replace(context, ""),
            "block": block,
        })
    shared = [{k: v for k, v in s.items() if k not in ("start", "end")} for s in sections
              if not re.match(r"Epic \d+:", s["title"])]
    for s in shared:
        if re.search(r"decision|assumption", s["title"], re.I):
            s["decision_ids"] = sum(1 for line in decisions.values() if s["line_start"] <= line <= s["line_end"])
    return epics, stories, shared, decisions


def epics_rows(stories, status, impl, roots):
    order = [s["id"] for s in stories]
    rows = []
    for s in stories:
        flags = []
        for n, ac in enumerate(s["acs"], 1):
            hits = flags_in(ac)
            if hits:
                flags.append({"where": f"AC {n}", "hits": hits})
        # A floor or contract row is judged, not read: its vague words are expected, its numbers are not.
        hits = {k: v for k, v in flags_in(s["claims"]).items() if k != "vague"}
        if hits:
            flags.append({"where": "Render Floor / Visual Contract", "hits": hits})
        nb = sorted({m.group(0) for m in BLOCKIF.finditer(s["notes"])})
        if nb:
            flags.append({"where": "notes", "hits": {"block_if": nb}})
        earlier = "\n".join(x["block"] for x in stories if story_key(x["id"]) < story_key(s["id"]))
        frozen = {m.group(1) for m in IDENT.finditer("`" + s["freezes"].replace("`", "``") + "`")} | set(
            re.findall(r"`([A-Z][A-Za-z0-9_]+)`", s["freezes"]))
        related = []
        if frozen:
            for o in stories:
                if o["id"] == s["id"]:
                    continue
                shared = sorted(t for t in frozen if re.search(r"\b" + re.escape(t) + r"\b", o["block"]))
                if shared:
                    related.append({"story": o["id"], "shares": shared})
        spec, spec_status = spec_for(impl, s["id"])
        rows.append({
            "unit": s,
            "status": status.get(s["id"], "?"),
            "spec": spec,
            "spec_status": spec_status,
            "flags": flags,
            "depends_on_status": {d: status.get(d, "?") for d in s["depends_on"]},
            "depends_on_later_story": [d for d in s["depends_on"]
                                       if d in order and order.index(d) > order.index(s["id"])],
            "depends_on_unknown_story": [d for d in s["depends_on"] if d not in order],
            "paths": missing_paths(s["block"], roots, s["own"], earlier),
            "related_by_frozen_contract": related,
        })
    return rows


def select_epics(rows, scope):
    if scope == "all":
        return rows
    if scope == "remaining":
        return [r for r in rows if r["status"] != "done"]
    m = re.fullmatch(r"(epic|story):([\d.,]+)", scope)
    if not m:
        raise ValueError(f"bad scope for epics: {scope} (remaining | all | epic:2,5 | story:2.4,9.1)")
    wanted = set(m.group(2).split(","))
    key = "epic" if m.group(1) == "epic" else "id"
    return [r for r in rows if r["unit"][key] in wanted]


# ── Spec / stories mode (bmad-spec) ───────────────────────────────────────────────────────────────

def parse_spec(folder):
    path = os.path.join(folder, "SPEC.md")
    text = read(path)
    line_of = line_index(text)
    companions = []
    fm = re.match(r"^---\n(.*?)\n---", text, re.S)
    m = re.search(r"^companions:[ \t]*(.*)$", fm.group(1), re.M) if fm else None
    if m:
        inline = m.group(1).split("#")[0].strip()
        if inline.startswith("["):
            companions = [c.strip().strip("'\"") for c in inline.strip("[]").split(",") if c.strip()]
        else:
            for ln in fm.group(1)[m.end():].splitlines():
                item = re.match(r"^\s+-\s*(.+?)\s*$", ln)
                if item:
                    companions.append(item.group(1).strip("'\""))
                elif ln.strip() and not ln[0].isspace():
                    break
    headings = [(m.start(), m.group(1).strip()) for m in re.finditer(r"^## (.+)$", text, re.M)]
    sections = {}
    for i, (start, title) in enumerate(headings):
        end = headings[i + 1][0] if i + 1 < len(headings) else len(text)
        sections[norm(title)] = {"title": title, "start": start, "end": end,
                                 "line_start": line_of(start), "line_end": line_of(max(end - 1, start))}
    caps = []
    sec = sections.get("capabilities")
    if sec:
        body = text[sec["start"]:sec["end"]]
        heads = list(re.finditer(r"^- \*\*(CAP-\d+)\*\*(.*)$", body, re.M))
        for i, h in enumerate(heads):
            end = heads[i + 1].start() if i + 1 < len(heads) else len(body)
            cap = body[h.start():end].rstrip()

            def item(label):
                m = re.search(r"^\s*-\s*\*\*" + label + r":\*\*\s*(.*?)(?=^\s*-\s*\*\*|\Z)", cap, re.M | re.S | re.I)
                return " ".join(m.group(1).split()) if m else ""

            caps.append({"id": h.group(1), "title": h.group(2).strip(" —–-:"),
                         "line_start": line_of(sec["start"] + h.start()),
                         "line_end": line_of(sec["start"] + h.start() + len(cap) - 1),
                         "intent": item("intent"), "success": item("success"), "text": cap})
    lists = {}
    for key in ("constraints", "non-goals", "assumptions", "open questions"):
        s = sections.get(key)
        if s:
            body = text[s["start"]:s["end"]]
            lists[key] = [{"line": line_of(s["start"] + m.start()), "text": m.group(1).strip()}
                          for m in re.finditer(r"^-\s+(.+)$", body, re.M)]
    return {"path": path, "companions": companions, "caps": caps, "lists": lists,
            "sections": [{k: v for k, v in s.items() if k not in ("start", "end")} for s in sections.values()]}


def unquote(v):
    v = v.strip()
    if len(v) >= 2 and v[0] == v[-1] and v[0] in "'\"":
        return v[1:-1]
    return v


def read_stories_yaml(text):
    """The documented stories.yaml schema without PyYAML: a list of flat maps, block scalars allowed."""
    items, cur, key, style, block = [], None, None, None, []

    def flush():
        if cur is not None and key is not None:
            if style.startswith(">"):
                paras, para = [], []
                for ln in block:
                    if ln:
                        para.append(ln)
                    elif para:
                        paras.append(" ".join(para))
                        para = []
                if para:
                    paras.append(" ".join(para))
                cur[key] = "\n".join(paras)
            else:
                cur[key] = "\n".join(block).strip("\n")

    for raw in text.splitlines():
        if key is not None:
            if not raw.strip() or re.match(r"^\s{3,}\S", raw):
                block.append(raw.strip())
                continue
            flush()
            key, style, block = None, None, []
        if raw.lstrip().startswith("#"):
            continue
        m = re.match(r"^(-\s+|\s+)([A-Za-z_]+):\s*(.*?)\s*$", raw)
        if not m:
            continue
        if m.group(1).startswith("-"):
            cur = {}
            items.append(cur)
        if cur is None:
            continue
        value = m.group(3)
        if re.fullmatch(r"[>|][+-]?", value):
            key, style, block = m.group(2), value, []
        elif value.lower() in ("true", "false"):
            cur[m.group(2)] = value.lower() == "true"
        else:
            cur[m.group(2)] = unquote(value)
    flush()
    return items


def load_stories(folder):
    path = os.path.join(folder, "stories.yaml")
    text = read(path)
    try:
        import yaml
        data = yaml.safe_load(text) or []
    except ImportError:
        data = read_stories_yaml(text)
    lines = [i + 1 for i, ln in enumerate(text.splitlines()) if re.match(r"^-\s", ln)]
    entries = []
    for i, e in enumerate(d for d in data if isinstance(d, dict)):
        entry = {k: ("" if v is None else str(v) if not isinstance(v, bool) else v) for k, v in e.items()}
        entry["line"] = lines[i] if i < len(lines) else 0
        entries.append(entry)
    return path, entries


def story_spec(folder, sid):
    hits = sorted(glob.glob(os.path.join(folder, "stories", f"{sid}-*.md")))
    return (hits[0], doc_status(hits[0])) if hits else (None, None)


def stories_rows(spec, entries, folder, roots):
    caps = {c["id"]: c for c in spec["caps"]}
    rows, earlier = [], ""
    refs_by_story = {}
    for e in entries:
        text = " ".join(str(e.get(k, "")) for k in ("title", "description", "invoke_dev_with"))
        refs_by_story[e["id"]] = sorted({"CAP-" + n for n in CAP_REF.findall(text)}, key=lambda c: int(c[4:]))
    for e in entries:
        refs = refs_by_story[e["id"]]
        flags = []
        for where in ("description", "invoke_dev_with"):
            hits = flags_in(str(e.get(where, "")))
            if hits:
                flags.append({"where": where, "hits": hits})
        for c in refs:
            if c in caps:
                hits = flags_in(caps[c]["success"])
                b = sorted({m.group(0) for m in BLOCKIF.finditer(caps[c]["text"])})
                if b:
                    hits["block_if"] = sorted(set(hits.get("block_if", [])) | set(b))
                if hits:
                    flags.append({"where": f"{c} success", "hits": hits})
        own = " ".join(str(e.get(k, "")) for k in ("title", "description", "invoke_dev_with"))
        cited = own + "\n" + "\n".join(caps[c]["text"] for c in refs if c in caps)
        path, status = story_spec(folder, e["id"])
        rows.append({
            "unit": {"id": e["id"], "title": e.get("title", ""), "line_start": e["line"],
                     "description": e.get("description", ""), "invoke_dev_with": e.get("invoke_dev_with", ""),
                     "spec_checkpoint": e.get("spec_checkpoint", False), "done_checkpoint": e.get("done_checkpoint", False),
                     "caps": refs},
            "status": status or "no spec yet",
            "spec": path,
            "spec_status": status,
            "flags": flags,
            "caps_unknown": [c for c in refs if c not in caps],
            "paths": missing_paths(cited, roots, None, earlier),
            "related_by_cap": [{"story": o, "shares": sorted(set(refs) & set(r))}
                               for o, r in refs_by_story.items() if o != e["id"] and set(refs) & set(r)],
        })
        earlier += "\n" + cited
    return rows


def spec_rows(spec, roots):
    rows, earlier = [], ""
    for c in spec["caps"]:
        flags = []
        hits = flags_in(c["success"])
        b = sorted({m.group(0) for m in BLOCKIF.finditer(c["text"])})
        if b:
            hits["block_if"] = sorted(set(hits.get("block_if", [])) | set(b))
        if hits:
            flags.append({"where": "success", "hits": hits})
        rows.append({"unit": {k: v for k, v in c.items() if k != "text"}, "status": "?", "spec": None,
                     "spec_status": None, "flags": flags,
                     "paths": missing_paths(c["text"], roots, None, earlier)})
        earlier += "\n" + c["text"]
    return rows


def select_spec(rows, scope, mode):
    if scope in ("all", "remaining"):
        return [r for r in rows if scope == "all" or r["status"] != "done"]
    m = re.fullmatch(r"(story|cap):([\w,-]+)", scope)
    if not m or (mode == "spec" and m.group(1) == "story"):
        raise ValueError(f"bad scope for {mode}: {scope} (remaining | all | "
                         + ("story:1,3 | cap:1,4)" if mode == "stories" else "cap:1,4)"))
    wanted = set(m.group(2).split(","))
    if m.group(1) == "story":
        return [r for r in rows if r["unit"]["id"] in wanted]
    caps = {"CAP-" + w for w in wanted}
    if mode == "spec":
        return [r for r in rows if r["unit"]["id"] in caps]
    return [r for r in rows if caps & set(r["unit"]["caps"])]


# ── Rendering ─────────────────────────────────────────────────────────────────────────────────────

def render_project(out, pm, source, intent):
    head = pm["git_head"] or "no git"
    state = "dirty" if pm["dirty_intent_files"] else "clean"
    out.append("## Project map")
    out.append(f"- intent source `{source}`: " + " · ".join(f"`{p}`" for p in intent) + f" at `{head}` ({state})")
    loop = pm["loop"]
    out.append("- loop: " + (f"`.bmad-loop/` story source `{loop['source']}`" + (
        f", spec folder `{loop['spec_folder']}`" if loop.get("spec_folder") else "")
        + " — run `bmad-loop status` before amending" if loop else "no `.bmad-loop/` here"))
    talk = pm["languages"]["talk"] or "the user's language"
    out.append(f"- languages: talk `{talk}` · write the report in `{pm['languages']['write']}`")
    code = [f"`{pm['sku_root']}`"] if pm["sku_root"] else []
    code += [f"tests `{t}`" for t in pm["test_roots"]]
    if pm["framework_api_index"]:
        code.append(f"framework types `{pm['framework_api_index']}`")
    out.append("- code: " + (" · ".join(code) or "—"))
    for label, key in (("architecture", "architecture"), ("UX packages", "ux_packages"),
                       ("spec folders", "spec_folders"), ("other planning docs", "other_planning_docs")):
        out.append(f"- {label}: " + (" · ".join(f"`{p}`" for p in pm[key]) or "—"))
    out.append("- prior preflight reports: " + (" · ".join(f"`{p}`" for p in pm["prior_reports"]) or "none"))
    out.append("- SKU calibration cases: " + (f"`{pm['sku_calibration']}`" if pm["sku_calibration"] else "none"))
    out.append("- paths resolved against: " + ", ".join(f"`{r or './'}`" for r in pm["path_roots"]))


def render_paths(out, paths):
    if paths:
        out.append("- referenced paths missing today:")
        for p in sorted(paths, key=lambda p: p["origin"] != "unowned"):
            out.append(f"  - `{p['path']}` ({ORIGIN_LABEL[p['origin']]})")


def render_flags(out, flags):
    for f in flags:
        parts = "; ".join(f"{k}: {', '.join(v)}" for k, v in f["hits"].items())
        out.append(f"  - {f['where']} → {parts}")


def render_epics(pm, intent, epics, shared, rows, sprint_path):
    out = [f"# Preflight index — {len(rows)} stories", "",
           "Flags are places to read, not findings. Line numbers refer to `" + intent + "`.", ""]
    render_project(out, pm, "epics", [intent])
    out.append("- sprint status: " + (f"`{sprint_path}`" if os.path.exists(sprint_path)
                                      else f"`{sprint_path}` not found — every story counts as remaining"))
    out.append("- shared sections: " + " · ".join(
        f"`{s['title']}` {s['line_start']}–{s['line_end']}"
        + (f" ({s['decision_ids']} decision ids)" if s.get("decision_ids") else "") for s in shared))
    out.append("- epics: " + " · ".join(
        f"{n} line {e['line']} (shared rules {e['shared_rules_lines'][0]}–{e['shared_rules_lines'][1]})"
        if e["shared_rules"] else f"{n} line {e['line']}" for n, e in epics.items()))
    out.append("")
    for r in rows:
        s = r["unit"]
        out.append(f"## {s['id']} — {s['title']}")
        out.append(f"- kind `{s['kind']}` · sprint `{r['status']}` · epics.md lines {s['line_start']}–{s['line_end']}"
                   + (f" · spec `{r['spec']}` (status `{r['spec_status']}`)" if r["spec"] else ""))
        out.append(f"- depends on: {s['depends_on_text'] or '—'}")
        if r["depends_on_status"]:
            out.append("  - status: " + ", ".join(f"{k} {v}" for k, v in r["depends_on_status"].items()))
        if r["depends_on_later_story"]:
            out.append(f"  - ⚠ depends on a story the loop reaches LATER: {', '.join(r['depends_on_later_story'])}")
        if r["depends_on_unknown_story"]:
            out.append(f"  - ⚠ depends on a story id not in epics.md: {', '.join(r['depends_on_unknown_story'])}")
        out.append(f"- freezes: {s['freezes'] or '—'}")
        out.append(f"- context to load: {s['context_to_load'] or '—'}")
        if s["decisions_cited"]:
            out.append(f"- decisions cited: {', '.join(s['decisions_cited'])}")
        out.append(f"- self-check unknown: {s['self_check_unknown'] or '—'}")
        out.append(f"- acceptance criteria: {len(s['acs'])}")
        render_flags(out, r["flags"])
        render_paths(out, r["paths"])
        if r["related_by_frozen_contract"]:
            out.append("- other stories touching this story's frozen contract: "
                       + ", ".join(f"{x['story']} ({', '.join(x['shares'])})" for x in r["related_by_frozen_contract"]))
        out.append("")
    return "\n".join(out)


def render_spec(pm, mode, spec, rows, intent, all_entries):
    noun = "stories" if mode == "stories" else "capabilities"
    out = [f"# Preflight index — {len(rows)} {noun}", "",
           "Flags are places to read, not findings. Line numbers refer to "
           + " and ".join(f"`{p}`" for p in intent) + ".", ""]
    render_project(out, pm, mode, intent)
    folder = os.path.dirname(spec["path"])
    missing = [c for c in spec["companions"] if not os.path.exists(os.path.normpath(os.path.join(folder, c)))]
    out.append(f"- companions: {len(spec['companions'])}" + (
        "; ⚠ missing: " + ", ".join(f"`{c}`" for c in missing) if missing else ", all present"))
    out.append("- SPEC sections: " + " · ".join(f"`{s['title']}` {s['line_start']}–{s['line_end']}"
                                                 for s in spec["sections"]))
    for key, label in (("open questions", "open questions (each is a decision nobody made yet)"),
                       ("assumptions", "assumptions (each was inferred, not confirmed)")):
        items = spec["lists"].get(key, [])
        if items:
            out.append(f"- {label}: " + ", ".join(f"line {i['line']}" for i in items))
    if mode == "stories":
        covered = {c for e in all_entries for c in e["unit"]["caps"]}
        orphans = [c["id"] for c in spec["caps"] if c["id"] not in covered]
        if orphans:
            out.append("- ⚠ CAPs no story names: " + ", ".join(orphans))
    out.append("")
    for r in rows:
        u = r["unit"]
        if mode == "stories":
            out.append(f"## {u['id']} — {u['title']}")
            out.append(f"- story spec: " + (f"`{r['spec']}` (status `{r['spec_status']}`)" if r["spec"] else "none yet")
                       + f" · stories.yaml line {u['line_start']}"
                       + (" · spec_checkpoint" if u["spec_checkpoint"] is True else "")
                       + (" · done_checkpoint" if u["done_checkpoint"] is True else ""))
            out.append(f"- description: {' '.join(str(u['description']).split()) or '—'}")
            if u["invoke_dev_with"]:
                out.append(f"- invoke_dev_with: {' '.join(str(u['invoke_dev_with']).split())}")
            caps = {c["id"]: c for c in spec["caps"]}
            out.append("- capabilities: " + (", ".join(
                f"{c} (SPEC.md {caps[c]['line_start']}–{caps[c]['line_end']})" for c in u["caps"] if c in caps) or
                "⚠ names no CAP — the session must map the description onto SPEC.md by itself"))
            if r["caps_unknown"]:
                out.append("  - ⚠ not in SPEC.md: " + ", ".join(r["caps_unknown"]))
            render_flags(out, r["flags"])
            render_paths(out, r["paths"])
            if r["related_by_cap"]:
                out.append("- other stories naming the same capability: "
                           + ", ".join(f"{x['story']} ({', '.join(x['shares'])})" for x in r["related_by_cap"]))
        else:
            out.append(f"## {u['id']} — {u['title'] or '(untitled)'}")
            out.append(f"- SPEC.md lines {u['line_start']}–{u['line_end']}")
            out.append(f"- intent: {u['intent'] or '—'}")
            out.append(f"- success: {u['success'] or '⚠ none — nothing decides when this is done'}")
            render_flags(out, r["flags"])
            render_paths(out, r["paths"])
        out.append("")
    return "\n".join(out)


# ── Entry point ───────────────────────────────────────────────────────────────────────────────────

def detect(args, cfg, policy):
    if args.source in ("stories", "spec") or (args.source == "auto" and args.spec_folder):
        folders = [args.spec_folder.rstrip("/")] if args.spec_folder else (
            [policy["spec_folder"].rstrip("/")] if policy and policy.get("spec_folder") else spec_folders(cfg))
        if len(folders) != 1:
            raise ValueError("name the spec folder with --spec-folder; found: "
                             + (", ".join(folders) or "no */SPEC.md under " + os.path.join(cfg["output"], "specs")))
        has_stories = os.path.exists(os.path.join(folders[0], "stories.yaml"))
        mode = args.source if args.source != "auto" else ("stories" if has_stories else "spec")
        if mode == "stories" and not has_stories:
            raise ValueError(f"{folders[0]}/stories.yaml not found — use --source spec until bmad-spec writes one")
        return mode, folders[0]
    epics = args.epics or os.path.join(cfg["planning"], "epics.md")
    if args.source == "epics":
        return "epics", epics
    if policy and policy.get("source") == "stories" and policy.get("spec_folder"):
        return "stories", policy["spec_folder"].rstrip("/")
    if os.path.exists(epics):
        return "epics", epics
    folders = spec_folders(cfg)
    if len(folders) == 1:
        return ("stories" if os.path.exists(os.path.join(folders[0], "stories.yaml")) else "spec"), folders[0]
    raise ValueError("no intent source: no " + epics + (", several spec folders (" + ", ".join(folders)
                     + ") — pick one with --spec-folder" if folders else ", no */SPEC.md"))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--source", choices=["auto", "epics", "stories", "spec"], default="auto")
    ap.add_argument("--epics", help="epics.md path (default: {planning_artifacts}/epics.md)")
    ap.add_argument("--spec-folder", help="a bmad-spec folder holding SPEC.md (and stories.yaml)")
    ap.add_argument("--scope", default="remaining")
    ap.add_argument("--format", choices=["md", "json"], default="md")
    ap.add_argument("--out")
    a = ap.parse_args()
    cfg = bmad_config()
    policy = loop_policy()
    try:
        mode, target = detect(a, cfg, policy)
    except ValueError as e:
        print(f"error: {e} — run from the repo root", file=sys.stderr)
        return 2
    try:
        if mode == "epics":
            if not os.path.exists(target):
                raise ValueError(f"{target} not found")
            sprint = os.path.join(cfg["impl"], "sprint-status.yaml")
            epics, stories, shared, decisions = parse_epics(read(target))
            if not stories:
                raise ValueError(f"{target} has no `### Story X.Y` heading")
            pm = project_map(cfg, policy, [target])
            rows = select_epics(epics_rows(stories, sprint_status(sprint), cfg["impl"], pm["path_roots"]), a.scope)
            if a.format == "json":
                for r in rows:
                    r["unit"] = {k: v for k, v in r["unit"].items() if k not in ("block", "own")}
                doc = {"source": mode, "intent": [target], "project": pm, "sprint_status": sprint,
                       "shared_sections": shared, "decisions": decisions,
                       "epics": {k: {kk: vv for kk, vv in v.items() if kk != "shared_rules"} for k, v in epics.items()},
                       "units": rows}
            else:
                text = render_epics(pm, target, epics, shared, rows, sprint)
        else:
            if not os.path.exists(os.path.join(target, "SPEC.md")):
                raise ValueError(f"{target}/SPEC.md not found")
            spec = parse_spec(target)
            if mode == "stories":
                story_path, entries = load_stories(target)
                intent = [story_path, spec["path"]]
                pm = project_map(cfg, policy, intent)
                all_rows = stories_rows(spec, entries, target, pm["path_roots"])
            else:
                if not spec["caps"]:
                    raise ValueError(f"{spec['path']} has no `- **CAP-n**` capability under `## Capabilities`")
                intent = [spec["path"]]
                pm = project_map(cfg, policy, intent)
                all_rows = spec_rows(spec, pm["path_roots"])
            rows = select_spec(all_rows, a.scope, mode)
            if a.format == "json":
                doc = {"source": mode, "intent": intent, "project": pm,
                       "spec": {k: v for k, v in spec.items() if k != "caps"},
                       "capabilities": [{k: v for k, v in c.items() if k != "text"} for c in spec["caps"]],
                       "units": rows}
            else:
                text = render_spec(pm, mode, spec, rows, intent, all_rows)
    except ValueError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    if a.format == "json":
        text = json.dumps(doc, ensure_ascii=False, indent=1)
    if a.out:
        os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)
        with open(a.out, "w", encoding="utf-8") as f:
            f.write(text + "\n")
        print(f"wrote {a.out} ({len(rows)} {'stories' if mode != 'spec' else 'capabilities'}, source {mode})")
    else:
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
