#!/bin/sh
# GENERATED by PrototypeFramework 0.4.2 from Documentation~/agent/tools/promote-reference.sh — do not edit here. Change it in the framework repo, then run Framework/Agent Docs/Sync (editor) or Tools/Build/pf-build.sh agentdocs.
# promote-reference.sh — store a judged capture as a surface's reference capture.
#
#   Tools/pf/promote-reference.sh <surface> <capture.png> [<capture.png>]...
#
# Synced from the framework, like visual-judge.sh. The data is the SKU's: UIGATE_ROOT (default
# Tools/UiGate, resolved from this script's location) holds captures/ and references/.
#
# Every Epic 8 story ends "the capture is stored as this surface's reference capture for later
# regression comparison". `Tools/UiGate/captures/` cannot hold it: that folder is regenerated output
# and git-ignored (Story 5.1), so a reference written there is lost on the next clone. References
# live in `Tools/UiGate/references/<surface>/`, committed, one PNG per fixture.
#
# A capture is promoted ONLY if the judge passed that exact file: the newest record under
# `Tools/UiGate/captures/*/` whose verdict is `ok` must list the capture's sha256 as a CURRENT image.
# Nothing else can make a reference — not a person's eye, not an agent's report, not a drift run
# that "looked fine". The judge never approves a golden; this script only files one the judge has
# already passed, and copies the verdict into PROVENANCE.md so the approval travels with the file.
#
# Exit: 0 promoted · 1 refused (no passing judge record for this exact capture) · 2 error.
#
# Later stories and regression checks hand a reference to the judge like any other image:
#   reference: Tools/UiGate/references/<surface>/<fixture>.png | accepted reference capture

set -eu

die() { echo "[promote-reference] ERROR: $*" >&2; exit 2; }

[ $# -ge 2 ] || die "usage: promote-reference.sh <surface> <capture.png>..."
SURFACE="$1"; shift
case "$SURFACE" in */*|"") die "surface must be a single path segment, got '$SURFACE'" ;; esac

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
UIGATE_ROOT="${UIGATE_ROOT:-$(CDPATH= cd -- "$HERE/.." && pwd)/UiGate}"
ARCHIVE_ROOT="${UIGATE_ARCHIVE_ROOT:-$UIGATE_ROOT/captures}"
DEST="$UIGATE_ROOT/references/$SURFACE"

sha() { shasum -a 256 "$1" | cut -d' ' -f1; }

refused=0
for cap in "$@"; do
    [ -f "$cap" ] || die "capture not found: $cap"
    s=$(sha "$cap")
    # newest ok record that judged these exact bytes as a CURRENT image
    rec=$(grep -l -E "^- image: [0-9]+ CURRENT .* sha256=$s( |$)" "$ARCHIVE_ROOT"/*/*.md 2>/dev/null \
          | while IFS= read -r f; do grep -q '^- verdict: ok$' "$f" && echo "$f"; done \
          | sort | tail -1 || true)
    if [ -z "$rec" ]; then
        echo "[promote-reference] REFUSED: $cap (sha256 $s) has no passing judge record." >&2
        echo "[promote-reference]   Judge it first: Tools/pf/visual-judge.sh --spec <spec> — exit 0 on these exact bytes." >&2
        refused=1
        continue
    fi
    mkdir -p "$DEST"
    name=$(basename "$cap")
    cp "$cap" "$DEST/$name"
    # The header test runs BEFORE the append block: its `>>` creates the file, so a test inside it
    # always saw one and the header was never written.
    [ -f "$DEST/PROVENANCE.md" ] || printf '# %s — reference captures\n\nAppend-only. Each entry is the judge verdict that allowed a file here.\n' "$SURFACE" > "$DEST/PROVENANCE.md"
    {
        echo
        echo "## $name — $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo
        echo "- sha256: $s"
        echo "- source: $cap"
        echo "- judge record: ${rec#"$UIGATE_ROOT"/}"
        sed -n -E 's/^- (model|effort|caller|contract|contract-sha256|input-sha256): /- judge \1: /p' "$rec"
        git -C "$UIGATE_ROOT" rev-parse HEAD 2>/dev/null | sed 's/^/- commit at promotion: /' || true
        echo
        sed -n '/^## Verdicts/,$p' "$rec" | grep -E '^V[0-9]+ *\|' | sed 's/^/    /'
    } >> "$DEST/PROVENANCE.md"
    echo "[promote-reference] promoted $cap -> ${DEST#"$UIGATE_ROOT"/}/$name (judge record $(basename "$rec"))"
done

[ "$refused" -eq 0 ] || exit 1
exit 0
