#!/usr/bin/env bash
# GENERATED by PrototypeFramework 0.4.2 from Documentation~/agent/tools/typecheck-headless.sh — do not edit here. Change it in the framework repo, then run Framework/Agent Docs/Sync (editor) or Tools/Build/pf-build.sh agentdocs.
# Tier-1 headless type-check. Compile pure-domain / application assemblies
# WITHOUT UnityEngine references — enforces engine-freedom AND is faster
# (no 300+ Unity DLLs to load). Fails if any listed assembly transitively
# depends on Unity APIs.
#
# Usage:
#   Tools/pf/typecheck-headless.sh                      # default whitelist
#   Tools/pf/typecheck-headless.sh Game.Domain Game.X   # explicit list
#
# The default whitelist matches the framework's "engine-free layer" rule.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Assemblies that MUST stay engine-free. Adjust when the layer boundary moves.
DEFAULT_WHITELIST=(
    "Game.Domain"
    "Game.Application"
    "Game.Gen"
)

if [[ $# -gt 0 ]]; then
    ASMS=("$@")
else
    ASMS=("${DEFAULT_WHITELIST[@]}")
fi

failed=0
total_start=$(date +%s)
for asm in "${ASMS[@]}"; do
    csproj_src="$REPO_ROOT/$asm.csproj"
    if [[ ! -f "$csproj_src" ]]; then
        echo "SKIP  $asm  (no csproj — open project in Unity once to generate)"
        continue
    fi

    csproj="$(python3 "$SCRIPT_DIR/_typecheck_lib.py" --headless --repo "$REPO_ROOT" "$asm")"

    log="$(mktemp -t typecheck-headless-XXXX)"
    t0=$(date +%s)
    if dotnet build "$csproj" -nologo -v:q -clp:NoSummary 2>&1 > "$log"; then
        echo "OK    $asm  ($(($(date +%s) - t0))s)"
    else
        echo "FAIL  $asm  ($(($(date +%s) - t0))s)"
        grep -E 'error [A-Z]+[0-9]+|error MSB[0-9]+' "$log" | awk '!seen[$0]++' | head -60 || cat "$log"
        failed=$((failed + 1))
    fi
    rm -f "$log"
done
echo "---   ${#ASMS[@]} asm in $(($(date +%s) - total_start))s, $failed failed"
exit $failed
