#!/usr/bin/env bash
# GENERATED by PrototypeFramework 0.4.2 from Documentation~/agent/tools/typecheck.sh — do not edit here. Change it in the framework repo, then run Framework/Agent Docs/Sync (editor) or Tools/Build/pf-build.sh agentdocs.
# Tier-2 type-check gate. Compile one Unity assembly through dotnet build,
# no Editor round-trip. See Tools/pf/_typecheck_lib.py for the transform.
#
# Usage:
#   Tools/pf/typecheck.sh <AssemblyName>            # e.g. Game.Views
#   Tools/pf/typecheck.sh --list                    # show discoverable assemblies
#   Tools/pf/typecheck.sh --changed                 # asmdefs touched since HEAD
#
# Output is quiet on success (prints "OK <asm> (Ns)"). On failure prints only
# `error CS####` lines and exits non-zero. Cache lives under Library/pf-typecheck/.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

if ! command -v dotnet >/dev/null 2>&1; then
    echo "ERROR: dotnet SDK not found on PATH." >&2
    exit 2
fi

if ! command -v python3 >/dev/null 2>&1; then
    echo "ERROR: python3 not found on PATH." >&2
    exit 2
fi

usage() {
    grep '^#' "$0" | sed 's/^# \{0,1\}//'
    exit "${1:-0}"
}

list_assemblies() {
    cd "$REPO_ROOT"
    ls -1 *.csproj 2>/dev/null | sed 's/\.csproj$//' | sort
}

changed_asmdefs() {
    cd "$REPO_ROOT"
    # asmdef files touched vs HEAD; map dir back to assembly name via asmdef.name
    git diff --name-only HEAD -- '*.asmdef' 2>/dev/null | while read -r asmdef; do
        [[ -f "$asmdef" ]] || continue
        python3 -c "import json,sys; print(json.load(open(sys.argv[1]))['name'])" "$asmdef" 2>/dev/null
    done
    # also: any .cs file → asmdef by walking up
    git diff --name-only HEAD -- '*.cs' 2>/dev/null | while read -r cs; do
        d="$(dirname "$cs")"
        while [[ "$d" != "." && "$d" != "/" ]]; do
            found=$(ls "$d"/*.asmdef 2>/dev/null | head -1 || true)
            if [[ -n "$found" ]]; then
                python3 -c "import json,sys; print(json.load(open(sys.argv[1]))['name'])" "$found" 2>/dev/null
                break
            fi
            d="$(dirname "$d")"
        done
    done | sort -u
}

typecheck_one() {
    local asm="$1"
    local headless="${2:-false}"
    local flag=""
    [[ "$headless" == "true" ]] && flag="--headless"

    local csproj
    csproj="$(python3 "$SCRIPT_DIR/_typecheck_lib.py" $flag --repo "$REPO_ROOT" "$asm")"

    local log
    log="$(mktemp -t typecheck-XXXX)"
    local t0 t1 rc
    t0=$(date +%s)
    if dotnet build "$csproj" -nologo -v:q -clp:NoSummary 2>&1 > "$log"; then
        rc=0
    else
        rc=$?
    fi
    t1=$(date +%s)

    if [[ $rc -eq 0 ]]; then
        echo "OK    $asm  ($((t1 - t0))s)"
    else
        echo "FAIL  $asm  ($((t1 - t0))s)"
        grep -E 'error [A-Z]+[0-9]+|error MSB[0-9]+' "$log" | awk '!seen[$0]++' | head -60 || cat "$log"
    fi
    rm -f "$log"
    return $rc
}

main() {
    case "${1:-}" in
        ""|-h|--help)
            usage 0
            ;;
        --list)
            list_assemblies
            ;;
        --changed)
            local asms
            asms="$(changed_asmdefs)"
            if [[ -z "$asms" ]]; then
                echo "OK    (no changed asmdefs)"
                exit 0
            fi
            local failed=0
            while read -r asm; do
                [[ -z "$asm" ]] && continue
                typecheck_one "$asm" false || failed=$((failed + 1))
            done <<< "$asms"
            exit $failed
            ;;
        *)
            typecheck_one "$1" false
            ;;
    esac
}

main "$@"
