# GENERATED by PrototypeFramework 0.4.2 from Documentation~/agent/tools/uigate_lib.py — do not edit here. Change it in the framework repo, then run Framework/Agent Docs/Sync (editor) or Tools/Build/pf-build.sh agentdocs.
"""Shared helpers for the UiGate tuning tools — parse a Visual Contract, read the judge archive,
run the judge, and compute the deterministic image metrics.

Nothing here decides a verdict. The judge (`Tools/pf/visual-judge.sh`) is the only thing that
answers a contract row; these helpers only count what it said, and measure the pixels with
arithmetic that does not involve a model, so the two can be compared.
"""

import glob
import math
import os
import re
import subprocess
from collections import Counter

# Synced into Tools/pf/ beside the judge. The DATA is the SKU's: UIGATE_ROOT (default Tools/UiGate,
# resolved from this file, not the cwd) holds contracts, captures and tuning/ — the same resolution
# visual-judge.sh uses, so every tool reads the one archive the judge writes.
HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
UIGATE = os.path.abspath(os.environ.get("UIGATE_ROOT") or os.path.join(HERE, "..", "UiGate"))
ARCHIVE = os.path.abspath(os.environ.get("UIGATE_ARCHIVE_ROOT") or os.path.join(UIGATE, "captures"))
TUNING = os.path.join(UIGATE, "tuning")
JUDGE = os.path.join(HERE, "visual-judge.sh")

VERDICTS = ("SATISFIED", "VIOLATED", "CANNOT-TELL")


# --- the contract -------------------------------------------------------------------------------

def contract_section(path):
    """The `## Visual Contract` section of a spec (or of a contract file), as text."""
    text = open(path, encoding="utf-8").read()
    m = re.search(r"^## Visual Contract.*?(?=^## (?!Visual Contract)|\Z)", text, re.M | re.S)
    if not m:
        raise SystemExit(f"no '## Visual Contract' section in {path}")
    return m.group(0)


def contract_block(section):
    """The ```visual-judge inputs block → dict(root, references[(path,label)], captures[...], notes[])."""
    m = re.search(r"^[ \t]*```visual-judge[ \t]*\n(.*?)^[ \t]*```[ \t]*$", section, re.M | re.S)
    out = {"root": "", "references": [], "captures": [], "notes": []}
    if not m:
        return out
    for line in m.group(1).splitlines():
        line = re.sub(r"\s#[^|]*$", "", line).strip()
        k, _, v = line.partition(":")
        k, v = k.strip(), v.strip()
        path, _, label = v.partition("|")
        path, label = path.strip(), label.strip()
        if k == "root":
            out["root"] = v
        elif k == "reference":
            out["references"].append((path, label))
        elif k == "capture":
            out["captures"].append((path, label))
        elif k == "notes":
            out["notes"].append(v)
    return out


def resolve(block, path, use_root):
    if os.path.isabs(path):
        return path
    if use_root and block["root"]:
        return os.path.join(ROOT, block["root"], path)
    return os.path.join(ROOT, path)


def contract_rows(section):
    """{row number: text} for the numbered rows of the contract (outside the inputs block)."""
    body = re.sub(r"```visual-judge.*?```", "", section, flags=re.S)
    rows = {}
    for m in re.finditer(r"^\s{0,3}(\d+)\.\s+(.*)$", body, re.M):
        rows[int(m.group(1))] = m.group(2).strip()
    return rows


def scored_rows(rows):
    """Rows a verdict can be scored on: every row except the declared CANNOT-TELL fallback."""
    return sorted(n for n, t in rows.items() if not t.upper().startswith("CANNOT-TELL FALLBACK"))


# --- the archive --------------------------------------------------------------------------------

def parse_record(path):
    text = open(path, encoding="utf-8").read()
    rec = {"path": path, "file": os.path.basename(path), "images": [], "verdicts": {}}
    for m in re.finditer(r"^- ([a-z0-9-]+): (.*)$", text, re.M):
        k, v = m.group(1), m.group(2).strip()
        if k == "image":
            im = re.match(r"(\d+) (REFERENCE|CURRENT) (.*?) sha256=([0-9a-f]+)(?: \| (.*))?$", v)
            if im:
                rec["images"].append(dict(n=int(im.group(1)), kind=im.group(2), path=im.group(3),
                                          sha=im.group(4), label=im.group(5) or ""))
        else:
            rec.setdefault(k, v)
    vs = text.split("## Verdicts", 1)[-1]
    for m in re.finditer(r"^V(\d+)\s*\|\s*(SATISFIED|VIOLATED|CANNOT-TELL)\s*\|\s*(.*)$", vs, re.M):
        rec["verdicts"][int(m.group(1))] = (m.group(2), m.group(3).strip())
    rec["model_call"] = rec.get("cache", "miss").startswith(("miss", "off"))
    rec["stamp"] = rec["file"].split("-", 1)[0]
    for k in ("duration-s", "tokens"):
        try:
            rec[k] = int(rec.get(k, "0"))
        except ValueError:
            rec[k] = 0
    return rec


def records(surface, since=None):
    out = []
    for p in sorted(glob.glob(os.path.join(ARCHIVE, surface, "*.md"))):
        r = parse_record(p)
        if since and r.get("when", "") < since:
            continue
        out.append(r)
    return out


def halts(surface, since=None):
    p = os.path.join(ARCHIVE, surface, "halts.log")
    if not os.path.exists(p):
        return []
    return [l for l in open(p).read().splitlines() if l and (not since or l[:20] >= since)]


# --- running the judge --------------------------------------------------------------------------

def run_judge(spec, surface, caller, measure=True, extra=()):
    """Run the judge once; return (exit code, newest archive record or None, stderr tail)."""
    args = ["sh", JUDGE, "--spec", spec, "--surface", surface, "--caller", caller]
    if measure:
        args.append("--measure")
    args += list(extra)
    p = subprocess.run(args, cwd=ROOT, capture_output=True, text=True)
    # The judge names the record it wrote; never guess it from the folder (parallel runs share one).
    m = re.findall(r"^\[visual-judge\] archived: (.*\.md)$", p.stderr, re.M)
    rec = parse_record(m[-1]) if m and os.path.exists(m[-1]) else None
    return p.returncode, rec, (p.stderr + p.stdout)[-1500:]


def majority(samples, rows):
    """samples: list of {row: verdict}. → ({row: majority verdict}, {row: agreement 0..1})."""
    maj, agree = {}, {}
    for n in rows:
        vs = [s.get(n, ("MISSING",))[0] for s in samples]
        if not vs:
            continue
        c = Counter(vs).most_common()
        # a tie resolves to the stricter verdict: VIOLATED > CANNOT-TELL > SATISFIED
        top = max((v for v, k in c if k == c[0][1]),
                  key=lambda v: {"VIOLATED": 3, "CANNOT-TELL": 2, "SATISFIED": 1}.get(v, 0))
        maj[n] = top
        agree[n] = c[0][1] / len(vs)
    return maj, agree


# --- deterministic image metrics (Pillow only) ---------------------------------------------------

def _img(path, size=None):
    from PIL import Image
    im = Image.open(path).convert("RGB")
    if size:
        im = im.resize(size, Image.LANCZOS)
    return im


def _srgb_to_lab(rgb):
    def lin(c):
        c /= 255.0
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = (lin(float(v)) for v in rgb)
    x = (0.4124 * r + 0.3576 * g + 0.1805 * b) / 0.95047
    y = (0.2126 * r + 0.7152 * g + 0.0722 * b)
    z = (0.0193 * r + 0.1192 * g + 0.9505 * b) / 1.08883
    f = lambda t: t ** (1 / 3) if t > 0.008856 else 7.787 * t + 16 / 116
    fx, fy, fz = f(x), f(y), f(z)
    return (116 * fy - 16, 500 * (fx - fy), 200 * (fy - fz))


def _palette(path, k=16):
    im = _img(path, (216, 384)).quantize(colors=k, method=2)
    pal = im.getpalette()[: 3 * k]
    counts = sorted(im.getcolors(), reverse=True)
    total = sum(c for c, _ in counts)
    return [(c / total, _srgb_to_lab(pal[3 * i: 3 * i + 3])) for c, i in counts]


def _de(a, b):
    return math.sqrt(sum((p - q) ** 2 for p, q in zip(a, b)))


def palette_distance(a, b):
    """Symmetric weighted chamfer ΔE76 between two images' 16-colour palettes (0 = same palette)."""
    pa, pb = _palette(a), _palette(b)
    ab = sum(w * min(_de(c, d) for _, d in pb) for w, c in pa)
    ba = sum(w * min(_de(c, d) for _, d in pa) for w, c in pb)
    return (ab + ba) / 2


def _gray(path, size=(54, 96)):
    return list(_img(path, size).convert("L").getdata())


def layout_correlation(a, b):
    """Pearson correlation of the two images' 54×96 greyscale thumbnails (1 = same composition)."""
    x, y = _gray(a), _gray(b)
    mx, my = sum(x) / len(x), sum(y) / len(y)
    sxy = sum((p - mx) * (q - my) for p, q in zip(x, y))
    sx = math.sqrt(sum((p - mx) ** 2 for p in x))
    sy = math.sqrt(sum((q - my) ** 2 for q in y))
    return sxy / (sx * sy) if sx and sy else 0.0


def colourfulness(path):
    """Hasler–Süsstrunk colourfulness of a 216×384 thumbnail."""
    px = list(_img(path, (216, 384)).getdata())
    rg = [r - g for r, g, b in px]
    yb = [0.5 * (r + g) - b for r, g, b in px]
    mean = lambda v: sum(v) / len(v)
    sd = lambda v: math.sqrt(mean([(t - mean(v)) ** 2 for t in v]))
    return math.sqrt(sd(rg) ** 2 + sd(yb) ** 2) + 0.3 * math.sqrt(mean(rg) ** 2 + mean(yb) ** 2)


def detail(path):
    """Mean edge magnitude of a 540×960 greyscale — a proxy for rendered detail/finish."""
    from PIL import ImageFilter
    im = _img(path, (540, 960)).convert("L").filter(ImageFilter.FIND_EDGES)
    v = list(im.getdata())
    return sum(v) / len(v)


def image_metrics(capture, reference):
    """How far a capture sits from its reference on four model-free axes."""
    cr, rr = colourfulness(capture), colourfulness(reference)
    dc, dr = detail(capture), detail(reference)
    return {
        "palette_dE": round(palette_distance(capture, reference), 2),
        "layout_corr": round(layout_correlation(capture, reference), 3),
        "colourfulness_ratio": round(cr / rr, 3) if rr else None,
        "detail_ratio": round(dc / dr, 3) if dr else None,
    }
