#!/usr/bin/env python3
# GENERATED by PrototypeFramework 0.4.2 from Documentation~/agent/tools/ux-handoff.py — do not edit here. Change it in the framework repo, then run Framework/Agent Docs/Sync (editor) or Tools/Build/pf-build.sh agentdocs.
# /// script
# requires-python = ">=3.9"
# dependencies = ["pillow", "pyyaml"]
# ///
"""ux-handoff — turn an approved bmad-ux package into a build-ready asset handoff.

The mechanical half of the `pf-ux-asset-handoff` skill (procedure: the skill and
`docs/framework/recipes/ux-asset-handoff.md`). A workspace `<ws>` is a bmad-ux run folder holding
DESIGN.md, EXPERIENCE.md and approved `mockups/*.png`; its sprite data lives in `<ws>/ui-kit/`, its
3D models and animation clips (when the game's world is 3D) in `<ws>/models/`.

    python3 Tools/pf/ux-handoff.py requests --ws <ws> [--ids a,b] [--keyed] [--force]
    python3 Tools/pf/ux-handoff.py manifest --ws <ws> [--check]
    python3 Tools/pf/ux-handoff.py models   --ws <ws> [--check] [--probe]
    python3 Tools/pf/ux-handoff.py sheet    --ws <ws> [--ids a,b] [--beside-crop] [--per-sheet N]
    python3 Tools/pf/ux-handoff.py key-out  <png> [--out P] [--color FF00FF] [--tol 40] [--soft 60]
    python3 Tools/pf/ux-handoff.py check    --ws <ws> [--sku <SkuFolder>]

  requests  ui-kit/sprite-jobs*.json -> Tools/AssetGen/requests/ux-<id>.json for `asset-gen.py`.
            `sprite` jobs become `generate` with a padded crop of `region` (what to reproduce) and
            the whole mockup (style); `plate` jobs become `edit` on the whole mockup (UI painted out).
            Existing requests are kept unless --force. --keyed asks for a flat #FF00FF ground.
  manifest  Measure ui-kit/assets/sprites/<id>.png into ui-kit/sprite-manifest.json (size, alpha
            and visible bounds, hashes, provenance from <png>.gen.json). Never modifies pixels.
            --check: exit 1 when the committed manifest is stale.
  models    Inventory the 3D models and animation clips into models/model-manifest.json: every
            pf-model-gen output (`models/<id>/model.gen.json`, found by itself) plus every mesh and
            clip declared in models/model-sources.json (supplied FBX/glTF, rigs, takes). Hashes each
            file and records its facts (size, triangles, objects, bones, takes and their length;
            triangle counts are recorded for later optimization, never gated here):
            from model.gen.json, from a glTF's own JSON, or, with --probe, from headless Blender
            (the only way to read an FBX's takes). Facts of an unchanged file are reused, so a
            probe is paid once. Never modifies a model or a clip. --check: exit 1 when stale.
  sheet     JPEG contact sheets in <ws>/.working/ (sprite on checkerboard, optionally beside its
            source crop), for review by eye or one vision call.
  key-out   Chroma-key fallback for a generation that came back without transparency.
  check     Cross-check SURFACES.md / DIVERGENCES.md, the sprite, component and model manifests,
            ASSET-MAP.md and the spine links, so an epic/build agent can trust the handoff.

Needs Pillow (the sprite commands and `check`) and PyYAML (`check`). `uv run Tools/pf/ux-handoff.py …`
installs both from the header above. `models --probe` needs Blender (BLENDER_BIN, else Blender.app on
macOS, else `blender` on PATH); UXHANDOFF_BLENDER_TIMEOUT_S (default 600) caps the one Blender run.

Exit codes (CliConventions): 0 ok · 1 drift (a check failed / manifest stale / nothing keyed) · 2 error.
"""

import argparse
import datetime
import hashlib
import json
import os
import re
import shutil
import struct
import subprocess
import sys
import tempfile
from pathlib import Path
from urllib.parse import unquote

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent  # Tools/pf/ -> repo root
KIT = "ui-kit"
MODELS = "models"
EXIT_OK, EXIT_DRIFT, EXIT_ERROR = 0, 1, 2
# uGUI under GetHost of one of the six framework render layers (RenderLayers.gen.cs), or a world Renderer.
HOSTS = {"uGUI-UnderGamePlay", "uGUI-GamePlay", "uGUI-OverlayGamePlay", "uGUI-Ui", "uGUI-Popup", "uGUI-Overlay",
         "Renderer-WorldRoot", "undecided"}
MODEL_HOSTS = {"Renderer-WorldRoot", "undecided"}  # a mesh draws through a Renderer (rule 16)
MESH_EXT = {".fbx", ".glb", ".gltf"}
RIGS = {"none", "transform", "skinned"}
ANIMATION = {"none", "clips", "code", "clips+code"}
SECONDS_TOL = 0.05  # a declared clip length against the measured take
FACTS_VERSION = 2   # bump when a measured fact changes meaning: cached facts of an older version are re-measured


def die(msg):
    print(f"[ux-handoff] ERROR: {msg}", file=sys.stderr)
    sys.exit(EXIT_ERROR)


def pil():
    try:
        from PIL import Image, ImageDraw
        return Image, ImageDraw
    except ImportError:
        die("Pillow is required: `uv run Tools/pf/ux-handoff.py …` or `pip install pillow`")


def workspace(arg):
    ws = Path(arg).resolve()
    if not (ws / "DESIGN.md").is_file() or not (ws / "EXPERIENCE.md").is_file():
        die(f"{ws} is not a bmad-ux workspace (needs DESIGN.md + EXPERIENCE.md)")
    return ws


def rel(p):
    return p.resolve().relative_to(ROOT).as_posix()


def load_jobs(ws):
    """sprite-jobs.json plus any sprite-jobs-*.json beside it, in name order."""
    files = sorted((ws / KIT).glob("sprite-jobs*.json"))
    if not files:
        die(f"no {KIT}/sprite-jobs.json in {ws}")
    jobs, seen = [], set()
    for f in files:
        for job in json.loads(f.read_text()):
            for key in ("id", "ref", "kind", "subject"):
                if not job.get(key):
                    die(f"{f.name}: job {job.get('id', '?')} missing '{key}'")
            if job["id"] in seen:
                die(f"duplicate sprite id {job['id']} ({f.name})")
            seen.add(job["id"])
            jobs.append(job)
    return jobs


def front_matter(path):
    text = path.read_text()
    if not text.startswith("---"):
        return {}
    end = text.find("\n---", 3)
    if end < 0:
        return {}
    try:
        import yaml
    except ImportError:
        die("PyYAML is required for `check`: `uv run Tools/pf/ux-handoff.py check …` or `pip install pyyaml`")
    return yaml.safe_load(text[3:end]) or {}


def sprite_png(ws, sid):
    return ws / KIT / "assets" / "sprites" / f"{sid}.png"


def sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()


# ── requests ─────────────────────────────────────────────────────────────────────────────────────

STYLE = ("Preserve the approved mockup's exact art style: its painted shading, outline weight, rim "
         "thickness, palette and lighting. Do NOT simplify into vector, SVG, flat icon or a geometric "
         "placeholder, and do not invent a new design.")
SPRITE = """Use case: reusable game sprite extracted from an approved mockup.
Image 1 is a crop of the approved mockup showing the asset; Image 2 is the whole mockup, for style only.
Reproduce ONLY this asset: {subject}
{style}
Reconstruct only what text, numbers or overlapping UI hide. Remove every word, digit, price, counter
and label: live text is rendered separately. {ground} Centre the whole silhouette with a small
empty safety margin; nothing clipped, no surroundings, no second object.{aspect}
This is one reusable PNG sprite, not a new mockup."""
PLATE = """Use case: clean background plate from an approved mockup.
Edit Image 1: {subject}
Remove ALL UI: panels, buttons, icons, cards, nodes, ribbons, wallets, characters, text and numbers.
Reconstruct the scenery beneath them so the plate reads as one continuous painting.
{style}
Keep the full rectangular frame opaque. No labels, no numbers, no new props."""
TRANSPARENT = "Output on a genuine transparent background (real alpha, no checkerboard pattern)."
KEYED = ("Output on a perfectly flat solid #FF00FF magenta background with no gradient, shadow or "
         "texture in it; do not use that magenta anywhere in the asset.")


def crop(mock, region, dst):
    Image, _ = pil()
    with Image.open(mock) as im:
        x0, y0, x1, y1 = region
        pad = int(max(x1 - x0, y1 - y0) * 0.08)
        box = (max(0, x0 - pad), max(0, y0 - pad), min(im.width, x1 + pad), min(im.height, y1 + pad))
        c = im.convert("RGB").crop(box)
        if max(c.size) < 512:  # give the model detail to read; never shipped
            k = 512 / max(c.size)
            c = c.resize((round(c.width * k), round(c.height * k)), Image.LANCZOS)
        dst.parent.mkdir(parents=True, exist_ok=True)
        c.save(dst)


def cmd_requests(a):
    ws = workspace(a.ws)
    if not (HERE / "asset-gen.py").is_file():
        die("Tools/pf/asset-gen.py not found: run the agent-docs sync first")
    want = set(a.ids.split(",")) if a.ids else None
    req_dir = ROOT / "Tools" / "AssetGen" / "requests"
    req_dir.mkdir(parents=True, exist_ok=True)
    written = kept = 0
    for job in load_jobs(ws):
        if want and job["id"] not in want:
            continue
        mock = ws / "mockups" / job["ref"]
        if not mock.is_file():
            die(f"{job['id']}: mockup not found: {mock}")
        dst = req_dir / f"ux-{job['id']}.json"
        if dst.exists() and not a.force:
            kept += 1
            continue
        req = {"schema": "asset-gen-request/v1", "id": f"ux-{job['id']}",
               "out": rel(sprite_png(ws, job["id"])), "consumer": rel(ws / KIT / "sprite-manifest.json")}
        if job["kind"] == "plate":
            req.update(mode="edit", target=rel(mock), references=[],
                       prompt=PLATE.format(subject=job["subject"], style=STYLE))
        else:
            if not job.get("region"):
                die(f"{job['id']}: sprite job needs region [x0,y0,x1,y1] in mockup pixels")
            c = ws / ".working" / "asset-crops" / f"{job['id']}.png"
            crop(mock, job["region"], c)
            aspect = f" Keep the source aspect ratio {job['aspect']}." if job.get("aspect") else ""
            req.update(mode="generate",
                       references=[{"path": rel(c), "role": "composition"}, {"path": rel(mock), "role": "style"}],
                       prompt=SPRITE.format(subject=job["subject"], style=STYLE,
                                            ground=KEYED if a.keyed else TRANSPARENT, aspect=aspect))
        dst.write_text(json.dumps(req, ensure_ascii=False, indent=2) + "\n")
        written += 1
    print(f"[ux-handoff] requests written: {written}, kept: {kept} -> {rel(req_dir)}")
    return EXIT_OK


# ── manifest ─────────────────────────────────────────────────────────────────────────────────────

def cmd_manifest(a):
    Image, _ = pil()
    ws = workspace(a.ws)
    assets, missing, no_alpha = [], [], []
    for job in load_jobs(ws):
        png = sprite_png(ws, job["id"])
        if not png.is_file():
            missing.append(job["id"])
            continue
        with Image.open(png) as im:
            w, h = im.size
            alpha = im.getchannel("A") if "A" in im.getbands() else None
            bounds = alpha.getbbox() if alpha else (0, 0, w, h)
            visible = alpha.point(lambda v: 255 if v >= 32 else 0).getbbox() if alpha else bounds
            arange = alpha.getextrema() if alpha else None
        if job["kind"] == "sprite" and (not arange or arange[0] > 0):
            no_alpha.append(job["id"])
        gen = png.with_name(png.name + ".gen.json")
        prov = json.loads(gen.read_text()) if gen.is_file() else {}
        mock = ws / "mockups" / job["ref"]
        assets.append({
            "id": job["id"], "file": png.relative_to(ws / KIT).as_posix(), "kind": job["kind"],
            "reference": job["ref"], "region": job.get("region"),
            "method": "asset-gen extraction from an approved flattened mockup; not a lossless layer export",
            "status": prov.get("status", "unknown-provenance"),
            "width": w, "height": h, "alphaBoundsXYXY": list(bounds) if bounds else None,
            "visibleBoundsXYXY": list(visible) if visible else None,
            "alphaRange": list(arange) if arange else None,
            "sha256": sha(png), "sourceSha256": sha(mock) if mock.is_file() else None,
            "pivot": job.get("pivot", [0.5, 0.5]), "pixelsPerUnitForUnity": 1,
            "draw": job.get("draw", "sliced" if job.get("slice") else "simple"),
            "suggestedSliceFractionLTRB": job.get("slice"), "subject": job["subject"],
        })
    manifest = {"version": 3, "generator": "Tools/pf/ux-handoff.py manifest",
                "expected": len(assets) + len(missing), "delivered": len(assets),
                "missing": missing, "noAlpha": no_alpha, "assets": assets}
    out = ws / KIT / "sprite-manifest.json"
    if a.check:
        old = json.loads(out.read_text()) if out.is_file() else {}
        old.pop("created", None)
        drift = old != manifest
        print("[ux-handoff] sprite-manifest.json " + ("DRIFT: re-run `manifest`" if drift else "up to date"))
        return EXIT_DRIFT if drift else EXIT_OK
    manifest["created"] = datetime.date.today().isoformat()
    out.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
    print(f"[ux-handoff] {len(assets)} sprites, {len(missing)} missing, {len(no_alpha)} without alpha -> {rel(out)}")
    if missing:
        print("  missing: " + ", ".join(missing))
    if no_alpha:
        print("  no alpha (requests --keyed + key-out, or re-extract): " + ", ".join(no_alpha))
    return EXIT_OK


# ── models ───────────────────────────────────────────────────────────────────────────────────────

PROBE = r'''
import json, math, sys
import bpy

spec, out = sys.argv[sys.argv.index("--") + 1:]
facts = {}
for path in json.load(open(spec)):
    bpy.ops.wm.read_factory_settings(use_empty=True)
    try:
        if path.lower().endswith(".fbx"):
            bpy.ops.import_scene.fbx(filepath=path)
        else:
            bpy.ops.import_scene.gltf(filepath=path)
    except Exception as e:  # one unreadable file is a fact, not a failed run
        facts[path] = {"error": str(e)[:300]}
        continue
    scene = bpy.context.scene
    fps = scene.render.fps / scene.render.fps_base
    graph = bpy.context.evaluated_depsgraph_get()
    lo, hi, tris, bones, objects = [math.inf] * 3, [-math.inf] * 3, 0, 0, []
    for ob in scene.objects:
        objects.append(ob.name)
        if ob.type == "ARMATURE":  # bones become transforms in Unity too, so a part may be one
            bones += len(ob.data.bones)
            objects += [b.name for b in ob.data.bones]
        if ob.type != "MESH":
            continue
        ev = ob.evaluated_get(graph)
        mesh = ev.to_mesh()
        mesh.calc_loop_triangles()
        tris += len(mesh.loop_triangles)
        for v in mesh.vertices:
            w = ev.matrix_world @ v.co
            for i in range(3):
                lo[i], hi[i] = min(lo[i], w[i]), max(hi[i], w[i])
        ev.to_mesh_clear()
    takes = {}
    for action in bpy.data.actions:  # FBX: one action per object and take, "<object>|<take>"
        name = action.name.split("|")[-1]
        start, end = action.frame_range
        takes[name] = max(takes.get(name, 0.0), round((end - start) / fps, 3))
    size = None if lo[0] == math.inf else [round(hi[0] - lo[0], 3), round(hi[2] - lo[2], 3), round(hi[1] - lo[1], 3)]
    facts[path] = {"size_m": size, "tris": tris, "bones": bones, "objects": sorted(set(objects)),
                   "takes": [{"name": k, "seconds": v} for k, v in sorted(takes.items())], "fps": fps}
json.dump(facts, open(out, "w"), indent=1)
'''


def blender_bin():
    explicit = os.environ.get("BLENDER_BIN")
    if explicit:
        return explicit
    mac = Path("/Applications/Blender.app/Contents/MacOS/Blender")
    if mac.exists():
        return str(mac)
    return shutil.which("blender") or die("Blender not found (models --probe): install it or set BLENDER_BIN")


def probe(paths):
    """{abs path: facts} for every file, from ONE headless Blender run (a launch costs seconds)."""
    if not paths:
        return {}
    timeout = int(os.environ.get("UXHANDOFF_BLENDER_TIMEOUT_S", "600"))
    with tempfile.TemporaryDirectory(prefix="ux-handoff-probe-") as tmp:
        script, spec, out = Path(tmp, "probe.py"), Path(tmp, "spec.json"), Path(tmp, "facts.json")
        script.write_text(PROBE)
        spec.write_text(json.dumps([str(p) for p in paths]))
        cmd = [blender_bin(), "-b", "--factory-startup", "--python-exit-code", "3", "-P", str(script), "--",
               str(spec), str(out)]
        try:
            run = subprocess.run(cmd, cwd=tmp, capture_output=True, text=True, timeout=timeout)
        except subprocess.TimeoutExpired:
            die(f"Blender probe did not finish within {timeout} s ({len(paths)} files); raise "
                "UXHANDOFF_BLENDER_TIMEOUT_S or probe fewer files")
        if not out.is_file():
            die("Blender probe wrote no facts; log tail:\n" + "\n".join((run.stdout + run.stderr).splitlines()[-15:]))
        return json.loads(out.read_text())


def gltf_facts(path):
    """Facts a glTF carries in its own JSON: triangles, nodes (joints are nodes), takes; no bounding box."""
    data = path.read_bytes()
    if path.suffix.lower() == ".glb":
        magic, _, _ = struct.unpack_from("<4sII", data, 0)
        length, kind = struct.unpack_from("<I4s", data, 12)
        if magic != b"glTF" or kind != b"JSON":
            die(f"{path}: not a binary glTF")
        doc = json.loads(data[20:20 + length])
    else:
        doc = json.loads(data)
    acc, meshes = doc.get("accessors", []), doc.get("meshes", [])

    def mesh_tris(m):
        n = 0
        for p in meshes[m].get("primitives", []):
            if p.get("mode", 4) != 4:  # triangles only
                continue
            src = p.get("indices", p.get("attributes", {}).get("POSITION"))
            n += acc[src]["count"] // 3 if src is not None else 0
        return n

    nodes = doc.get("nodes", [])
    takes = []
    for a in doc.get("animations", []):
        inputs = [acc[s["input"]] for s in a.get("samplers", [])]
        span = (max(x["max"][0] for x in inputs) - min(x["min"][0] for x in inputs)) if inputs else 0.0
        takes.append({"name": a.get("name", ""), "seconds": round(span, 3)})
    return {"size_m": None, "tris": sum(mesh_tris(n["mesh"]) for n in nodes if "mesh" in n),
            "bones": len({j for s in doc.get("skins", []) for j in s.get("joints", [])}),
            "objects": sorted({n.get("name", "") for n in nodes}), "takes": sorted(takes, key=lambda t: t["name"])}


def modelgen_facts(gen):
    f = gen.get("facts") or {}
    s = f.get("size")
    return {"size_m": [s["width"], s["height"], s["length"]] if s else None, "tris": f.get("tris"), "bones": 0,
            "objects": sorted({o["name"] for o in f.get("objects", [])} | set(f.get("empties") or [])),
            "takes": []}  # model-gen bakes no animation; its sockets and pivots are empties


def ws_path(ws, p):
    """A path a source names: workspace-relative, or repo-relative (model.gen.json writes those)."""
    q = ws / p
    return q if q.exists() else ROOT / p


def load_sources(ws):
    """pf-model-gen outputs (found by themselves) merged with models/model-sources.json (declared)."""
    entries = {}
    for gen_path in sorted((ws / MODELS).glob("*/model.gen.json")):
        gen = json.loads(gen_path.read_text())
        fbx = ws_path(ws, gen["fbx"]["path"])
        req_path = ROOT / gen.get("request", "")
        req = json.loads(req_path.read_text()) if gen.get("request") and req_path.is_file() else {}
        entries[gen["id"]] = {"id": gen["id"], "origin": "model-gen", "mesh": fbx, "rig": "none", "clips": [],
                              "parts": [x["name"] for x in req.get("parts", [])],
                              "_gen": gen, "_gen_path": gen_path}
    src = ws / MODELS / "model-sources.json"
    if src.is_file():
        for d in json.loads(src.read_text()):
            if not d.get("id") or not d.get("mesh") and d["id"] not in entries:
                die(f"model-sources.json: entry {d.get('id', '?')} needs id and mesh")
            e = entries.setdefault(d["id"], {"id": d["id"], "origin": "supplied", "clips": []})
            if d.get("mesh") and e["origin"] == "model-gen":
                e["origin"] = "model-gen+supplied"  # a declared mesh (say a rigged or animated one) replaces its FBX
            for k, v in d.items():
                e[k] = ws_path(ws, v) if k in ("mesh", "anim") else v
            if e.get("rig", "none") not in RIGS:
                die(f"model-sources.json: {d['id']}: rig must be one of {sorted(RIGS)}")
            for c in e.get("clips", []):
                if not c.get("id"):
                    die(f"model-sources.json: {d['id']}: every clip needs an id")
    return [entries[k] for k in sorted(entries)]


def match_take(clip_id, takes, file_named_for_clip):
    """The take a clip names: by name, or the file's only take when the file is named after the clip."""
    if takes is None:
        return None
    hit = [t for t in takes if t["name"] == clip_id]
    if not hit and file_named_for_clip and len(takes) >= 1:
        hit = sorted(takes, key=lambda t: -t["seconds"])[:1]
    return hit[0] if hit else False


def cmd_models(a):
    ws = workspace(a.ws)
    out = ws / MODELS / "model-manifest.json"
    old = json.loads(out.read_text()) if out.is_file() else {}
    cached = old.get("files", {}) if old.get("factsVersion") == FACTS_VERSION else {}
    entries = load_sources(ws)
    if not entries:
        die(f"no 3D sources: no {MODELS}/*/model.gen.json and no {MODELS}/model-sources.json in {ws}")

    def wsrel(p):
        try:
            return p.resolve().relative_to(ws).as_posix()
        except ValueError:
            return rel(p)

    files, need_probe = {}, []
    for e in entries:
        for p in [e.get("mesh"), e.get("anim")] + [ws_path(ws, c["file"]) for c in e["clips"] if c.get("file")]:
            if p is None or wsrel(p) in files:
                continue
            key = wsrel(p)
            if not p.is_file():
                files[key] = None
                continue
            digest = sha(p)
            rec = {"sha256": digest, "bytes": p.stat().st_size, "format": p.suffix.lower().lstrip("."),
                   "factsSource": None, "facts": None}
            prev = cached.get(key) or {}
            if prev.get("sha256") == digest and prev.get("facts"):
                rec.update(factsSource=prev["factsSource"], facts=prev["facts"])
            elif p.suffix.lower() in (".glb", ".gltf"):
                rec.update(factsSource="gltf", facts=gltf_facts(p))
            gen = e.get("_gen")
            if rec["facts"] is None and gen and p == e.get("mesh") and digest == gen["fbx"]["sha256"]:
                rec.update(factsSource="model-gen", facts=modelgen_facts(gen))
            if rec["facts"] is None and a.probe:
                need_probe.append((key, p))
            files[key] = rec
    for path, f in probe([p for _, p in need_probe]).items():
        key = next(k for k, p in need_probe if str(p) == path)
        if "error" in f:
            print(f"  probe could not read {key}: {f['error']}")
            continue
        files[key].update(factsSource="blender", facts=f)

    models, missing = [], []
    for e in entries:
        mesh = e.get("mesh")
        mkey = wsrel(mesh) if mesh else None
        if not mkey or files.get(mkey) is None:
            missing.append(e["id"])
            continue
        akey = wsrel(e["anim"]) if e.get("anim") else None
        mf = (files[mkey] or {}).get("facts") or {}
        clips = []
        for c in e["clips"]:
            ckey = wsrel(ws_path(ws, c["file"])) if c.get("file") else akey or mkey
            cf = files.get(ckey)
            if cf is None:  # the file is missing: the clip is not there
                take = False
            else:
                takes = (cf.get("facts") or {}).get("takes")
                take = match_take(c["id"], takes, bool(c.get("file")) and Path(ckey).stem == c["id"])
            clips.append({"id": c["id"], "file": ckey, "loop": c.get("loop"), "seconds": c.get("seconds"),
                          "take": take["name"] if take else None,
                          "measuredSeconds": take["seconds"] if take else None,
                          "found": None if take is None else bool(take)})
        gen = e.get("_gen")
        models.append({
            "id": e["id"], "origin": e["origin"], "mesh": mkey, "anim": akey,
            "status": e.get("status") or (gen or {}).get("status") or "unknown-provenance",
            "provenance": wsrel(e["_gen_path"]) if gen else None,
            "rig": e.get("rig", "none"), "parts": e.get("parts") or [],
            "tris": mf.get("tris"), "size_m": mf.get("size_m"), "bones": mf.get("bones"),
            "objects": mf.get("objects"), "clips": clips,
        })
    unprobed = sorted(k for k, f in files.items() if f and f["facts"] is None)
    manifest = {"version": 1, "factsVersion": FACTS_VERSION, "generator": "Tools/pf/ux-handoff.py models",
                "expected": len(entries), "delivered": len(models), "missing": missing, "unprobed": unprobed,
                "files": {k: files[k] for k in sorted(files) if files[k]}, "models": models}
    if a.check:
        def fingerprint(m):  # what a stale manifest misleads about: which files, which bytes, which state
            return ([(x["id"], x["mesh"], x["anim"], x["status"], [(c["id"], c["file"]) for c in x["clips"]])
                     for x in m.get("models", [])], {k: v["sha256"] for k, v in m.get("files", {}).items()},
                    m.get("missing"))
        drift = fingerprint(old) != fingerprint(manifest)
        print("[ux-handoff] model-manifest.json " + ("DRIFT: re-run `models`" if drift else "up to date"))
        return EXIT_DRIFT if drift else EXIT_OK
    manifest["created"] = datetime.date.today().isoformat()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(manifest, ensure_ascii=False, indent=1) + "\n")
    n_clips = sum(len(m["clips"]) for m in models)
    print(f"[ux-handoff] {len(models)} models, {n_clips} clips, {len(missing)} missing, {len(unprobed)} file(s) "
          f"without facts -> {rel(out)}")
    if missing:
        print("  missing: " + ", ".join(missing))
    if unprobed:
        print(f"  no facts (FBX takes and size need `models --probe`): {len(unprobed)} file(s)")
    return EXIT_OK


# ── sheet ────────────────────────────────────────────────────────────────────────────────────────

CELL, LABEL, COLS = 220, 22, 6


def cmd_sheet(a):
    Image, ImageDraw = pil()
    ws = workspace(a.ws)
    want = set(a.ids.split(",")) if a.ids else None

    def checker(size):
        im = Image.new("RGB", size, (200, 200, 200))
        d = ImageDraw.Draw(im)
        for y in range(0, size[1], 16):
            for x in range(0, size[0], 16):
                if (x // 16 + y // 16) % 2:
                    d.rectangle([x, y, x + 15, y + 15], fill=(150, 150, 150))
        return im

    def fit(im, box):
        k = min(box[0] / im.width, box[1] / im.height)
        return im.resize((max(1, int(im.width * k)), max(1, int(im.height * k))))

    items = [(j["id"], sprite_png(ws, j["id"]), ws / ".working" / "asset-crops" / f"{j['id']}.png")
             for j in load_jobs(ws) if (not want or j["id"] in want) and sprite_png(ws, j["id"]).is_file()]
    cw = CELL * (2 if a.beside_crop else 1)
    paths = []
    for n in range(0, len(items), a.per_sheet):
        chunk = items[n:n + a.per_sheet]
        rows = (len(chunk) + COLS - 1) // COLS
        sheet = Image.new("RGB", (cw * COLS, (CELL + LABEL) * rows), (40, 40, 40))
        d = ImageDraw.Draw(sheet)
        for i, (sid, png, crop_png) in enumerate(chunk):
            x, y = (i % COLS) * cw, (i // COLS) * (CELL + LABEL)
            if a.beside_crop and crop_png.is_file():
                sheet.paste(fit(Image.open(crop_png).convert("RGB"), (CELL - 8, CELL - 8)), (x + 4, y + 4))
                x += CELL
            bg = checker((CELL - 8, CELL - 8))
            spr = fit(Image.open(png).convert("RGBA"), (CELL - 16, CELL - 16))
            bg.paste(spr, ((bg.width - spr.width) // 2, (bg.height - spr.height) // 2), spr)
            sheet.paste(bg, (x + 4, y + 4))
            d.text(((i % COLS) * cw + 6, y + CELL), sid, fill=(255, 255, 255))
        out = ws / ".working" / f"sprite-sheet-{n // a.per_sheet + 1:02d}.jpg"
        out.parent.mkdir(parents=True, exist_ok=True)
        sheet.save(out, quality=88)
        paths.append(out)
    print("\n".join(str(p) for p in paths) or "[ux-handoff] no sprites found")
    return EXIT_OK


# ── key-out ──────────────────────────────────────────────────────────────────────────────────────

def cmd_key_out(a):
    Image, _ = pil()
    kr, kg, kb = (int(a.color[i:i + 2], 16) for i in (0, 2, 4))
    magenta = kr > 128 and kb > 128 and kg < 128
    im = Image.open(a.src).convert("RGBA")
    px = im.load()
    keyed = 0
    for y in range(im.height):
        for x in range(im.width):
            r, g, b, al = px[x, y]
            d = ((r - kr) ** 2 + (g - kg) ** 2 + (b - kb) ** 2) ** 0.5
            if d >= a.tol + a.soft:
                continue
            t = 0.0 if d <= a.tol else (d - a.tol) / a.soft
            keyed += 1
            if magenta:  # pull the spill out of the fringe
                spill = max(0, min(r, b) - g) * (1 - t)
                r, b = int(r - spill), int(b - spill)
            px[x, y] = (r, g, b, int(al * t))
    im.save(a.out or a.src)
    lo, hi = im.getchannel("A").getextrema()
    print(f"[ux-handoff] keyed {keyed} px, alpha {lo}..{hi} -> {a.out or a.src}")
    return EXIT_OK if keyed else EXIT_DRIFT


# ── check ────────────────────────────────────────────────────────────────────────────────────────

LINK = re.compile(r"\]\(([^)\s#]+)(?:#[^)]*)?\)")


def cmd_check(a):
    Image, _ = pil()
    ws = workspace(a.ws)
    fails, warns = [], []
    fail = lambda area, m: fails.append(f"[{area}] {m}")  # noqa: E731
    warn = lambda area, m: warns.append(f"[{area}] {m}")  # noqa: E731
    sku = a.sku
    if not sku:
        hits = list((ROOT / "Assets").glob("*/*FrameworkSettings.asset"))
        sku = hits[0].parent.name if len(hits) == 1 else None
    loose = {f.stem for f in (ws / KIT / "assets").glob("*.png")}

    # surfaces
    sp = ws / "SURFACES.md"
    div = (ws / "DIVERGENCES.md").read_text() if (ws / "DIVERGENCES.md").is_file() else None
    if div is None:
        fail("surfaces", "DIVERGENCES.md missing")
    if not sp.is_file():
        fail("surfaces", "SURFACES.md missing")
    else:
        surfaces = front_matter(sp).get("surfaces") or {}
        if not surfaces:
            fail("surfaces", "SURFACES.md front matter has no `surfaces:`")
        for key, s in surfaces.items():
            cap = str(s.get("capture", ""))
            if cap in ("none", "None", ""):
                if not s.get("reason"):
                    fail("surfaces", f"{key}: capture none without reason")
                continue
            if not (ws / cap).is_file():
                fail("surfaces", f"{key}: capture not found: {cap}")
            for st in (s.get("states") or []):
                sc = st.get("capture") if isinstance(st, dict) else None
                if sc and not (ws / sc).is_file():
                    fail("surfaces", f"{key}: state capture not found: {sc}")
            if not s.get("approved"):
                fail("surfaces", f"{key}: no approval date")
            if div is not None and not re.search(rf"^#+ .*\b{re.escape(key)}\b", div, re.M):
                fail("surfaces", f"{key}: no DIVERGENCES.md heading (write 'None' explicitly)")

    # sprites
    assets = {}
    mp = ws / KIT / "sprite-manifest.json"
    if not mp.is_file():
        fail("sprites", f"{KIT}/sprite-manifest.json missing")
    else:
        assets = {x["id"]: x for x in json.loads(mp.read_text()).get("assets", [])}
        for sid, x in assets.items():
            f = ws / KIT / x["file"]
            if not f.is_file():
                fail("sprites", f"{sid}: file missing {x['file']}")
                continue
            if x.get("sha256") and sha(f) != x["sha256"]:
                fail("sprites", f"{sid}: sha256 differs from manifest (re-run `manifest`)")
            if x.get("kind") == "sprite":
                with Image.open(f) as im:
                    if "A" not in im.getbands() or im.getchannel("A").getextrema()[0] > 0:
                        fail("sprites", f"{sid}: sprite has no transparent pixels")

    # components
    cp = ws / KIT / "component-manifest.json"
    if not cp.is_file():
        warn("components", f"{KIT}/component-manifest.json missing (component→sprite binding lives only in ASSET-MAP)")
    else:
        bound = set()
        for c in json.loads(cp.read_text()).get("components", []):
            for s in c.get("sprites", []):
                sid = s.split("/")[-1].removesuffix(".png")
                bound.add(sid)
                if sid not in assets and sid not in loose:
                    fail("components", f"{c['id']}: sprite '{s}' not in sprite manifest")
        free = sorted(set(assets) - bound)
        if free:
            warn("components", f"{len(free)} sprite(s) bound to no component (content art is fine; UI chrome is a gap): "
                 + ", ".join(free[:12]) + (" …" if len(free) > 12 else ""))

    # asset map
    ap = ws / "ASSET-MAP.md"
    fm = {}
    if not ap.is_file():
        fail("asset-map", "ASSET-MAP.md missing")
    else:
        fm = front_matter(ap)
        mapped, unmapped = fm.get("sprites") or {}, fm.get("unmapped") or {}
        if not mapped:
            fail("asset-map", "ASSET-MAP.md front matter has no `sprites:`")
        for sid in assets:
            if sid not in mapped and sid not in unmapped:
                fail("asset-map", f"{sid}: in sprite manifest but not mapped (map it or list under unmapped: with a reason)")
        for sid, m in mapped.items():
            if sid not in assets and sid not in loose:
                fail("asset-map", f"{sid}: mapped but no such sprite")
            tgt = m.get("target")
            ok_tgt = isinstance(tgt, list) and len(tgt) == 2
            if not ok_tgt:
                fail("asset-map", f"{sid}: target [w,h] missing")
            host = m.get("host")
            if host not in HOSTS:
                fail("asset-map", f"{sid}: host '{host}' not one of {sorted(HOSTS)}")
            elif host == "undecided":
                warn("asset-map", f"{sid}: host undecided")
            dest = str(m.get("dest", ""))
            if sku and not dest.startswith(f"Assets/{sku}/"):
                fail("asset-map", f"{sid}: dest '{dest}' outside Assets/{sku}/ (SpriteImportDefaults would not apply PPU 1)")
            x = assets.get(sid)
            if x and ok_tgt and x.get("visibleBoundsXYXY"):
                x0, y0, x1, y1 = x["visibleBoundsXYXY"]
                if tgt[0] > x1 - x0 or tgt[1] > y1 - y0:
                    warn("asset-map", f"{sid}: target {tgt} exceeds master visible size {[x1 - x0, y1 - y0]} (upscale)")
            if m.get("size_source") == "assumption":
                warn("asset-map", f"{sid}: size is an assumption")

    # models: a 3D world's meshes and clips, then their ASSET-MAP rows
    is3d = bool(list((ws / MODELS).glob("*/model.gen.json"))) or (ws / MODELS / "model-sources.json").is_file() \
        or (ws / "MODELS.md").is_file()
    if not is3d:
        stray = sorted(p.relative_to(ws).as_posix() for p in ws.rglob("*")
                       if p.suffix.lower() in MESH_EXT and ".working" not in p.parts)
        if stray:
            fail("models", f"{len(stray)} FBX/glTF file(s) but no 3D inventory (declare them in {MODELS}/model-sources.json, "
                 "run `models`): " + ", ".join(stray[:6]) + (" …" if len(stray) > 6 else ""))
    models = {}
    mm = ws / MODELS / "model-manifest.json"
    if is3d and not mm.is_file():
        fail("models", f"{MODELS}/model-manifest.json missing (run `ux-handoff.py models`)")
    elif is3d:
        man = json.loads(mm.read_text())
        for key, f in man.get("files", {}).items():
            p = ws_path(ws, key)
            if not p.is_file():
                fail("models", f"{key}: file missing")
            elif sha(p) != f["sha256"]:
                fail("models", f"{key}: sha256 differs from manifest (re-run `models`)")
        for mid in man.get("missing", []):
            fail("models", f"{mid}: mesh file missing (a Gap: pf-model-gen, or the artist who owns it)")
        if man.get("unprobed"):
            warn("models", f"{len(man['unprobed'])} file(s) without facts, so their takes, size and parts are unverified "
                 "(run `models --probe`): " + ", ".join(man["unprobed"][:6]) + (" …" if len(man["unprobed"]) > 6 else ""))
        pending = []
        for m in man.get("models", []):
            mid = m["id"]
            models[mid] = m
            if m.get("status") != "approved":
                pending.append(f"{mid} ({m.get('status')})")
            if m.get("provenance"):
                gen = json.loads((ws / m["provenance"]).read_text())
                fbx = ws_path(ws, gen["fbx"]["path"])
                if not fbx.is_file() or sha(fbx) != gen["fbx"]["sha256"]:
                    fail("models", f"{mid}: FBX no longer matches model.gen.json (rebuild it with model-gen; never hand-edit)")
            if m["rig"] == "skinned" and m.get("bones") == 0:
                fail("models", f"{mid}: rig skinned but the file has no bones")
            if m["rig"] == "none" and m["clips"]:
                fail("models", f"{mid}: clips declared on a model with rig none")
            objects = set(m.get("objects") or [])
            for part in m.get("parts") or []:
                if objects and part not in objects:
                    fail("models", f"{mid}: moving part '{part}' is not an object or bone in the mesh")
            for c in m["clips"]:
                where = f"{mid}.{c['id']}"
                if c["file"] not in man.get("files", {}):
                    fail("models", f"{where}: file missing {c['file']}")
                elif c["found"] is False:
                    fail("models", f"{where}: no such take in {c['file']}")
                if not isinstance(c.get("loop"), bool):
                    fail("models", f"{where}: loop not declared (true/false; the import sets it)")
                if c.get("seconds") and c.get("measuredSeconds") is not None and \
                        abs(c["measuredSeconds"] - c["seconds"]) > SECONDS_TOL * c["seconds"]:
                    fail("models", f"{where}: declared {c['seconds']} s but the file holds {c['measuredSeconds']} s "
                         "(a frame-rate mismatch at export?)")
        if pending:
            warn("models", f"{len(pending)} model(s) not approved: " + ", ".join(pending[:8]) + (" …" if len(pending) > 8 else ""))

    if is3d and ap.is_file():
        mapped, unmapped = fm.get("models") or {}, fm.get("unmapped_models") or {}
        scale = fm.get("model_import_scale")
        if scale is None:
            fail("asset-map", "no `model_import_scale` (how a metre lands on the rig: a number, or `undecided`)")
        elif scale == "undecided":
            warn("asset-map", "model_import_scale undecided (an architecture decision: route it)")
        elif not isinstance(scale, (int, float)) or scale <= 0:
            fail("asset-map", f"model_import_scale '{scale}' is not a positive number or `undecided`")
        if models and not mapped:
            fail("asset-map", "ASSET-MAP.md front matter has no `models:`")
        for mid in models:
            if mid not in mapped and mid not in unmapped:
                fail("asset-map", f"{mid}: in model manifest but not mapped (map it or list under unmapped_models: with a reason)")
        for mid, r in mapped.items():
            r = r or {}
            m = models.get(mid)
            if not m:
                fail("asset-map", f"{mid}: mapped but no such model")
                continue
            host = r.get("host")
            if host not in MODEL_HOSTS:
                fail("asset-map", f"{mid}: host '{host}' not one of {sorted(MODEL_HOSTS)}")
            elif host == "undecided":
                warn("asset-map", f"{mid}: host undecided")
            dest = str(r.get("dest", ""))
            if sku and not dest.startswith(f"Assets/{sku}/"):
                fail("asset-map", f"{mid}: dest '{dest}' outside Assets/{sku}/")
            if Path(dest).suffix.lower() not in MESH_EXT:
                fail("asset-map", f"{mid}: dest '{dest}' is not an .fbx/.glb/.gltf")
            elif Path(dest).suffix.lower() != ".fbx":
                warn("asset-map", f"{mid}: glTF dest needs a glTF importer package in the SKU")
            if "import_scale" in r and r["import_scale"] != scale and not r.get("scale_note"):
                fail("asset-map", f"{mid}: import_scale {r['import_scale']} differs from model_import_scale {scale} "
                     "with no scale_note (a scale applied twice?)")
            if not r.get("used_by"):
                fail("asset-map", f"{mid}: used_by missing")
            if r.get("rig") and r["rig"] != m["rig"]:
                fail("asset-map", f"{mid}: rig '{r['rig']}' but the manifest says '{m['rig']}'")
            anim = r.get("animation", "none")
            if anim not in ANIMATION:
                fail("asset-map", f"{mid}: animation '{anim}' not one of {sorted(ANIMATION)}")
                continue
            have = {c["id"] for c in m["clips"]}
            clips, skip = r.get("clips") or {}, r.get("unmapped_clips") or {}
            if "clips" in anim:
                for cid in sorted(have - set(clips) - set(skip)):
                    fail("asset-map", f"{mid}.{cid}: clip in manifest but not mapped (map it or list under unmapped_clips:)")
                if not clips:
                    fail("asset-map", f"{mid}: animation '{anim}' maps no clips")
            elif clips:
                fail("asset-map", f"{mid}: clips mapped but animation is '{anim}'")
            for cid, cr in clips.items():
                if cid not in have:
                    fail("asset-map", f"{mid}.{cid}: mapped but no such clip in the manifest")
                elif not (cr or {}).get("used_by"):
                    fail("asset-map", f"{mid}.{cid}: used_by missing (the state or event that plays it)")
            if "code" in anim:
                parts, objects = r.get("code_parts") or [], set(m.get("objects") or [])
                if not parts:
                    fail("asset-map", f"{mid}: animation '{anim}' names no code_parts")
                for part in parts:
                    if objects and part not in objects:
                        fail("asset-map", f"{mid}: code part '{part}' is not an object or bone in the mesh")
                if parts and not objects:
                    warn("asset-map", f"{mid}: code_parts unverified (no facts for the mesh)")

    # spines
    if is3d and not any(k in (ws / n).read_text() for n in ("DESIGN.md", "EXPERIENCE.md")
                        for k in ("model-manifest.json", "MODELS.md")):
        fail("spines", "neither DESIGN.md nor EXPERIENCE.md links the 3D inventory (MODELS.md or models/model-manifest.json)")
    for name in ("DESIGN.md", "EXPERIENCE.md"):
        t = (ws / name).read_text()
        for must in ("SURFACES.md", "ASSET-MAP.md"):
            if must not in t:
                fail("spines", f"{name} does not link {must}")
    if "### Finish bar" not in (ws / "DESIGN.md").read_text():
        fail("spines", "DESIGN.md has no '### Finish bar' under Do's and Don'ts")
    for md in sorted(ws.glob("*.md")):
        for target in LINK.findall(md.read_text()):
            if not re.match(r"^[a-z]+:", target) and not (md.parent / unquote(target)).exists():
                fail("spines", f"{md.name}: broken link {target}")

    for w in warns:
        print("warn " + w)
    for f in fails:
        print("FAIL " + f)
    print(f"[ux-handoff] {len(fails)} failure(s), {len(warns)} warning(s); sku={sku or 'unknown'}")
    return EXIT_DRIFT if fails else EXIT_OK


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("requests")
    p.add_argument("--ws", required=True)
    p.add_argument("--ids")
    p.add_argument("--keyed", action="store_true")
    p.add_argument("--force", action="store_true")
    p = sub.add_parser("manifest")
    p.add_argument("--ws", required=True)
    p.add_argument("--check", action="store_true")
    p = sub.add_parser("models")
    p.add_argument("--ws", required=True)
    p.add_argument("--check", action="store_true")
    p.add_argument("--probe", action="store_true")
    p = sub.add_parser("sheet")
    p.add_argument("--ws", required=True)
    p.add_argument("--ids")
    p.add_argument("--beside-crop", action="store_true")
    p.add_argument("--per-sheet", type=int, default=30)
    p = sub.add_parser("key-out")
    p.add_argument("src")
    p.add_argument("--out")
    p.add_argument("--color", default="FF00FF")
    p.add_argument("--tol", type=float, default=40)
    p.add_argument("--soft", type=float, default=60)
    p = sub.add_parser("check")
    p.add_argument("--ws", required=True)
    p.add_argument("--sku")
    a = ap.parse_args()
    return {"requests": cmd_requests, "manifest": cmd_manifest, "models": cmd_models, "sheet": cmd_sheet,
            "key-out": cmd_key_out, "check": cmd_check}[a.cmd](a)


if __name__ == "__main__":
    sys.exit(main())
