#!/usr/bin/env python3
# GENERATED by PrototypeFramework 0.4.2 from Documentation~/agent/tools/visual-scorecard.py — do not edit here. Change it in the framework repo, then run Framework/Agent Docs/Sync (editor) or Tools/Build/pf-build.sh agentdocs.
"""Score one finish-story run: did the surface end up looking like the approved design, and what
did it cost to get there?

    python3 Tools/pf/visual-scorecard.py --spec <spec.md> --variant baseline
    python3 Tools/pf/visual-scorecard.py --spec <spec.md> --variant baseline \\
            --human Tools/UiGate/tuning/runs/8-1-baseline-human.md          # after rating by hand
    python3 Tools/pf/visual-scorecard.py --compare 8-1            # every scored run

Four numbers answer "was the workflow effective", and they are kept apart on purpose — a single
blended score would let a cheap run that looks wrong tie with an expensive one that looks right:

  1. FIDELITY — does the final render match the approved design?
       human   the person who approved the mockup rates every contract row 0/1/2 (the gold number)
       judge   a HELD-OUT judgement: N fresh `--measure` samples on the final captures, majority per
               row. Not the loop's own last verdict — the loop optimised against that one.
       pixels  model-free distance to the approved mockup, before → after: palette ΔE, layout
               correlation, colourfulness and detail ratios. A sanity check that cannot be gamed by
               wording, not a target (DIVERGENCES.md allows a different layout).
  2. JUDGE AGREEMENT — held-out judge vs human, per row. This is the judge's precision on real
     output, which the mutation suite (judge-calibrate.py) can only approximate.
  3. LOOP — judge rounds, per-row trajectory, rows flipped VIOLATED → SATISFIED, HALTs, broken
     captures, cache hits, calls per call site (stage / audit / lens).
  4. COST — Claude (Tools/bmad/run-cost.py when the SKU has it: list-price $, wall) and Codex (calls, seconds, tokens).

Each invocation appends one line to `Tools/UiGate/tuning/runs.jsonl` and writes a report to
`Tools/UiGate/tuning/runs/`. Held-out samples already taken on the same final captures are reused,
so re-running with `--human` after rating costs no model call. `--close` then moves the story's
judge archive to `Tools/UiGate/captures/_runs/`, so the NEXT tuning run of the same story starts
with no HALT history and no cache hits from this one — close every run before starting the next.
"""

import argparse
import glob
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import uigate_lib as L  # noqa: E402

TUNING = L.TUNING  # the SKU's data: tuning/baseline/, runs/, runs.jsonl
RUNS = os.path.join(TUNING, "runs")
LOG = os.path.join(TUNING, "runs.jsonl")
SHORT = {"SATISFIED": "S", "VIOLATED": "V", "CANNOT-TELL": "c"}


def frontmatter(spec):
    text = open(spec, encoding="utf-8").read()
    m = re.match(r"---\n(.*?)\n---", text, re.S)
    fm = {}
    if m:
        for line in m.group(1).splitlines():
            k, _, v = line.partition(":")
            if v and not line.startswith(" "):
                fm[k.strip()] = v.strip().strip("'\"")
    block = re.search(r"^## Auto Run Result\s*\n(.*?)(?=^## |\Z)", text, re.M | re.S)
    blocking = re.search(r"[Bb]locking condition:\s*(.*)", block.group(1)) if block else None
    return fm, (blocking.group(1).strip() if blocking else "")


def claude_cost(story):
    # bmad-loop's cost reader ships with the BMAD fork's SKU tools, not with the framework: optional.
    tool = os.path.join(L.ROOT, "Tools", "bmad", "run-cost.py")
    if not story or not os.path.exists(tool):
        return {}
    p = subprocess.run([sys.executable, tool, story], cwd=L.ROOT, capture_output=True, text=True)
    out = p.stdout
    get = lambda pat: (lambda m: float(m.group(1).replace(",", "")) if m else None)(re.search(pat, out))
    return {"cost_usd": get(r"COST \(list API prices\)\s+\$([\d,\.]+)"),
            "wall_min": get(r"wall ([\d\.]+) min"),
            "subagent_legs": get(r"subagent legs\s+([\d\.]+)")}


def human_scores(path):
    if not path or not os.path.exists(path):
        return None
    scores = {}
    for m in re.finditer(r"^V(\d+):\s*([012])\b", open(path, encoding="utf-8").read(), re.M):
        scores[int(m.group(1))] = int(m.group(2))
    return scores or None


def write_human_template(path, surface, rows, scored, block, compare_png):
    if os.path.exists(path):
        return
    ref = L.resolve(block, block["references"][0][0], True) if block["references"] else "?"
    lines = [f"# Human rating — {surface}", "",
             "Rate the FINAL render against the approved design, one row at a time.",
             "2 = clearly matches the approved design · 1 = partly / arguable · 0 = does not.",
             "Leave a row blank if you cannot tell. Then re-run visual-scorecard.py with --human <this file>.", "",
             f"- side by side: `{os.path.relpath(compare_png, L.ROOT)}` (approved | before | after)",
             f"- approved mockup: `{os.path.relpath(ref, L.ROOT)}`"]
    lines += [f"- capture: `{p}` — {lbl}" for p, lbl in block["captures"]]
    lines.append("")
    for n in scored:
        lines += [f"<!-- {rows[n][:160]} -->", f"V{n}: ", ""]
    lines += ["overall (0-10): ", "notes: ", ""]
    os.makedirs(os.path.dirname(path), exist_ok=True)
    open(path, "w", encoding="utf-8").write("\n".join(lines))


def compare_image(out, pairs):
    """approved | before | after, one strip per capture, 360 px wide columns."""
    from PIL import Image, ImageDraw
    strips = []
    for ref, before, after in pairs:
        cols = [p for p in (ref, before, after)]
        ims = []
        for p in cols:
            im = Image.new("RGB", (360, 640), (40, 40, 40))
            if p and os.path.exists(p):
                im = Image.open(p).convert("RGB").resize((360, 640))
            ims.append(im)
        strip = Image.new("RGB", (360 * 3 + 20, 640 + 28), (24, 24, 24))
        d = ImageDraw.Draw(strip)
        for i, (im, t) in enumerate(zip(ims, ("approved", "before", "after"))):
            strip.paste(im, (i * 370, 28))
            d.text((i * 370 + 6, 6), t, fill=(230, 230, 230))
        strips.append(strip)
    sheet = Image.new("RGB", (strips[0].width, sum(s.height for s in strips)), (24, 24, 24))
    y = 0
    for s in strips:
        sheet.paste(s, (0, y))
        y += s.height
    os.makedirs(os.path.dirname(out), exist_ok=True)
    sheet.save(out, "JPEG", quality=85)


def pct(v):
    return "n/a" if v is None else f"{100 * v:.0f}%"


def compare(story):
    if not os.path.exists(LOG):
        print("no runs scored yet")
        return 0
    runs = [json.loads(l) for l in open(LOG) if l.strip()]
    runs = [r for r in runs if not story or r.get("story", "").startswith(story)]
    cols = [("variant", "variant"), ("fid. human", "fidelity_human"), ("fid. judge", "fidelity_judge"),
            ("judge~human", "judge_human_agreement"), ("policy", "loop_policy"), ("rounds", "rounds"), ("halts", "halts"),
            ("codex calls", "codex_calls"), ("codex s", "codex_seconds"), ("claude $", "claude_cost_usd"),
            ("wall min", "claude_wall_min"), ("status", "status")]
    print(" | ".join(c for c, _ in cols))
    for r in runs:
        vals = []
        for _, k in cols:
            v = r.get(k)
            vals.append(pct(v) if k.startswith(("fidelity", "judge_human")) else ("—" if v is None else str(v)))
        print(" | ".join(vals))
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--spec", help="the story spec (or a contract file) whose Visual Contract was judged")
    ap.add_argument("--variant", default="unnamed", help="name of the workflow variant under test")
    ap.add_argument("--story", help="story key prefix for run-cost.py (default: from the spec name)")
    ap.add_argument("--surface", help="judge archive folder (default: the spec's basename, as the judge does)")
    ap.add_argument("--eval-samples", type=int, default=3, help="held-out judge samples (0 = skip)")
    ap.add_argument("--human", help="a filled-in human rating file")
    ap.add_argument("--before", default=os.path.join(TUNING, "baseline"),
                    help="folder holding the pre-story captures, matched by file name")
    ap.add_argument("--close", action="store_true",
                    help="after scoring, move this story's judge archive aside so the next run starts clean")
    ap.add_argument("--compare", metavar="STORY", nargs="?", const="", help="print every scored run and exit")
    a = ap.parse_args()

    if a.compare is not None:
        return compare(a.compare)
    if not a.spec:
        ap.error("--spec is required")

    spec = os.path.abspath(a.spec)
    surface = a.surface or os.path.splitext(os.path.basename(spec))[0]
    m = re.search(r"(\d+-\d+)", os.path.basename(spec))
    story = a.story or (m.group(1) if m else "")
    section = L.contract_section(spec)
    block = L.contract_block(section)
    rows = L.contract_rows(section)
    scored = L.scored_rows(rows)
    fm, blocking = frontmatter(spec) if os.path.exists(spec) else ({}, "")
    now = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    tag = f"{story or surface}-{a.variant}"

    # --- 3. the loop, from the archive -------------------------------------------------------------
    archive_surface = surface
    if not os.path.isdir(os.path.join(L.ARCHIVE, surface)):
        closed = sorted(glob.glob(os.path.join(L.ARCHIVE, "_runs", f"{surface}--{a.variant}--*")))
        closed = [c for c in closed if not c.endswith("-eval")]
        if closed:
            archive_surface = os.path.relpath(closed[-1], L.ARCHIVE)
    recs = L.records(archive_surface)
    calls = [r for r in recs if r["model_call"] and r.get("verdict") in ("ok", "drift")]
    hits = [r for r in recs if not r["model_call"]]
    broken = [r for r in recs if r.get("verdict") == "error"]
    halts = L.halts(archive_surface)
    by_caller = {}
    for r in recs:
        c = r.get("caller", "unknown")
        by_caller.setdefault(c, [0, 0])
        by_caller[c][0 if r["model_call"] else 1] += 1
    rounds, seen = [], set()
    for r in calls:
        h = r.get("captures-sha256") or r.get("capture-sha256")
        if h not in seen:
            seen.add(h)
            rounds.append(r)
    sat = lambda r: sum(1 for n in scored if r["verdicts"].get(n, ("",))[0] == "SATISFIED")
    flipped = []
    if rounds:
        first, last = rounds[0]["verdicts"], rounds[-1]["verdicts"]
        flipped = [n for n in scored if first.get(n, ("",))[0] == "VIOLATED" and last.get(n, ("",))[0] == "SATISFIED"]
    final_caps = {i["sha"] for i in (rounds[-1]["images"] if rounds else []) if i["kind"] == "CURRENT"}
    looped = [r for r in recs if r.get("loop", "none") != "none"]
    loop_policy = looped[-1].get("loop-policy") if looped else None
    loop_stops = [f"{r.get('caller')}: {r['loop']}" for r in looped if r["loop"].startswith("stop")]

    # --- 1b. held-out judge --------------------------------------------------------------------------
    disk_caps = {}
    for p, _ in block["captures"]:
        full = L.resolve(block, p, False)
        if os.path.exists(full):
            disk_caps[p] = subprocess.run(["shasum", "-a", "256", full], capture_output=True, text=True).stdout.split(" ")[0]
    stale = bool(final_caps) and set(disk_caps.values()) != final_caps
    # Held-out samples on THESE captures that an earlier invocation already paid for are reused.
    eval_surface = f"{surface}-eval"
    on_disk = set(disk_caps.values())
    eval_recs = [r for r in L.records(eval_surface) + L.records(os.path.join("_runs", f"{surface}--{a.variant}--eval"))
                 if r.get("verdict") in ("ok", "drift")
                 and {i["sha"] for i in r["images"] if i["kind"] == "CURRENT"} == on_disk][-a.eval_samples:] \
        if a.eval_samples > 0 else []
    for s in range(len(eval_recs), max(0, a.eval_samples)):
        rc, rec, tail = L.run_judge(spec, eval_surface, "eval", measure=True)
        if rec and rec.get("verdict") in ("ok", "drift"):
            eval_recs.append(rec)
        else:
            print(f"[scorecard] eval sample {s + 1} did not run (exit {rc}):\n{tail[-600:]}", file=sys.stderr)
    maj, agree = L.majority([r["verdicts"] for r in eval_recs], scored) if eval_recs else ({}, {})
    fid_judge = (sum(1 for n in scored if maj.get(n) == "SATISFIED") / len(scored)) if maj else None
    judge_consistency = (sum(agree.values()) / len(agree)) if agree else None

    # --- 1c. pixels ------------------------------------------------------------------------------------
    pixels, pairs = [], []
    ref0 = L.resolve(block, block["references"][0][0], True) if block["references"] else None
    for p, lbl in block["captures"]:
        after = L.resolve(block, p, False)
        before = os.path.join(a.before, os.path.basename(p))
        before = before if os.path.exists(before) else None
        pairs.append((ref0, before, after))
        if ref0 and os.path.exists(after):
            row = {"capture": p, "after": L.image_metrics(after, ref0)}
            if before:
                row["before"] = L.image_metrics(before, ref0)
            pixels.append(row)
    compare_png = os.path.join(RUNS, f"{tag}-compare.jpg")
    if pairs and ref0:
        compare_image(compare_png, pairs)

    # --- 1a / 2. human, and the judge's agreement with it --------------------------------------------
    human_path = a.human or os.path.join(RUNS, f"{tag}-human.md")
    hs = human_scores(a.human)
    if not hs:
        write_human_template(human_path, surface, rows, scored, block, compare_png)
    fid_human = (sum(hs.get(n, 0) for n in scored if n in hs) / (2 * len([n for n in scored if n in hs]))) if hs else None
    comparable = [n for n in scored if hs and n in hs and hs[n] != 1 and maj.get(n) in ("SATISFIED", "VIOLATED")]
    agreement = (sum(1 for n in comparable if (hs[n] == 2) == (maj[n] == "SATISFIED")) / len(comparable)) if comparable else None
    disagree = [n for n in comparable if (hs[n] == 2) != (maj[n] == "SATISFIED")]

    # --- 4. cost -----------------------------------------------------------------------------------------
    cc = claude_cost(story)

    entry = dict(
        when=now, story=story, surface=surface, variant=a.variant, spec=os.path.relpath(spec, L.ROOT),
        status=fm.get("status"), blocking=blocking or None, route=fm.get("route"), kind=fm.get("kind"),
        fidelity_human=fid_human, fidelity_judge=fid_judge, judge_consistency=judge_consistency,
        judge_human_agreement=agreement, judge_human_disagree=[f"V{n}" for n in disagree],
        eval_majority={f"V{n}": v for n, v in maj.items()},
        rounds=len(rounds), halts=len(halts), loop_policy=loop_policy, loop_stops=loop_stops, broken_captures=len(broken), cache_hits=len(hits),
        codex_calls=len(calls), codex_seconds=sum(r["duration-s"] for r in calls),
        codex_tokens=sum(r["tokens"] for r in calls),
        eval_calls=len(eval_recs), eval_seconds=sum(r["duration-s"] for r in eval_recs),
        calls_by_caller={k: {"model": v[0], "cache": v[1]} for k, v in by_caller.items()},
        first_round_satisfied=sat(rounds[0]) if rounds else None,
        last_round_satisfied=sat(rounds[-1]) if rounds else None, scored_rows=len(scored),
        flipped=[f"V{n}" for n in flipped], pixels=pixels, captures_stale=stale,
        judge_model=(calls or eval_recs or [{}])[-1].get("model"),
        judge_effort=(calls or eval_recs or [{}])[-1].get("effort"),
        claude_cost_usd=cc.get("cost_usd"), claude_wall_min=cc.get("wall_min"),
        claude_subagent_legs=cc.get("subagent_legs"),
    )

    # --- report --------------------------------------------------------------------------------------------
    traj = ["| row | " + " | ".join(f"R{i + 1}" for i in range(len(rounds))) + " | held-out | human |",
            "|---|" + "---|" * (len(rounds) + 2)]
    for n in sorted(rows):
        cells = [SHORT.get(r["verdicts"].get(n, ("-",))[0], "-") for r in rounds]
        h = "" if not hs or n not in hs else str(hs[n])
        traj.append(f"| V{n} | " + " | ".join(cells) + f" | {SHORT.get(maj.get(n, ''), '-')} | {h} |")
    pix = ["| capture | palette ΔE before → after | layout corr | colourfulness | detail |", "|---|---|---|---|---|"]
    for p in pixels:
        b, f = p.get("before", {}), p["after"]
        arrow = lambda k: f"{b.get(k, '—')} → {f[k]}"
        pix.append(f"| `{os.path.basename(p['capture'])}` | {arrow('palette_dE')} | {arrow('layout_corr')} | "
                   f"{arrow('colourfulness_ratio')} | {arrow('detail_ratio')} |")
    callers = ", ".join(f"{k} {v[0]}+{v[1]} cached" for k, v in sorted(by_caller.items())) or "none"
    report = f"""# Visual scorecard — {story or surface} — {a.variant}

{now} · spec `{entry['spec']}` · status **{entry['status']}**{f' (blocked: {blocking})' if blocking else ''} · route {entry['route']}

## Headline

| | |
|---|---|
| **fidelity — human** (0/1/2 per row → %) | **{pct(fid_human)}**{'' if hs else f' — not rated yet: fill `{os.path.relpath(human_path, L.ROOT)}`, then re-run with `--human`'} |
| **fidelity — held-out judge** ({len(eval_recs)} samples, rows SATISFIED) | **{pct(fid_judge)}** (consistency {pct(judge_consistency)}) |
| judge ↔ human agreement | {pct(agreement)}{(' — disagree on ' + ', '.join(entry['judge_human_disagree'])) if disagree else ''} |
| loop | policy `{loop_policy or '—'}` · {len(rounds)} rounds · SATISFIED {entry['first_round_satisfied']} → {entry['last_round_satisfied']} of {len(scored)} · flipped {', '.join(entry['flipped']) or 'none'} · {len(halts)} HALT · {len(broken)} broken capture |
| Codex | {len(calls)} calls, {entry['codex_seconds']} s, {entry['codex_tokens']:,} tokens · cache hits {len(hits)} · by caller: {callers} · model `{entry['judge_model']}` / `{entry['judge_effort']}` |
| Claude | ${cc.get('cost_usd') or '—'} list price · {cc.get('wall_min') or '—'} min wall · {cc.get('subagent_legs') or '—'} subagent legs |
{('| LOOP stops | ' + ' · '.join(loop_stops) + ' |') if loop_stops else ''}
{'| **WARNING** | the captures on disk are not the ones the loop last judged — the held-out numbers describe a different render |' if stale else ''}

## Per-row trajectory

S satisfied · V violated · c cannot-tell. R1…Rn are the loop's judge rounds (one per distinct capture);
held-out is the majority of the fresh samples; human is the 0/1/2 rating.

{chr(10).join(traj)}

## Pixels vs the approved mockup (model-free)

palette ΔE: lower is closer · layout corr: 1 = same composition · colourfulness / detail: 1 = same as mockup.

{chr(10).join(pix)}

Side by side: `{os.path.relpath(compare_png, L.ROOT)}`
"""
    os.makedirs(RUNS, exist_ok=True)
    out = os.path.join(RUNS, f"{tag}-{now}.md")
    open(out, "w", encoding="utf-8").write(report)
    with open(LOG, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry) + "\n")
    print(report)
    print(f"[scorecard] wrote {os.path.relpath(out, L.ROOT)} and appended tuning/runs.jsonl")

    if a.close:
        for src, dst in ((surface, f"{surface}--{a.variant}--{now}"), (eval_surface, f"{surface}--{a.variant}--eval")):
            src, dst = os.path.join(L.ARCHIVE, src), os.path.join(L.ARCHIVE, "_runs", dst)
            if os.path.isdir(src):
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                if os.path.exists(dst):
                    for f in os.listdir(src):
                        shutil.move(os.path.join(src, f), os.path.join(dst, f))
                    os.rmdir(src)
                else:
                    shutil.move(src, dst)
                print(f"[scorecard] moved {os.path.relpath(src, L.ROOT)} -> {os.path.relpath(dst, L.ROOT)}")
        print("[scorecard] closed — the next run of this story starts with an empty judge archive")
    return 0


if __name__ == "__main__":
    sys.exit(main())
