#!/bin/sh
# GENERATED by PrototypeFramework 0.4.2 from Documentation~/agent/tools/visual-judge.sh — do not edit here. Change it in the framework repo, then run Framework/Agent Docs/Sync (editor) or Tools/Build/pf-build.sh agentdocs.
# visual-judge.sh — settle a spec's `## Visual Contract` against a real capture.
#
# The contract says what a looker must be able to see; this asks a vision model to
# settle every row against the pixels that actually shipped. It never edits anything,
# never approves a golden, and never answers a question an image cannot settle — a row
# whose truth lives in a scale factor, a hex value or a sorting order comes back
# CANNOT-TELL, which is the signal to write a field assertion for it instead.
#
# This is the CEILING gate — "does it look right?", the question a `kind: finish` story has to
# answer. The FLOOR question a `kind: function` story needs — "is it wired up at all?" — is
# settled deterministically, with no model and no quota, by `Tools/pf/pixel-probe.py`.
# Run the floor first: it is free, it is reproducible, and a floor failure makes every ceiling
# verdict meaningless.
#
# Usage:
#   Tools/pf/visual-judge.sh (--spec <spec.md> | --contract <file>)
#                            [--capture <png>[|label]]... [--reference <png>[|label]]...
#                            [--notes <file>[#section]]... [--model <name>] [--effort <level>]
#                            [--surface <name>] [--caller <name>]
#                            [--dry-run] [--no-cache] [--measure]
#
#   --spec       a spec file; the `## Visual Contract` section is extracted from it
#   --contract   a file that already holds just the contract
#   --capture    a CURRENT render under test. Repeatable. `path|label` names the fixture it shows,
#                so a row that says which fixture it applies to can be matched to its image.
#   --reference  an APPROVED image of this surface — a mockup a person signed off, a finish
#                benchmark, an interaction specimen. Repeatable, and every reference a row names
#                must be here: a row that compares against an image the judge was never handed
#                returns CANNOT-TELL forever, or worse, SATISFIED on anything. References are
#                attached FIRST, in the order given, then the captures; the prompt carries a
#                numbered legend of every image, so each verdict can cite which one it read.
#   --notes      deliberate divergences the judge must not re-flag. Repeatable. `file#section`
#                extracts only the `## section…` block of a larger divergences file.
#   --model      override the model (else VISUAL_JUDGE_MODEL, else judge.conf, else Codex default)
#   --effort     reasoning effort (else VISUAL_JUDGE_EFFORT, else judge.conf, else Codex default)
#   --surface    archive folder name; defaults to the contract/spec file's basename
#   --caller     who is asking (stage, audit, lens, eval…) — recorded in the archive so a run's
#                judge calls can be counted per call site. Else VISUAL_JUDGE_CALLER, else `unknown`.
#   --dry-run    do every check, print the prompt and the exact `codex` argv, and stop before
#                spending a model call. Nothing is archived (there is no verdict to archive).
#   --no-cache   always call the model, even when this exact input was judged before
#   --measure    a measurement run: implies --no-cache and skips the HALT check, so the same
#                input can be sampled repeatedly. Never use it inside an implementation loop.
#
# The inputs block. A `## Visual Contract` may end with ONE fenced block whose info string is
# `visual-judge`. It is the machine-readable half of the contract — the images and notes every
# caller must pass — so the implementing stage, the audit and the review lens all judge exactly the
# same inputs by running `visual-judge.sh --spec <spec>` and nothing else. The block is stripped from
# the prompt; the legend replaces it. Flags given on the command line are ADDED to it; an image that
# is already in (same bytes) is not attached twice.
#
#     ```visual-judge
#     root: _bmad-output/planning-artifacts/ux-designs/<package>   # base for reference/notes paths
#     reference: mockups/key-gameplay-01.png | approved mockup — rows 1-10
#     reference: imports/IMG_4110.PNG | finish benchmark — row 10 only
#     capture: Tools/UiGate/captures/gameplay-finish.png | fixture gameplay-finish — rows 1-10
#     notes: DIVERGENCES.md#gameplay
#     ```
#
#   Capture paths are relative to the directory the judge runs from (the repository root);
#   `root:` applies to `reference:` and `notes:` only.
#
# Exit-code contract (CliConventions.ExitCode): 0 Ok · 1 Drift · 2 Error · 3 Intent gap.
#   0 = every row SATISFIED or CANNOT-TELL
#   1 = at least one row VIOLATED
#   2 = could not run (no codex, no capture, no contract, BROKEN CAPTURE, transport failure)
#   3 = HALT: the same row has been VIOLATED twice running and the capture has not moved a
#       pixel since. The loop is not converging — the row is asking the fixture for something
#       the fixture cannot give. Stop coding and re-read the row.
#
# Four things this does before it will spend a model call
#
#   1. BROKEN-CAPTURE CHECK, on every capture. A capture that is very nearly one flat colour did
#      not render; it is a capture-pipeline fault, not a UI fault. That exits 2 naming the file and
#      the measured variance — never 1, and never a VIOLATED row, because every row would come
#      back VIOLATED and every one of those verdicts would name the wrong cause. This is not
#      hypothetical: `judge-calibration.md` records the Game View's render texture reading back
#      a uniform `RGBA(0.098, 0.098, 0.122, 1)` across the whole frame, and the loop that met it
#      spent model calls to be told, wrongly, that the UI was broken.
#
#   2. HALT CHECK. The archive is read back before the model is called. Same row VIOLATED in
#      each of the last two runs, and all three — those two and this one — on byte-identical
#      captures? Then the edits are not reaching the pixels, and the model has nothing new to
#      look at. (One re-judge of an unchanged capture is a cache hit, not a HALT.)
#      Exit 3 instead. A row asking for something unsatisfiable on its own fixture has spun
#      this loop four rounds for nothing before.
#
#   3. CACHE. "Only judge a capture that changed", enforced: when the whole input — prompt, every
#      image's bytes, model, effort, encoding and sample count — hashes to a run already archived,
#      that run's verdict is returned and archived again as a cache hit, with no model call. The
#      audit and the review lens that re-judge the stage's final capture therefore cost nothing.
#      A cache hit REPLAYS a verdict, it does not re-derive one. The model is not deterministic:
#      measured 2026-09-23, an input judged all-SATISFIED at 03:58Z (input-sha256 2d9ddd…) came
#      back with three rows VIOLATED in 3 of 3 re-runs that evening. With UIGATE_JUDGE_SAMPLES=1
#      the cache freezes whatever that single draw said. With a higher setting it freezes a
#      settled verdict, which is the only kind worth freezing (see SAMPLES below).
#
#   4. ARCHIVE. A HALT appends one line to `<surface>/halts.log` instead. Every other run lands in `Tools/UiGate/captures/<surface>/<stamp>-<verdict>.{png,md}`
#      — the captures as they were judged, plus the caller, the model, the effort, every image
#      with its hash, the V-lines, the wall time, the tokens and the hash of the contract that
#      produced them. Without it a row that failed four rounds running leaves nothing behind, and
#      nobody can say where the drift started, whether the contract moved under it, or what the
#      judge cost.
#
# Environment
#   VISUAL_JUDGE_MODEL      default model (overrides judge.conf)
#   VISUAL_JUDGE_EFFORT     default reasoning effort, passed as `-c model_reasoning_effort=…`
#   VISUAL_JUDGE_CALLER     default --caller
#   UIGATE_ROOT             the SKU's UiGate data folder; default `Tools/UiGate`, resolved from this
#                           script's own location (`Tools/pf/../UiGate`), not from the cwd
#   UIGATE_ARCHIVE_ROOT     archive root; default `$UIGATE_ROOT/captures`, so the evidence trail
#                           lands with the SKU's UiGate data rather than in the framework-owned
#                           folder this script is synced into
#   UIGATE_MIN_VARIANCE     flat-capture threshold in luma variance; default 4.0
#   UIGATE_PYTHON           interpreter for `pixel-probe.py` and the image downscale; default `python3`
#   UIGATE_JUDGE_SHORT_SIDE every attached image is downscaled (never up) so its short side is at most
#                           this many px before it is sent; default 768 — what a vision model's
#                           high-detail mode keeps anyway. Measured: nine full-size images (~14 MB
#                           of PNG) made `codex exec` loop on `Reconnecting… n/5` and never answer;
#                           the same nine at 768 answered in one call. `0` sends originals.
#   UIGATE_JUDGE_FORMAT     `jpeg` (default) or `png`: how each downscaled image is encoded for the
#                           wire. An image with any transparent pixel is always sent as PNG. Measured
#                           2026-09-23 on the same nine images, interleaved in the same time windows:
#                           768 px PNG = 8.3 MB, 398–860 s per call (median 714 s, n=7); JPEG q90
#                           4:4:4 = 2.1 MB (PSNR ~42 dB), 63–76 s (n=5), identical token counts —
#                           the model sees the same pixels, only the upload shrinks. A call that
#                           takes 14 minutes is a call every caller's cap kills: that, not an
#                           outage, is what made story 8.1's seven audit attempts "never answer".
#   UIGATE_JUDGE_JPEG_QUALITY  JPEG quality 1-95; default 90. Chroma is never subsampled (4:4:4),
#                           so thin coloured outlines — row highlights, warning rims — keep their
#                           hue at the edge, which is exactly what those contract rows judge.
#   UIGATE_JUDGE_TIMEOUT    wall-clock seconds ALL model calls of one run may take together; default
#                           840. It sits under the 15-minute ceiling of Claude Code's Bash tool, so
#                           the judge reports its own timeout (exit 2, "no answer within Ns") before
#                           the host kills it without a word. `0` disables. Callers must NOT wrap
#                           the judge in a shorter `pf-timeout`: a run the caller kills early can
#                           never answer, and the same capture then looks like a dead transport.
#   UIGATE_JUDGE_SAMPLES    K, the number of independent model calls that must AGREE before a row's
#                           verdict counts; default 2 — one call is a draw, not a verdict: a
#                           byte-identical input measured on a SKU flipped rows between runs. With K>1 the
#                           judge makes K calls in parallel; any row they do not settle gets one more
#                           call at a time, up to 2K-1 calls in all. A row whose majority never
#                           reaches K is reported VIOLATED and marked `unsettled`: the judge will
#                           not sign off a row it cannot reproduce. Each V-line then ends with its
#                           votes, e.g. `[votes of 3: VIOLATED 2 · SATISFIED 1]`. --measure forces 1.
#   UIGATE_LOOP_POLICY      `fixed` (default) or `progress` — see THE LOOP LINE below
#   UIGATE_LOOP_MAX_ROUNDS  the ceiling on rounds per caller; default 3
#
# THE LOOP LINE. Outside --measure, every verdict ends with one line the caller follows instead of
# counting rounds itself:
#
#     [visual-judge] LOOP: round 2/6 · caller stage · policy progress · VIOLATED 10 → 6
#                    · cleared V1,V2,V5,V6 · newly VIOLATED none · continue
#
#   A round is one distinct set of captures judged for this caller (a cache hit is not a new
#   round); the delta is against the previous distinct captures judged on this surface, whoever
#   judged them. The decision is `done` (nothing VIOLATED), `stop (…)` or `continue`:
#     fixed     continue until the caller has spent UIGATE_LOOP_MAX_ROUNDS rounds.
#     progress  continue while every round leaves FEWER rows VIOLATED than the round before; stop
#               at the first round that does not, or at the ceiling. UI work moves many rows per
#               pass, so a flat count is the signal that the next pass is guessing.
#   The HALT check (exit 3) still stops a single row that is stuck on unchanged pixels, under
#   either policy. The line is advisory text on stdout: exit codes are unchanged.
#
# judge.conf — `$UIGATE_ROOT/judge.conf`, SKU-owned, `KEY=value` lines. Read keys:
#   VISUAL_JUDGE_MODEL, VISUAL_JUDGE_EFFORT, UIGATE_MIN_VARIANCE, UIGATE_JUDGE_SHORT_SIDE,
#   UIGATE_JUDGE_FORMAT, UIGATE_JUDGE_JPEG_QUALITY, UIGATE_JUDGE_TIMEOUT, UIGATE_JUDGE_SAMPLES,
#   UIGATE_LOOP_POLICY, UIGATE_LOOP_MAX_ROUNDS. It exists because the judge runs
#   Codex with `--ignore-user-config` (so the repo's own agent hooks never reach it), which also
#   drops the user's `~/.codex/config.toml` model and effort: without a pin, the judge silently
#   runs the CLI's built-in default, and a catch rate measured on one model says nothing about
#   another.

set -eu

HERE=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PROBE="$HERE/pixel-probe.py"
PYTHON="${UIGATE_PYTHON:-python3}"
UIGATE_ROOT="${UIGATE_ROOT:-$(CDPATH= cd -- "$HERE/.." && pwd)/UiGate}"
# The archive belongs with the SKU's UiGate DATA, not beside this script: this file is synced from
# the framework into `Tools/pf/` and is overwritten on every sync, while the archive is the evidence
# trail the HALT check reads back across runs.
ARCHIVE_ROOT="${UIGATE_ARCHIVE_ROOT:-$UIGATE_ROOT/captures}"
CONF="$UIGATE_ROOT/judge.conf"

die() { echo "[visual-judge] ERROR: $*" >&2; exit 2; }
note() { echo "[visual-judge] $*" >&2; }

# conf_get KEY — the last `KEY=value` line of judge.conf, surrounding quotes stripped.
conf_get() {
    [ -f "$CONF" ] || return 0
    sed -n "s/^[ 	]*$1[ 	]*=[ 	]*//p" "$CONF" | tail -1 | sed 's/[ 	]*#.*$//; s/^"\(.*\)"$/\1/; s/[ 	]*$//'
}

MIN_VARIANCE="${UIGATE_MIN_VARIANCE:-$(conf_get UIGATE_MIN_VARIANCE)}"
MIN_VARIANCE="${MIN_VARIANCE:-4.0}"

SHORT_SIDE="${UIGATE_JUDGE_SHORT_SIDE:-$(conf_get UIGATE_JUDGE_SHORT_SIDE)}"
SHORT_SIDE="${SHORT_SIDE:-768}"
SEND_FORMAT="${UIGATE_JUDGE_FORMAT:-$(conf_get UIGATE_JUDGE_FORMAT)}"
SEND_FORMAT="${SEND_FORMAT:-jpeg}"
case "$SEND_FORMAT" in jpeg|png) ;; *) die "UIGATE_JUDGE_FORMAT must be jpeg or png, not '$SEND_FORMAT'" ;; esac
JPEG_QUALITY="${UIGATE_JUDGE_JPEG_QUALITY:-$(conf_get UIGATE_JUDGE_JPEG_QUALITY)}"
JPEG_QUALITY="${JPEG_QUALITY:-90}"
JUDGE_TIMEOUT="${UIGATE_JUDGE_TIMEOUT:-$(conf_get UIGATE_JUDGE_TIMEOUT)}"
JUDGE_TIMEOUT="${JUDGE_TIMEOUT:-840}"
SAMPLES="${UIGATE_JUDGE_SAMPLES:-$(conf_get UIGATE_JUDGE_SAMPLES)}"
SAMPLES="${SAMPLES:-2}"
for _kv in "UIGATE_JUDGE_JPEG_QUALITY=$JPEG_QUALITY" "UIGATE_JUDGE_TIMEOUT=$JUDGE_TIMEOUT" "UIGATE_JUDGE_SAMPLES=$SAMPLES"; do
    case "${_kv#*=}" in ''|*[!0-9]*) die "${_kv%%=*} must be a whole number, not '${_kv#*=}'" ;; esac
done
[ "$SAMPLES" -ge 1 ] || die "UIGATE_JUDGE_SAMPLES must be at least 1"
{ [ "$JPEG_QUALITY" -ge 1 ] && [ "$JPEG_QUALITY" -le 95 ]; } || die "UIGATE_JUDGE_JPEG_QUALITY must be 1-95"
LOOP_POLICY="${UIGATE_LOOP_POLICY:-$(conf_get UIGATE_LOOP_POLICY)}"
LOOP_POLICY="${LOOP_POLICY:-fixed}"
LOOP_MAX="${UIGATE_LOOP_MAX_ROUNDS:-$(conf_get UIGATE_LOOP_MAX_ROUNDS)}"
LOOP_MAX="${LOOP_MAX:-3}"
case "$LOOP_POLICY" in fixed|progress) ;; *) echo "[visual-judge] ERROR: UIGATE_LOOP_POLICY must be fixed or progress, not '$LOOP_POLICY'" >&2; exit 2 ;; esac

# Two runs' captures count as "the same pixels" if their luma variance agrees this closely.
# The hash is tried first; this is the fallback for a re-encode that changed bytes but not image.
VARIANCE_EPSILON="0.5"

WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT
: > "$WORK/cli-captures"
: > "$WORK/cli-references"
: > "$WORK/cli-notes"

SPEC=""
CONTRACT=""
SURFACE=""
DRY_RUN=0
NO_CACHE=0
MEASURE=0
MODEL_ARG=""
EFFORT_ARG=""
CALLER="${VISUAL_JUDGE_CALLER:-}"

while [ $# -gt 0 ]; do
    case "$1" in
        --capture)   [ $# -ge 2 ] || die "--capture needs a path";   printf '%s\n' "$2" >> "$WORK/cli-captures";   shift 2 ;;
        --reference) [ $# -ge 2 ] || die "--reference needs a path"; printf '%s\n' "$2" >> "$WORK/cli-references"; shift 2 ;;
        --notes)     [ $# -ge 2 ] || die "--notes needs a path";     printf '%s\n' "$2" >> "$WORK/cli-notes";      shift 2 ;;
        --spec)      [ $# -ge 2 ] || die "--spec needs a path";      SPEC="$2";       shift 2 ;;
        --contract)  [ $# -ge 2 ] || die "--contract needs a path";  CONTRACT="$2";   shift 2 ;;
        --surface)   [ $# -ge 2 ] || die "--surface needs a name";   SURFACE="$2";    shift 2 ;;
        --model)     [ $# -ge 2 ] || die "--model needs a name";     MODEL_ARG="$2";  shift 2 ;;
        --effort)    [ $# -ge 2 ] || die "--effort needs a level";   EFFORT_ARG="$2"; shift 2 ;;
        --caller)    [ $# -ge 2 ] || die "--caller needs a name";    CALLER="$2";     shift 2 ;;
        --dry-run)   DRY_RUN=1; shift ;;
        --no-cache)  NO_CACHE=1; shift ;;
        --measure)   MEASURE=1; NO_CACHE=1; shift ;;
        -h|--help)   awk 'NR>1{ if (substr($0,1,1)!="#") exit; sub(/^# ?/,""); print }' "$0"; exit 0 ;;
        *)           die "unknown argument '$1'" ;;
    esac
done

MODEL="${MODEL_ARG:-${VISUAL_JUDGE_MODEL:-$(conf_get VISUAL_JUDGE_MODEL)}}"
EFFORT="${EFFORT_ARG:-${VISUAL_JUDGE_EFFORT:-$(conf_get VISUAL_JUDGE_EFFORT)}}"
CALLER="${CALLER:-unknown}"
# A measurement samples the model one call at a time, repeatedly — that is its whole point.
[ "$MEASURE" -eq 0 ] || SAMPLES=1

[ "$DRY_RUN" -eq 1 ] || command -v codex >/dev/null 2>&1 || die "codex CLI not found on PATH"

hash_file() {
    if command -v shasum >/dev/null 2>&1; then shasum -a 256 "$1" | cut -d' ' -f1
    elif command -v sha256sum >/dev/null 2>&1; then sha256sum "$1" | cut -d' ' -f1
    else cksum "$1" | cut -d' ' -f1
    fi
}

trim() { sed 's/^[ 	]*//; s/[ 	]*$//'; }

# --- the contract -----------------------------------------------------------
if [ -n "$CONTRACT" ]; then
    [ -f "$CONTRACT" ] || die "contract not found: $CONTRACT"
    cp "$CONTRACT" "$WORK/contract-raw.md"
    CONTRACT_SOURCE="$CONTRACT"
elif [ -n "$SPEC" ]; then
    [ -f "$SPEC" ] || die "spec not found: $SPEC"
    awk '/^## Visual Contract/{f=1} f&&/^## /&&!/^## Visual Contract/{exit} f' "$SPEC" > "$WORK/contract-raw.md"
    [ -s "$WORK/contract-raw.md" ] || die "no '## Visual Contract' section in $SPEC"
    CONTRACT_SOURCE="$SPEC"
else
    die "give either --spec or --contract"
fi

# Split the inputs block off the prose: the block is for this script, the prose is for the model.
awk '/^[ \t]*```visual-judge[ \t]*$/{f=1;next} f&&/^[ \t]*```[ \t]*$/{exit} f' "$WORK/contract-raw.md" \
    | sed 's/[ 	]#[^|]*$//' > "$WORK/block.txt"
awk '/^[ \t]*```visual-judge[ \t]*$/{s=1;next} s&&/^[ \t]*```[ \t]*$/{s=0;next} !s' "$WORK/contract-raw.md" > "$WORK/contract.md"
CONTRACT_HASH=$(hash_file "$WORK/contract-raw.md")

block_values() { sed -n "s/^[ 	]*$1:[ 	]*//p" "$WORK/block.txt"; }
ROOT=$(block_values root | tail -1 | trim)

# resolve_path REL USE_ROOT — absolute paths pass through; relative ones join ROOT when asked to.
resolve_path() {
    case "$1" in
        /*) printf '%s\n' "$1" ;;
        *)  if [ "$2" = "1" ] && [ -n "$ROOT" ]; then printf '%s/%s\n' "$ROOT" "$1"; else printf '%s\n' "$1"; fi ;;
    esac
}

# --- the images -------------------------------------------------------------
# images.tsv: KIND <TAB> path <TAB> label <TAB> sha256 — references first, then captures, each in
# the order given (block first, then the command line). An image already listed under the same
# kind with the same bytes is not attached twice.
: > "$WORK/images.tsv"
add_image() {  # add_image KIND SPEC USE_ROOT
    _spec="$2"
    _path=$(printf '%s' "${_spec%%|*}" | trim)
    case "$_spec" in *"|"*) _label=$(printf '%s' "${_spec#*|}" | trim) ;; *) _label="" ;; esac
    [ -n "$_path" ] || return 0
    _path=$(resolve_path "$_path" "$3")
    [ -f "$_path" ] || die "$(echo "$1" | tr 'A-Z' 'a-z') not found: $_path"
    _sha=$(hash_file "$_path")
    if awk -F'\t' -v k="$1" -v s="$_sha" '$1==k && $4==s {found=1} END{exit !found}' "$WORK/images.tsv"; then
        return 0
    fi
    printf '%s\t%s\t%s\t%s\n' "$1" "$_path" "$_label" "$_sha" >> "$WORK/images.tsv"
}

block_values reference > "$WORK/block-references"
block_values capture   > "$WORK/block-captures"
while IFS= read -r l; do add_image REFERENCE "$l" 1; done < "$WORK/block-references"
while IFS= read -r l; do add_image REFERENCE "$l" 0; done < "$WORK/cli-references"
while IFS= read -r l; do add_image CURRENT   "$l" 0; done < "$WORK/block-captures"
while IFS= read -r l; do add_image CURRENT   "$l" 0; done < "$WORK/cli-captures"

awk -F'\t' '$1=="CURRENT"{print $2}' "$WORK/images.tsv" > "$WORK/captures.txt"
[ -s "$WORK/captures.txt" ] || die "no capture given (neither --capture nor a 'capture:' line in the inputs block)"
REF_COUNT=$(awk -F'\t' '$1=="REFERENCE"' "$WORK/images.tsv" | wc -l | tr -d ' ')
CAP_COUNT=$(wc -l < "$WORK/captures.txt" | tr -d ' ')

# The capture the archive names first and the variance fallback measures.
PRIMARY=$(sed -n '1p' "$WORK/captures.txt")
PRIMARY_HASH=$(awk -F'\t' '$1=="CURRENT"{print $4; exit}' "$WORK/images.tsv")
awk -F'\t' '$1=="CURRENT"{print $4}' "$WORK/images.tsv" > "$WORK/capture-hashes.txt"
CAPTURES_HASH=$(hash_file "$WORK/capture-hashes.txt")

# --- the notes --------------------------------------------------------------
: > "$WORK/notes.md"
add_notes() {  # add_notes SPEC USE_ROOT
    _spec=$(printf '%s' "$1" | trim)
    [ -n "$_spec" ] || return 0
    case "$_spec" in *"#"*) _file="${_spec%%#*}"; _sec="${_spec#*#}" ;; *) _file="$_spec"; _sec="" ;; esac
    _file=$(resolve_path "$_file" "$2")
    [ -f "$_file" ] || die "notes not found: $_file"
    if [ -n "$_sec" ]; then
        awk -v sec="$_sec" '
            BEGIN { want = "## " tolower(sec) }
            /^## / { if (f) exit; if (index(tolower($0), want) == 1) f = 1 }
            f' "$_file" > "$WORK/notes-part.md"
        [ -s "$WORK/notes-part.md" ] || die "notes section '## $_sec' not found in $_file"
        cat "$WORK/notes-part.md" >> "$WORK/notes.md"
    else
        cat "$_file" >> "$WORK/notes.md"
    fi
    echo >> "$WORK/notes.md"
    echo "$_file${_sec:+#$_sec}" >> "$WORK/notes-sources.txt"
}
block_values notes > "$WORK/block-notes"
while IFS= read -r l; do add_notes "$l" 1; done < "$WORK/block-notes"
while IFS= read -r l; do add_notes "$l" 0; done < "$WORK/cli-notes"
NOTES_SOURCES=$( [ -f "$WORK/notes-sources.txt" ] && tr '\n' ' ' < "$WORK/notes-sources.txt" | sed 's/ *$//' || true)

# --- where this run gets filed ----------------------------------------------
if [ -z "$SURFACE" ]; then
    SURFACE=$(basename "$CONTRACT_SOURCE"); SURFACE=${SURFACE%.*}
fi
case "$SURFACE" in
    */*|"") die "surface name must be a single path segment, got '$SURFACE'" ;;
esac
ARCHIVE_DIR="$ARCHIVE_ROOT/$SURFACE"

# A stamp unique within the folder and still ordered lexically: a cache hit can land in the same
# second as the run it reuses, and `.N` sorts after `-` so the later run stays later.
STAMP=$(date -u +%Y%m%dT%H%M%SZ)
if [ -d "$ARCHIVE_DIR" ]; then
    _base="$STAMP"; _n=0
    while ls "$ARCHIVE_DIR/$STAMP"-*.md >/dev/null 2>&1; do _n=$((_n + 1)); STAMP="$_base.$_n"; done
fi

: > "$WORK/verdicts.txt"
VARIANCE="unmeasured"
DURATION=""
TOKENS=""
CACHE_STATE="miss"
[ "$NO_CACHE" -eq 1 ] && CACHE_STATE="off"

# archive <verdict> <model> — writes <stamp>-<verdict>.png (+ -N.png per extra capture) and .md,
# echoes the .md path.
archive() {
    _verdict="$1"
    _model="$2"
    mkdir -p "$ARCHIVE_DIR"
    _i=0
    while IFS= read -r _c; do
        _i=$((_i + 1))
        if [ "$_i" -eq 1 ]; then cp "$_c" "$ARCHIVE_DIR/$STAMP-$_verdict.png"
        else cp "$_c" "$ARCHIVE_DIR/$STAMP-$_verdict-$_i.png"; fi
    done < "$WORK/captures.txt"
    {
        echo "# visual-judge — $SURFACE — $_verdict"
        echo
        echo "- when: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
        echo "- verdict: $_verdict"
        echo "- caller: $CALLER"
        echo "- model: ${_model:-unknown}"
        echo "- model-requested: ${MODEL:-codex-default}"
        echo "- effort: ${EFFORT:-codex-default}"
        echo "- cache: $CACHE_STATE"
        echo "- duration-s: ${DURATION:-0}"
        echo "- tokens: ${TOKENS:-unknown}"
        echo "- samples: ${NSAMP:-0} call(s), $SAMPLES agreeing required"
        echo "- sent: ${SENT_DESC:-unknown} (short side $SHORT_SIDE, jpeg q$JPEG_QUALITY)"
        echo "- capture: $PRIMARY"
        echo "- capture-sha256: $PRIMARY_HASH"
        echo "- captures-sha256: $CAPTURES_HASH"
        echo "- capture-variance: $VARIANCE"
        echo "- input-sha256: ${INPUT_HASH:-none}"
        echo "- loop-policy: $LOOP_POLICY/$LOOP_MAX"
        echo "- round: ${LOOP_ROUND:-none}"
        echo "- loop: ${LOOP_DECISION:-none}"
        echo "- contract: $CONTRACT_SOURCE"
        echo "- contract-sha256: $CONTRACT_HASH"
        echo "- notes: ${NOTES_SOURCES:-none}"
        awk -F'\t' '{ printf "- image: %d %s %s sha256=%s%s\n", NR, $1, $2, $4, ($3 != "" ? " | " $3 : "") }' "$WORK/images.tsv"
        echo
        echo "## Verdicts"
        echo
        if [ -s "$WORK/verdicts.txt" ]; then cat "$WORK/verdicts.txt"; else echo "(none — the run stopped before the model was asked)"; fi
        if [ "${NSAMP:-0}" -gt 1 ]; then
            # Indented, so no reader of the record (cache, HALT, LOOP — all grep `^V<n> |`) can
            # mistake one call's vote for the verdict.
            echo
            echo "## Samples"
            _s=1
            while [ "$_s" -le "$NSAMP" ]; do
                echo
                echo "### Sample $_s ($(cut -d' ' -f2 "$WORK/rc-$_s" 2>/dev/null || echo '?')s)"
                echo
                sed 's/^/    /' "$WORK/v-$_s.txt" 2>/dev/null || true
                _s=$((_s + 1))
            done
        fi
    } > "$ARCHIVE_DIR/$STAMP-$_verdict.md"
    echo "$ARCHIVE_DIR/$STAMP-$_verdict.md"
}

# --- (1) broken-capture check, every capture ----------------------------------
# Deliberately soft when the helper is unavailable: a missing python must not turn a gate that
# used to run into a gate that refuses to. It is only ever hard when the check actually ran and
# actually found a flat frame.
if [ ! -f "$PROBE" ]; then
    note "WARNING: $PROBE is missing — skipping the broken-capture check."
elif ! command -v "$PYTHON" >/dev/null 2>&1; then
    note "WARNING: '$PYTHON' not on PATH — skipping the broken-capture check."
else
    while IFS= read -r _c; do
        if _v=$("$PYTHON" "$PROBE" --variance-only "$_c" --min-variance "$MIN_VARIANCE" 2>"$WORK/variance.err"); then
            note "capture variance $_v (>= $MIN_VARIANCE) — $_c carries real content"
            if [ "$_c" = "$PRIMARY" ]; then VARIANCE="$_v"; fi
        else
            VRC=$?
            if [ "$VRC" -eq 1 ]; then
                cat "$WORK/variance.err" >&2
                echo "[visual-judge] BROKEN CAPTURE: $_c has luma variance $_v, below the $MIN_VARIANCE floor." >&2
                echo "[visual-judge] The frame is essentially one flat colour: nothing was rendered into it." >&2
                echo "[visual-judge] This is a capture-pipeline fault. No model was called and no row was judged —" >&2
                echo "[visual-judge] a VIOLATED verdict here would name the wrong cause. Fix the capture, then re-run." >&2
                [ "$DRY_RUN" -eq 1 ] || note "archived: $(archive error "")"
                exit 2
            fi
            cat "$WORK/variance.err" >&2
            note "WARNING: the broken-capture check could not run on $_c (exit $VRC) — continuing without it."
        fi
    done < "$WORK/captures.txt"
fi

# --- (2) HALT check ----------------------------------------------------------
# Read back the last two archived runs. If a row was VIOLATED in both and these captures are the
# same pixels as the last ones, the model has nothing new to see and the loop is not converging.
if [ "$MEASURE" -eq 0 ] && [ -d "$ARCHIVE_DIR" ]; then
    ls "$ARCHIVE_DIR"/*.md 2>/dev/null | sort | tail -2 > "$WORK/recent.txt" || true
    if [ "$(wc -l < "$WORK/recent.txt" | tr -d ' ')" = "2" ]; then
        PREV1=$(sed -n '1p' "$WORK/recent.txt")   # older
        PREV2=$(sed -n '2p' "$WORK/recent.txt")   # most recent
        grep -E '^V[0-9]+ *\| *VIOLATED' "$PREV1" 2>/dev/null | sed 's/[^V0-9].*//' | sort -u > "$WORK/v1.txt" || true
        grep -E '^V[0-9]+ *\| *VIOLATED' "$PREV2" 2>/dev/null | sed 's/[^V0-9].*//' | sort -u > "$WORK/v2.txt" || true
        REPEATED=$(comm -12 "$WORK/v1.txt" "$WORK/v2.txt" | tr '\n' ' ' | sed 's/ *$//')

        if [ -n "$REPEATED" ]; then
            # "Twice with no pixel change": BOTH earlier runs judged these same pixels. A single
            # re-judge of an unchanged capture (the audit or the lens after the stage) is a cache hit,
            # not a stuck loop — only a second one is.
            PREV_ALL=$(sed -n 's/^- captures-sha256: //p' "$PREV2" | head -1)
            PREV1_ALL=$(sed -n 's/^- captures-sha256: //p' "$PREV1" | head -1)
            PREV_HASH=$(sed -n 's/^- capture-sha256: //p' "$PREV2" | head -1)
            PREV_VAR=$(sed -n 's/^- capture-variance: //p' "$PREV2" | head -1)
            PREV1_VAR=$(sed -n 's/^- capture-variance: //p' "$PREV1" | head -1)
            UNCHANGED=0
            WHY=""
            if [ -n "$PREV_ALL" ] && [ "$PREV_ALL" = "$CAPTURES_HASH" ] && [ "$PREV1_ALL" = "$CAPTURES_HASH" ]; then
                UNCHANGED=1
                WHY="captures are byte-identical across all three runs (sha256 $CAPTURES_HASH)"
            elif [ -z "$PREV_ALL" ] && [ -n "$PREV_HASH" ] && [ "$PREV_HASH" = "$PRIMARY_HASH" ]; then
                UNCHANGED=1
                WHY="capture is byte-identical to the previous run (sha256 $PRIMARY_HASH)"
            elif [ -n "$PREV_ALL" ] && [ "$PREV_ALL" != "$CAPTURES_HASH" ]; then
                :   # the pixels moved since the last run: not stuck, whatever the variance says
            elif [ "$CAP_COUNT" -eq 1 ] && [ -n "$PREV_VAR" ] && [ -n "$PREV1_VAR" ] && [ "$VARIANCE" != "unmeasured" ] && [ "$PREV_VAR" != "unmeasured" ] && [ "$PREV1_VAR" != "unmeasured" ]; then
                if [ "$($PYTHON -c "print(1 if max(abs(float('$VARIANCE') - float('$PREV_VAR')), abs(float('$VARIANCE') - float('$PREV1_VAR'))) < float('$VARIANCE_EPSILON') else 0)" 2>/dev/null || echo 0)" = "1" ]; then
                    UNCHANGED=1
                    WHY="capture variance moved by less than $VARIANCE_EPSILON ($PREV_VAR -> $VARIANCE)"
                fi
            fi
            if [ "$UNCHANGED" -eq 1 ]; then
                echo "[visual-judge] HALT — intent_gap: row(s) $REPEATED unchanged after 2 rounds." >&2
                echo "[visual-judge] Each of $REPEATED came back VIOLATED in both of the last two runs, and the" >&2
                echo "[visual-judge] $WHY." >&2
                echo "[visual-judge] The model would answer identically; no call was made." >&2
                echo "[visual-judge] Prior runs: $PREV1" >&2
                echo "[visual-judge]             $PREV2" >&2
                echo "[visual-judge] This is a contract problem, not a code problem: the row is asking this" >&2
                echo "[visual-judge] fixture for something it cannot show. Re-read the row, and either fix the" >&2
                echo "[visual-judge] fixture, rewrite the row, or demote it to a field assertion." >&2
                # Logged beside the records, never as one: a HALT record would become "the last run"
                # and the next identical call would sail past this check to the model.
                echo "$(date -u +%Y-%m-%dT%H:%M:%SZ) caller=$CALLER rows=$(echo "$REPEATED" | tr ' ' ',') captures-sha256=$CAPTURES_HASH" >> "$ARCHIVE_DIR/halts.log"
                exit 3
            fi
        fi
    fi
fi

# --- the prompt -------------------------------------------------------------
{
    echo "You are settling a visual contract against a real render. Judge ONLY the attached images."
    echo
    echo "## The attached images, in attachment order"
    echo
    awk -F'\t' '{ printf "- Image %d — %s — `%s`%s\n", NR, $1, $2, ($3 != "" ? " — " $3 : "") }' "$WORK/images.tsv"
    echo
    if [ "$REF_COUNT" -gt 0 ]; then
        echo "Every REFERENCE image is the standard of what 'correct' looks like for the rows its legend"
        echo "line names (a line marked pending-user-review is the current proposal, not yet signed off —"
        echo "judge against it all the same). Every CURRENT image is a render under test. Settle each row"
        echo "against the CURRENT image(s) it applies to, comparing with the REFERENCE image(s) the row or"
        echo "the legend names for it — the first REFERENCE when nothing narrower is named. A treatment a"
        echo "reference also shows is correct by definition — never report it as a fault. Report only"
        echo "where a CURRENT image departs from its reference in a way the row names."
    else
        echo "No reference image is attached: settle each row against the CURRENT image(s) alone."
    fi
    if [ "$CAP_COUNT" -gt 1 ]; then
        echo
        echo "More than one CURRENT image is attached. A row that names a fixture or a state is judged"
        echo "ONLY on the CURRENT image whose legend line names that fixture or state; a row that names"
        echo "none is judged on every CURRENT image it can apply to."
    fi
    echo
    cat "$WORK/contract.md"
    echo
    if [ -s "$WORK/notes.md" ]; then
        echo "## Deliberate divergences — already decided, do NOT report these as faults"
        echo
        cat "$WORK/notes.md"
        echo
    fi
    cat <<'RULES'
## How to answer

Settle every numbered row, in order, one line each, in exactly this format:

    V<n> | SATISFIED | one short sentence, naming the image number(s) you judged
    V<n> | VIOLATED  | what differs, where, in which CURRENT image, against which REFERENCE image
    V<n> | CANNOT-TELL | why an image cannot settle this claim

Rules:
- SATISFIED only if the image positively shows it. Absence of evidence is CANNOT-TELL, not SATISFIED.
- CANNOT-TELL is the correct answer for anything whose truth is a number the eye cannot read —
  an exact scale factor, an exact colour value, a sorting order, a 9-slice mode. Say so plainly.
- CANNOT-TELL is also correct when no attached CURRENT image shows the state a row needs.
- Anything the contract lists as out of scope is correctly absent. Never report it as missing.
- Judge the pixels, not the contract's wording and not what you assume was intended.
- Describe what you see; never propose a fix.
- No preamble, no summary, no recommendations. Only the V-lines.
RULES
} > "$WORK/prompt.txt"

# The whole input, hashed: what the model would see, plus which model and how hard it thinks.
{
    cat "$WORK/prompt.txt"
    awk -F'\t' '{print $4}' "$WORK/images.tsv"
    echo "model=${MODEL:-} effort=${EFFORT:-} short-side=$SHORT_SIDE format=$SEND_FORMAT q=$JPEG_QUALITY samples=$SAMPLES"
} > "$WORK/input.txt"
INPUT_HASH=$(hash_file "$WORK/input.txt")

# --- what is actually sent ---------------------------------------------------
# Every image is downscaled to the resolution the model would keep anyway. Hashes, the legend and
# the archive all name the ORIGINAL file; only the bytes on the wire are smaller.
: > "$WORK/send.txt"
_i=0
while IFS="$(printf '\t')" read -r _k _p _l _s; do
    _i=$((_i + 1))
    _dst="$WORK/send-$_i"
    if [ "$SHORT_SIDE" != "0" ] && _sent=$("$PYTHON" - "$_p" "$_dst" "$SHORT_SIDE" "$SEND_FORMAT" "$JPEG_QUALITY" 2>/dev/null <<'PY'
import sys
from PIL import Image
src, dst, short, fmt, quality = sys.argv[1], sys.argv[2], int(sys.argv[3]), sys.argv[4], int(sys.argv[5])
im = Image.open(src)
im.load()
if im.mode not in ("RGB", "RGBA"):
    im = im.convert("RGBA" if "A" in im.getbands() else "RGB")
w, h = im.size
k = short / min(w, h)
if k < 1:
    im = im.resize((max(1, round(w * k)), max(1, round(h * k))), Image.LANCZOS)
# JPEG has no alpha: an image with any transparent pixel keeps PNG rather than gaining a ground
# nobody drew.
opaque = im.mode == "RGB" or im.getchannel("A").getextrema()[0] == 255
if fmt == "jpeg" and opaque:
    out = dst + ".jpg"
    im.convert("RGB").save(out, "JPEG", quality=quality, subsampling=0, optimize=True)
else:
    out = dst + ".png"
    im.save(out, "PNG", optimize=True)
print(out)
PY
); then
        printf '%s\n' "$_sent" >> "$WORK/send.txt"
    else
        [ "$SHORT_SIDE" = "0" ] || note "WARNING: could not downscale $_p (no Pillow for '$PYTHON'?) — sending the original."
        printf '%s\n' "$_p" >> "$WORK/send.txt"
    fi
done < "$WORK/images.tsv"

_bytes=0
while IFS= read -r _p; do _bytes=$((_bytes + $(wc -c < "$_p" | tr -d ' '))); done < "$WORK/send.txt"
SENT_DESC="$(sed 's/.*\.//' "$WORK/send.txt" | sort | uniq -c | awk '{printf "%s%s×%s", (NR>1?"+":""), $1, $2}') $(awk -v b="$_bytes" 'BEGIN{printf "%.1f MB", b/1048576}')"

# --- argv -------------------------------------------------------------------
# `-i` is variadic, so a positional prompt would be swallowed as another image path:
# the prompt goes on stdin and the argument list ends with `-`.
# References are attached BEFORE the captures — the legend above says so, and the order is what
# makes "Image N" unambiguous.
set -- exec -s read-only --skip-git-repo-check --ephemeral --ignore-user-config
[ -n "$MODEL" ] && set -- "$@" -m "$MODEL"
[ -n "$EFFORT" ] && set -- "$@" -c "model_reasoning_effort=\"$EFFORT\""
set -- "$@" -i
while IFS= read -r _p; do set -- "$@" "$_p"; done < "$WORK/send.txt"
set -- "$@" -

if [ "$DRY_RUN" -eq 1 ]; then
    echo "[visual-judge] DRY RUN — no model call, nothing archived."
    echo "[visual-judge] surface=$SURFACE caller=$CALLER variance=$VARIANCE references=$REF_COUNT captures=$CAP_COUNT short-side=$SHORT_SIDE"
    echo "[visual-judge] sent=$SENT_DESC samples=$SAMPLES agreeing (up to $((2 * SAMPLES - 1)) calls) timeout=${JUDGE_TIMEOUT}s"
    echo "[visual-judge] model=${MODEL:-codex-default} effort=${EFFORT:-codex-default} input-sha256=$INPUT_HASH"
    echo "[visual-judge] would archive to: $ARCHIVE_DIR/$STAMP-<verdict>.{png,md}"
    echo "[visual-judge] argv:"
    printf '  codex'; for a in "$@"; do printf ' %s' "$a"; done; printf ' < prompt\n'
    echo "[visual-judge] prompt:"
    sed 's/^/  | /' "$WORK/prompt.txt"
    exit 0
fi

# --- the loop line ------------------------------------------------------------
# loop_decide — reads $WORK/verdicts.txt and the archive (before this run is archived), sets
# LOOP_ROUND / LOOP_DECISION and prints the LOOP line. Silent under --measure.
LOOP_ROUND=""
LOOP_DECISION=""
loop_decide() {
    [ "$MEASURE" -eq 0 ] || return 0
    grep -E '^V[0-9]+ *\| *VIOLATED' "$WORK/verdicts.txt" | sed 's/ *|.*//' | sort -u > "$WORK/now-v.txt" || true
    _now=$(wc -l < "$WORK/now-v.txt" | tr -d ' ')
    _was=""
    : > "$WORK/prev-v.txt"
    : > "$WORK/caller-rounds.txt"
    _prev=""
    if [ -d "$ARCHIVE_DIR" ]; then
        ls "$ARCHIVE_DIR"/*.md 2>/dev/null | sort -r > "$WORK/all-records.txt" || true
        while IFS= read -r _f; do
            grep -q -E '^- verdict: (ok|drift)$' "$_f" || continue
            _h=$(sed -n 's/^- captures-sha256: //p' "$_f" | head -1)
            [ -n "$_h" ] || continue
            if [ -z "$_prev" ] && [ "$_h" != "$CAPTURES_HASH" ]; then _prev="$_f"; fi
            if grep -q -x -F -- "- caller: $CALLER" "$_f"; then echo "$_h" >> "$WORK/caller-rounds.txt"; fi
        done < "$WORK/all-records.txt"
    fi
    echo "$CAPTURES_HASH" >> "$WORK/caller-rounds.txt"
    LOOP_ROUND=$(sort -u "$WORK/caller-rounds.txt" | wc -l | tr -d ' ')
    _delta="VIOLATED $_now (no earlier round)"
    _cleared="none"; _new="none"
    if [ -n "$_prev" ]; then
        sed -n '/^## Verdicts/,$p' "$_prev" | grep -E '^V[0-9]+ *\| *VIOLATED' | sed 's/ *|.*//' | sort -u > "$WORK/prev-v.txt" || true
        _was=$(wc -l < "$WORK/prev-v.txt" | tr -d ' ')
        _delta="VIOLATED $_was → $_now"
        _cleared=$(comm -23 "$WORK/prev-v.txt" "$WORK/now-v.txt" | tr '\n' ',' | sed 's/,$//')
        _new=$(comm -13 "$WORK/prev-v.txt" "$WORK/now-v.txt" | tr '\n' ',' | sed 's/,$//')
        _cleared=${_cleared:-none}; _new=${_new:-none}
    fi
    if [ "$_now" -eq 0 ]; then
        LOOP_DECISION="done"
    elif [ "$LOOP_ROUND" -ge "$LOOP_MAX" ]; then
        LOOP_DECISION="stop (ceiling: $LOOP_ROUND of $LOOP_MAX rounds spent — report the VIOLATED rows as open)"
    elif [ "$LOOP_POLICY" = "progress" ] && [ -n "$_was" ] && [ "$_now" -ge "$_was" ]; then
        LOOP_DECISION="stop (no progress: $_delta — the next pass would be guessing; report the VIOLATED rows as open)"
    else
        LOOP_DECISION="continue"
    fi
    echo "[visual-judge] LOOP: round $LOOP_ROUND/$LOOP_MAX · caller $CALLER · policy $LOOP_POLICY · $_delta · cleared $_cleared · newly VIOLATED $_new · $LOOP_DECISION"
}

# --- (3) cache ---------------------------------------------------------------
if [ "$NO_CACHE" -eq 0 ] && [ -d "$ARCHIVE_DIR" ]; then
    HIT=$(grep -l -F -- "- input-sha256: $INPUT_HASH" "$ARCHIVE_DIR"/*.md 2>/dev/null \
          | while IFS= read -r f; do grep -q -E '^- verdict: (ok|drift)$' "$f" && echo "$f"; done \
          | sort | tail -1 || true)
    if [ -n "$HIT" ]; then
        sed -n '/^## Verdicts/,$p' "$HIT" | grep -E '^V[0-9]+ *\|' > "$WORK/verdicts.txt" || true
        if [ -s "$WORK/verdicts.txt" ]; then
            CACHE_STATE="hit $(basename "$HIT")"
            MODEL_USED=$(sed -n 's/^- model: //p' "$HIT" | head -1)
            echo "[visual-judge] CACHE HIT — this exact input was judged in $(basename "$HIT"); no model call."
            echo "[visual-judge] model=${MODEL_USED:-unknown} references=$REF_COUNT captures=$CAP_COUNT"
            cat "$WORK/verdicts.txt"
            if grep -q '| *VIOLATED' "$WORK/verdicts.txt"; then
                echo "[visual-judge] DRIFT: $(grep -c '| *VIOLATED' "$WORK/verdicts.txt") row(s) VIOLATED."
                loop_decide
                note "archived: $(archive drift "$MODEL_USED")"
                exit 1
            fi
            echo "[visual-judge] Ok: no row VIOLATED."
            loop_decide
            note "archived: $(archive ok "$MODEL_USED")"
            exit 0
        fi
    fi
fi

# --- run --------------------------------------------------------------------
# Every model call goes through pf-timeout (synced beside this script) so the run owns its own
# ceiling — UIGATE_JUDGE_TIMEOUT, shared by every call of the run — and kills codex's whole
# process group when it fires, instead of a caller's cap killing the judge mid-word.
TIMEOUT_CMD=""
if [ "$JUDGE_TIMEOUT" != "0" ]; then
    if [ -x "$HERE/pf-timeout" ]; then TIMEOUT_CMD="$HERE/pf-timeout"
    else note "WARNING: $HERE/pf-timeout is missing — model calls run without the ${JUDGE_TIMEOUT}s ceiling."; fi
fi

# run_sample N CAP ARGV… — one model call; raw output in raw-N.txt, "<exit> <seconds>" in rc-N.
run_sample() {
    _n=$1; _cap=$2; shift 2
    _t=$(date +%s)
    if [ -n "$TIMEOUT_CMD" ]; then
        if "$TIMEOUT_CMD" "$_cap" codex "$@" < "$WORK/prompt.txt" > "$WORK/raw-$_n.txt" 2>&1; then _rc=0; else _rc=$?; fi
    else
        if codex "$@" < "$WORK/prompt.txt" > "$WORK/raw-$_n.txt" 2>&1; then _rc=0; else _rc=$?; fi
    fi
    echo "$_rc $(( $(date +%s) - _t ))" > "$WORK/rc-$_n"
}

# settle_sample N — validates one finished call and writes its V-lines to v-N.txt; dies (exit 2)
# on anything that is not a verdict. One failed call fails the run: a judge that did not run is
# never a pass, and a vote that was never cast cannot be counted as agreement.
settle_sample() {
    _n=$1
    _rc=$(cut -d' ' -f1 "$WORK/rc-$_n")
    if [ "$_rc" = "124" ] && [ -n "$TIMEOUT_CMD" ]; then
        sed -n '1,20p' "$WORK/raw-$_n.txt" >&2
        die "no answer within the ${JUDGE_TIMEOUT}s ceiling (UIGATE_JUDGE_TIMEOUT, call $_n) — a transport failure, not a verdict. Check the sent= size on the verdict line; never re-run under a shorter cap."
    fi
    if [ "$_rc" != "0" ]; then
        sed -n '1,40p' "$WORK/raw-$_n.txt" >&2
        die "codex exec failed (call $_n, exit $_rc)"
    fi
    # `ERROR: Reconnecting… n/5` is the transport retrying, not a refusal: it is fatal only when the
    # run produced no verdict, which the V-line check below already catches.
    if grep '^ERROR:' "$WORK/raw-$_n.txt" | grep -v -q 'Reconnecting'; then
        grep '^ERROR:' "$WORK/raw-$_n.txt" | grep -v 'Reconnecting' | head -3 >&2
        die "the model or transport refused the request (call $_n)"
    fi
    grep -E '^V[0-9]+ *\|' "$WORK/raw-$_n.txt" | sed 's/^V//' | sort -t'|' -k1,1n -u | sed 's/^/V/' > "$WORK/v-$_n.txt" || true
    [ -s "$WORK/v-$_n.txt" ] || { sed -n '1,40p' "$WORK/raw-$_n.txt" >&2; die "the model returned no V-lines (call $_n)"; }
}

# aggregate — every settled call's V-lines → verdicts.txt. A row takes the status at least
# SAMPLES calls agree on; a row with no such status is written `UNSETTLED` (resolved below).
# With SAMPLES=1 and one call this reproduces that call's V-lines exactly.
aggregate() {
    _s=1
    : > "$WORK/votes.tsv"
    while [ "$_s" -le "$NSAMP" ]; do
        awk -v n="$_s" '
            /^V[0-9]+ *\|/ {
                i = index($0, "|"); row = substr($0, 1, i - 1); rest = substr($0, i + 1)
                j = index(rest, "|"); st = substr(rest, 1, j - 1); txt = substr(rest, j + 1)
                gsub(/^[ \t]+|[ \t]+$/, "", row); gsub(/^[ \t]+|[ \t]+$/, "", st); gsub(/^[ \t]+|[ \t]+$/, "", txt)
                printf "%s\t%s\t%s\t%s\n", n, row, st, txt
            }' "$WORK/v-$_s.txt" >> "$WORK/votes.tsv"
        _s=$((_s + 1))
    done
    awk -F'\t' -v K="$SAMPLES" -v N="$NSAMP" '
        { r = $2; st = $3; c[r, st]++; if (!((r, st) in t)) t[r, st] = $4
          if (!(r in seen)) { seen[r] = 1; order[++nr] = r }
          if (!(st in known)) { known[st] = 1; stats[++ns] = st } }
        END {
            for (i = 1; i <= nr; i++) {
                r = order[i]; win = ""; votes = ""
                for (j = 1; j <= ns; j++) { st = stats[j]
                    if ((r, st) in c) { votes = votes (votes ? " · " : "") st " " c[r, st]; if (c[r, st] >= K) win = st } }
                line = (win != "") ? r " | " win " | " t[r, win] : r " | UNSETTLED | no verdict reached " K " of " N " calls"
                if (N > 1) line = line " [votes of " N ": " votes "]"
                print line
            }
        }' "$WORK/votes.tsv" | sed 's/^V//' | sort -t'|' -k1,1n | sed 's/^/V/' > "$WORK/verdicts.txt"
}

T0=$(date +%s)
NSAMP=0
MAX_SAMPLES=$((2 * SAMPLES - 1))
while [ "$NSAMP" -lt "$SAMPLES" ]; do
    NSAMP=$((NSAMP + 1))
    run_sample "$NSAMP" "$JUDGE_TIMEOUT" "$@" &
done
wait
_s=1; while [ "$_s" -le "$NSAMP" ]; do settle_sample "$_s"; _s=$((_s + 1)); done
aggregate
# Rows the first K calls did not settle get one more call at a time, while the ceiling allows.
while grep -q '| UNSETTLED |' "$WORK/verdicts.txt" && [ "$NSAMP" -lt "$MAX_SAMPLES" ]; do
    _left=$JUDGE_TIMEOUT
    if [ "$JUDGE_TIMEOUT" != "0" ]; then
        _left=$(( JUDGE_TIMEOUT - ($(date +%s) - T0) ))
        if [ "$_left" -lt 60 ]; then
            note "only ${_left}s of the ${JUDGE_TIMEOUT}s ceiling left — no further call; the split row(s) stay unsettled."
            break
        fi
    fi
    NSAMP=$((NSAMP + 1))
    note "row(s) $(grep '| UNSETTLED |' "$WORK/verdicts.txt" | sed 's/ *|.*//' | tr '\n' ' ')split — call $NSAMP of at most $MAX_SAMPLES."
    run_sample "$NSAMP" "$_left" "$@"
    settle_sample "$NSAMP"
    aggregate
done
# A row the calls could not agree on is not signed off: it is VIOLATED, and says why.
sed 's/| UNSETTLED | \(.*\)$/| VIOLATED | unsettled — \1/' "$WORK/verdicts.txt" > "$WORK/verdicts.tmp" && mv "$WORK/verdicts.tmp" "$WORK/verdicts.txt"
DURATION=$(( $(date +%s) - T0 ))

MODEL_USED=$(sed -n 's/^model: //p' "$WORK/raw-1.txt" | head -1)
TOKENS=""
_s=1
while [ "$_s" -le "$NSAMP" ]; do
    _tk=$(grep -i -A1 'tokens used' "$WORK/raw-$_s.txt" | grep -o '[0-9][0-9,]*' | tail -1 | tr -d ',' || true)
    [ -z "$_tk" ] || TOKENS=$(( ${TOKENS:-0} + _tk ))
    _s=$((_s + 1))
done

echo "[visual-judge] model=${MODEL_USED:-unknown} effort=${EFFORT:-codex-default} references=$REF_COUNT captures=$CAP_COUNT ${DURATION}s tokens=${TOKENS:-unknown} calls=$NSAMP agreeing=$SAMPLES sent=$SENT_DESC"
cat "$WORK/verdicts.txt"

if grep -q '| *VIOLATED' "$WORK/verdicts.txt"; then
    echo "[visual-judge] DRIFT: $(grep -c '| *VIOLATED' "$WORK/verdicts.txt") row(s) VIOLATED."
    loop_decide
    note "archived: $(archive drift "$MODEL_USED")"
    exit 1
fi
echo "[visual-judge] Ok: no row VIOLATED."
loop_decide
note "archived: $(archive ok "$MODEL_USED")"
exit 0
